CREATE OR REPLACE PROCEDURE DAAS_ADHOC.TRIP_METRIC_BACKUP_20231226()
RETURNS VARCHAR NOT NULL
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$

proc_output = "";
proc_step = "";

try
{
	snowflake.execute( {sqlText: "BEGIN;" } );
	
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_MASTER_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_MASTER AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_DETAIL_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_DETAIL AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_SUMMARY_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_SUMMARY AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.DAILY_ACTIVITY_SUMMARY_BKP_20231226 AS SELECT * FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_MERGE_PROCESSED_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_MERGE_PROCESSED AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_MERGE_QUEUE_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_MERGE_QUEUE AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_RECALC_PROCESSED_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_RECALC_PROCESSED AT (OFFSET=>-60*60*50);"} );
	snowflake.execute( {sqlText: "CREATE OR REPLACE TABLE DAAS_TEMP.TRIP_RECALC_QUEUE_BKP_20231226 AS SELECT * FROM DAAS_CORE.TRIP_RECALC_QUEUE AT (OFFSET=>-60*60*50);"} );
		
	snowflake.execute( {sqlText: "COMMIT;" } );

	proc_output = "SUCCESS";
}	

catch (err) 
{ 
snowflake.execute( {sqlText: "ROLLBACK;" } );

proc_output += "\n Failed: Code: " + err.code + "\n  State: " + err.state;
proc_output += "\n  Message: " + err.message;
proc_output += "\nStack Trace:\n" + err.stackTraceTxt;
}
 
return proc_output;
$$;