-- Step 1) Suspend TRIP_ROOT_TASK

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK SUSPEND;

-- Step 2) Change the warehouse of the trip jobs to 2xl warehouse



-- Step 3) Increase Task time to 4 Hours

CALL DAAS_COMMON.ALTER_TASK_TIMEOUT_PROC('DAAS_COMMON', 'TRIP_RECALCULATION_ONDEMAND_TASK', 14400000);

-- Step 4) Take backup of Trip tables [Thru Standardized Proc - BACKUP_TABLE_PROC]

CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'DAILY_ACTIVITY_SUMMARY', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_SUMMARY', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_DETAIL', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_MASTER', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_MERGE_PROCESSED', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_MERGE_QUEUE', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_RECALC_PROCESSED', NULL ,NULL);
CALL DAAS_UAT.DAAS_SECURITY.CLONE_TABLE_PROC('DAAS_UAT', 'DAAS_UAT', 'DAAS_CORE', 'TRIP_RECALC_QUEUE', NULL ,NULL);


-- Step 5) Creating table to capture the Ratings Extra SKs

CALL DAAS_ADHOC.RATING_EXTRA_SK_ADHOC_PROC();


-- Step 6) Run the count query to check if the cleanup needs to be performed in chunks
SELECT
	 COUNT(A.TRIP_MASTER_ID)
FROM
		DAAS_CORE.TRIP_MASTER A
JOIN DAAS_CORE.TRIP_DETAIL B
ON
		A.TRIP_MASTER_ID = B.TRIP_MASTER_ID
JOIN (SELECT 
		TM.TRIP_MASTER_ID
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.TRIP_MASTER_ID IN (SELECT DISTINCT TRIP_MASTER_ID FROM DAAS_TEMP.RATING_EXTRA_SKS_CLEANUP_TRIPS)
	AND TM.DELETE_IND = 'N') C
ON
		A.TRIP_MASTER_ID = C.TRIP_MASTER_ID
WHERE
		 A.DELETE_IND = 'N'
	AND B.TRANSACTION_SUB_TYPE = 'OPENED';


-- Step 6) If the count is huge, divide the records into chunks

SELECT MAX(RANK) FROM DAAS_TEMP.RATING_EXTRA_SKS_CLEANUP_TRIPS;


-- Step 7) Run the Adhoc scripts to soft delete the extra SKs and recalculate the trips 

CALL DAAS_ADHOC.RATING_CLEANUP_ADHOC_PROC(LOWER_LIMIT,UPPER_LIMIT);
	

-- Step 8) Execute OnDemand tasks from Recalc to Trip Summary sequentially to cleanup these SKs [Thru OnDemand Tasks]

EXECUTE TASK DAAS_COMMON.TRIP_RECALCULATION_ONDEMAND_TASK;
EXECUTE TASK DAAS_COMMON.TRIP_MERGE_CHECK_ONDEMAND_TASK;
EXECUTE TASK DAAS_COMMON.TRIP_MERGE_ONDEMAND_TASK;
EXECUTE TASK DAAS_COMMON.TRIP_CUSTOMER_MERGE_CHECK_GUEST_GUESTXREF_ONDEMAND_TASK;
EXECUTE TASK DAAS_COMMON.TRIP_CUSTOMER_MERGE_CHECK_TRIP_MASTER_ONDEMAND_TASK;
EXECUTE TASK DAAS_COMMON.TRIP_CUSTOMER_MERGE_ONDEMAND_TASK;
EXECUTE TASK DAAS_COMMON.TRIP_SUMMARY_WRAPPER_ONDEMAND_TASK;

-- Repeat the steps 7 & 8 for all the chunks 


-- Step 9) Ensure there is no more discrepency (Validation)--this should result in 0.

SELECT COUNT(*) 
FROM DAAS_CORE.TRIP_DETAIL TD
JOIN DAAS_CORE.TRIP_MASTER TM
ON TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
WHERE TRANSACTION_TABLE_SK NOT IN (SELECT DISTINCT RATINGS_FACT_SK FROM DAAS_CORE.RATINGS_FACT)
AND TD.TRANSACTION_TYPE = 'RATINGS'
AND TM.DELETE_IND = 'N'
AND TD.DELETE_IND = 'N'
AND TM.GUEST_UNIQUE_ID <> -1;


-- Step 10) Revert back the warehouse of the trip jobs to l warehouse



-- Step 11) Revert back the Task time to 2 Hours

CALL DAAS_COMMON.ALTER_TASK_TIMEOUT_PROC('DAAS_COMMON', 'TRIP_RECALCULATION_ONDEMAND_TASK', 7200000);

--Step 12) Resume TRIP_ROOT_TASK

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK RESUME;







