~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Replay the guest ids of 1sk taggged to 2 guest ids for hotel
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	

Step 1:- Suspend TRIP_ROOT_TASK (Thru Console - Aggergated role)

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK SUSPEND;



Step 2:- Identify the recs having 1 SK tagged to 2 Guests


SELECT COUNT(DISTINCT GUEST_UNIQUE_ID), TD.TRANSACTION_TABLE_SK
FROM DAAS_CORE.TRIP_DETAIL TD
JOIN DAAS_CORE.TRIP_MASTER TM
ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
WHERE TM.DELETE_IND = 'N' AND TD.DELETE_IND = 'N' AND TRANSACTION_TYPE = 'HOTEL' --AND MARKET_CD <> 'CH2'
AND TM.GUEST_UNIQUE_ID <> -1
GROUP BY ALL
HAVING COUNT(DISTINCT GUEST_UNIQUE_ID)>1;



Step 3:- Code Check-in and Deploy the below procedure

	- trip_hotel_domain_pipeline_proc



Step 4:- Replay the ids from hotel domains using "DATA_REPLAY_PROC" (Thru Aggregated role)


-- HOTEL

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT', 
'WHERE HOTEL_GUEST_RESERVATIONS_FACT_SK IN 
(SELECT HOTEL_GUEST_RESERVATIONS_FACT_SK 
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW HGR
WHERE EXISTS
(
	SELECT DISTINCT  TD.TRANSACTION_TABLE_SK --COUNT(DISTINCT TM.GUEST_UNIQUE_ID)
	FROM DAAS_CORE.TRIP_MASTER TM
	JOIN DAAS_CORE.TRIP_DETAIL TD
	ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
    WHERE TD.transaction_table_sk = HGR.hotel_guest_reservations_fact_sk
	and TM.DELETE_IND = ''N'' AND TD.DELETE_IND = ''N'' AND TRANSACTION_TYPE = ''HOTEL''
    GROUP BY ALL
	HAVING COUNT(DISTINCT GUEST_UNIQUE_ID)>1))', '1SK2GUESTS', 100000000);



Step 5:- Execute TRIP_ROOT_TASK (Thru Console)

EXECUTE TASK DAAS_COMMON.TRIP_ROOT_TASK;



Step 6:- Validate TRIP_SUMMARY & DAILY_ACTIVITY_SUMMARY metrics

SELECT --TRANSACTION_TABLE_SK,TRANSACTION_TYPE,
COUNT(DISTINCT GUEST_UNIQUE_ID)
FROM DAAS_CORE.TRIP_DETAIL TD
JOIN DAAS_CORE.TRIP_MASTER TM
ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
WHERE TM.DELETE_IND = 'N' AND TD.DELETE_IND = 'N' AND TRANSACTION_TYPE = 'HOTEL'
GROUP BY ALL
HAVING COUNT(DISTINCT GUEST_UNIQUE_ID)>1;