-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--																		TRIP_SUMMARY
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


-- PropVsEnt

WITH ABS_LOGIC AS
(
SELECT
    TD.TRIP_MASTER_ID,
    COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
    CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
FROM
    DAAS_CORE.TRIP_DETAIL TD
JOIN 
    DAAS_CORE.TRIP_MASTER TM 
ON
    TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
JOIN
    DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
ON
    TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
WHERE
    TD.TRANSACTION_TYPE = 'FREEPLAY'
AND 
    TM.DELETE_IND = 'N'
GROUP BY
    TD.TRIP_MASTER_ID
)
SELECT 
    ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_DOLLAR_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
FROM 
    DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW TS
JOIN 
    ABS_LOGIC AL
ON 
    TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
AND 
    DLC_FSP_FLG = 'Y'
;

-- MktVsEnt:
 

WITH FREEPLAY AS
(
WITH ABS_LOGIC AS
(
SELECT
    TD.TRIP_MASTER_ID,
    COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
    CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
FROM
    DAAS_CORE.TRIP_DETAIL TD
JOIN 
    DAAS_CORE.TRIP_MASTER TM 
ON
    TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
JOIN
    DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
ON
    TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
WHERE
    TD.TRANSACTION_TYPE = 'FREEPLAY'
AND 
    TM.DELETE_IND = 'N'
GROUP BY
    TD.TRIP_MASTER_ID
)
SELECT
    DISTINCT GUEST_UNIQUE_ID,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_DOLLAR_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
FROM 
    DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW TS
JOIN 
    ABS_LOGIC AL
ON 
    TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
AND 
    DLC_FSP_FLG = 'Y'
AND TS.GUEST_UNIQUE_ID <> -1
GROUP BY
    GUEST_UNIQUE_ID
)
SELECT DISTINCT GUEST_UNIQUE_ID
FROM FREEPLAY
WHERE MARKET_DLC_FSP_POINT_AMT <> ENTERPRISE_DLC_FSP_POINT_AMT
;



-- Market Level Validation

WITH ABS_LOGIC AS
(
SELECT
    TD.TRIP_MASTER_ID,
    COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
    CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
FROM
    DAAS_CORE.TRIP_DETAIL TD
JOIN 
    DAAS_CORE.TRIP_MASTER TM 
ON
    TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
JOIN
    DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
ON
    TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
WHERE
    TD.TRANSACTION_TYPE = 'FREEPLAY'
AND 
    TM.DELETE_IND = 'N' AND TD.DELETE_IND = 'N'
GROUP BY
    TD.TRIP_MASTER_ID
)
SELECT 
    GUEST_UNIQUE_ID,
    GUEST_ACTIVITY_DATE,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD = 'NCM' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS MARKET_NCM_DLC_FSP_DOLLAR_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD = 'CH2' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS MARKET_CH2_DLC_FSP_DOLLAR_AMT
FROM 
    DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW TS
JOIN 
    ABS_LOGIC AL
ON 
    TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
WHERE 
    DLC_FSP_FLG = 'Y'
AND 
    TS.GUEST_UNIQUE_ID NOT IN 
    (
    SELECT DISTINCT GUEST_UNIQUE_ID 
    FROM DAAS_CORE.TRIP_MASTER
    WHERE DELETE_IND = 'N'
    AND GUEST_UNIQUE_ID IN 
    (SELECT XREF_ACCOUNT_NBR FROM DAAS_CORE.GUEST_XREF_BRIDGE_LKP WHERE XREF_ACCOUNT_NBR <> PRIMARY_ACCOUNT_NBR)
    )
AND 
   TS.GUEST_ACTIVITY_DATE BETWEEN '2023-01-01' AND '2023-06-01'
GROUP BY GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE
HAVING
    MARKET_NCM_DLC_FSP_DOLLAR_AMT <> 0
AND MARKET_CH2_DLC_FSP_DOLLAR_AMT <> 0
;













-- PropVsEnt

SELECT
	'PROPERTY TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('PROPERTY')
GROUP BY 1
UNION
SELECT
	'ENTERPRISE TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('ENTERPRISE')
GROUP BY 1;



-- MktVsEnt

SELECT
	'MARKET TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('MARKET')
GROUP BY 1
UNION
SELECT
	'ENTERPRISE TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('ENTERPRISE')
AND MARKET_CD <> 'CH2'
GROUP BY 1;

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--																		DAILY_ACTIVITY_SUMMARY
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- PropVsEnt

SELECT
	'PROPERTY TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('PROPERTY')
GROUP BY 1
UNION
SELECT
	'ENTERPRISE TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('ENTERPRISE')
GROUP BY 1;



-- MktVsEnt

SELECT
	'MARKET TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('MARKET')
AND MARKET_CD <> 'CH2'
GROUP BY 1
UNION
SELECT
	'ENTERPRISE TOTALS',
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('ENTERPRISE')
GROUP BY 1;



-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--																			Finding Discrepancy Guests
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- PropVsEnt

WITH CTE_P AS
(
SELECT
	'PROPERTY TOTALS',
	GUEST_UNIQUE_ID,
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('PROPERTY')
GROUP BY 2
),
CTE_E AS
(
SELECT
	'ENTERPRISE TOTALS',
	GUEST_UNIQUE_ID,
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('ENTERPRISE')
GROUP BY 2
)
SELECT DISTINCT CTE_P.GUEST_UNIQUE_ID FROM CTE_P, CTE_E
WHERE
	CTE_P.GUEST_UNIQUE_ID 	= CTE_E.GUEST_UNIQUE_ID
AND	CTE_P.DLC_FSP_POINT_AMT <> CTE_E.DLC_FSP_POINT_AMT
AND CTE_P.GUEST_UNIQUE_ID 	<> -1
ORDER BY CTE_P.GUEST_UNIQUE_ID
;

-- MktVsEnt

WITH CTE_M AS
(
SELECT
	'MARKET TOTALS',
	GUEST_UNIQUE_ID,
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('MARKET')
AND MARKET_CD <> 'CH2'
GROUP BY 2
),
CTE_E AS
(
SELECT
	'ENTERPRISE TOTALS',
	GUEST_UNIQUE_ID,
	SUM(DLC_FSP_POINT_AMT) AS DLC_FSP_POINT_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	TRIP_TYPE IN ('ENTERPRISE')
GROUP BY 2
)
SELECT DISTINCT CTE_M.GUEST_UNIQUE_ID FROM CTE_M, CTE_E
WHERE
	CTE_M.GUEST_UNIQUE_ID 	= CTE_E.GUEST_UNIQUE_ID
AND	CTE_M.DLC_FSP_POINT_AMT <> CTE_E.DLC_FSP_POINT_AMT
AND CTE_M.GUEST_UNIQUE_ID 	<> -1
ORDER BY CTE_M.GUEST_UNIQUE_ID
;





-- PropVsEnt:

WITH FREEPLAY AS
(
WITH ABS_LOGIC AS
(
SELECT
    TD.TRIP_MASTER_ID,
    COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
    CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
FROM
    DAAS_CORE.TRIP_DETAIL TD
JOIN 
    DAAS_CORE.TRIP_MASTER TM 
ON
    TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
JOIN
    DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
ON
    TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
WHERE
    TD.TRANSACTION_TYPE = 'FREEPLAY'
AND 
    TM.DELETE_IND = 'N'
GROUP BY
    TD.TRIP_MASTER_ID
)
SELECT
    DISTINCT GUEST_UNIQUE_ID,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_DOLLAR_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
FROM 
    DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW TS
JOIN 
    ABS_LOGIC AL
ON 
    TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
AND 
    DLC_FSP_FLG = 'Y'
AND TS.GUEST_UNIQUE_ID <> -1
GROUP BY
    GUEST_UNIQUE_ID
)
SELECT DISTINCT GUEST_UNIQUE_ID
FROM FREEPLAY
WHERE PROPERTY_DLC_FSP_POINT_AMT <> ENTERPRISE_DLC_FSP_POINT_AMT
;





-- MktVsEnt:
 

WITH FREEPLAY AS
(
WITH ABS_LOGIC AS
(
SELECT
    TD.TRIP_MASTER_ID,
    COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
    CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
FROM
    DAAS_CORE.TRIP_DETAIL TD
JOIN 
    DAAS_CORE.TRIP_MASTER TM 
ON
    TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
JOIN
    DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
ON
    TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
WHERE
    TD.TRANSACTION_TYPE = 'FREEPLAY'
AND 
    TM.DELETE_IND = 'N'
GROUP BY
    TD.TRIP_MASTER_ID
)
SELECT
    DISTINCT GUEST_UNIQUE_ID,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_POINT_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_DOLLAR_AMT,
    ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
FROM 
    DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW TS
JOIN 
    ABS_LOGIC AL
ON 
    TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
AND 
    DLC_FSP_FLG = 'Y'
AND TS.GUEST_UNIQUE_ID <> -1
GROUP BY
    GUEST_UNIQUE_ID
)
SELECT DISTINCT GUEST_UNIQUE_ID
FROM FREEPLAY
WHERE MARKET_DLC_FSP_POINT_AMT <> ENTERPRISE_DLC_FSP_POINT_AMT
;