/* --------------------------------------------
                    Ratings    
--------------------------------------------*/

SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_TIME_PLAYED_IN_MIN  ELSE 0 END) AS PROP_SLOT_TIME_PLAYED_IN_MIN ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_TIME_PLAYED_IN_MIN  ELSE 0 END) AS MKT_SLOT_TIME_PLAYED_IN_MIN ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_TIME_PLAYED_IN_MIN  ELSE 0 END) AS ENT_SLOT_TIME_PLAYED_IN_MIN ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_TIME_PLAYED_IN_MIN ELSE 0 END) AS PROP_TABLE_TIME_PLAYED_IN_MIN,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_TIME_PLAYED_IN_MIN ELSE 0 END) AS MKT_TABLE_TIME_PLAYED_IN_MIN,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_TIME_PLAYED_IN_MIN ELSE 0 END) AS ENT_TABLE_TIME_PLAYED_IN_MIN,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_TIME_PLAYED_IN_MIN ELSE 0 END) AS PROP_OTHER_TIME_PLAYED_IN_MIN,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_TIME_PLAYED_IN_MIN ELSE 0 END) AS MKT_OTHER_TIME_PLAYED_IN_MIN,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_TIME_PLAYED_IN_MIN ELSE 0 END) AS ENT_OTHER_TIME_PLAYED_IN_MIN,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_BUY_IN_AMT ELSE 0 END) AS PROP_TABLE_BUY_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_BUY_IN_AMT ELSE 0 END) AS MKT_TABLE_BUY_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_BUY_IN_AMT ELSE 0 END) AS ENT_TABLE_BUY_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_COIN_IN_AMT ELSE 0 END) AS PROP_SLOT_COIN_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_COIN_IN_AMT ELSE 0 END) AS MKT_SLOT_COIN_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_COIN_IN_AMT ELSE 0 END) AS ENT_SLOT_COIN_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_COIN_OUT_AMT ELSE 0 END) AS PROP_SLOT_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_COIN_OUT_AMT ELSE 0 END) AS MKT_SLOT_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_COIN_OUT_AMT ELSE 0 END) AS ENT_SLOT_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_CASH_IN_AMT ELSE 0 END) AS PROP_TABLE_CASH_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_CASH_IN_AMT ELSE 0 END) AS MKT_TABLE_CASH_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_CASH_IN_AMT ELSE 0 END) AS ENT_TABLE_CASH_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_BILLS_IN_AMT ELSE 0 END) AS PROP_SLOT_BILLS_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_BILLS_IN_AMT ELSE 0 END) AS MKT_SLOT_BILLS_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_BILLS_IN_AMT ELSE 0 END) AS ENT_SLOT_BILLS_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_CASH_IN_AMT ELSE 0 END) AS PROP_OTHER_CASH_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_CASH_IN_AMT ELSE 0 END) AS MKT_OTHER_CASH_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_CASH_IN_AMT ELSE 0 END) AS ENT_OTHER_CASH_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_COIN_OUT_AMT ELSE 0 END) AS PROP_TABLE_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_COIN_OUT_AMT ELSE 0 END) AS MKT_TABLE_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_COIN_OUT_AMT ELSE 0 END) AS ENT_TABLE_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_COIN_IN_AMT ELSE 0 END) AS PROP_OTHER_COIN_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_COIN_IN_AMT ELSE 0 END) AS MKT_OTHER_COIN_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_COIN_IN_AMT ELSE 0 END) AS ENT_OTHER_COIN_IN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_COIN_OUT_AMT ELSE 0 END) AS PROP_OTHER_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_COIN_OUT_AMT ELSE 0 END) AS MKT_OTHER_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_COIN_OUT_AMT ELSE 0 END) AS ENT_OTHER_COIN_OUT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_JACKPOT_AMT ELSE 0 END) AS PROP_SLOT_JACKPOT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_JACKPOT_AMT ELSE 0 END) AS MKT_SLOT_JACKPOT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_JACKPOT_AMT ELSE 0 END) AS ENT_SLOT_JACKPOT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_JACKPOT_AMT ELSE 0 END) AS PROP_OTHER_JACKPOT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_JACKPOT_AMT ELSE 0 END) AS MKT_OTHER_JACKPOT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_JACKPOT_AMT ELSE 0 END) AS ENT_OTHER_JACKPOT_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_WIN_LOSS_AMT ELSE 0 END) AS PROP_SLOT_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_WIN_LOSS_AMT ELSE 0 END) AS MKT_SLOT_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_WIN_LOSS_AMT ELSE 0 END) AS ENT_SLOT_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_WIN_LOSS_AMT ELSE 0 END) AS PROP_TABLE_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_WIN_LOSS_AMT ELSE 0 END) AS MKT_TABLE_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_WIN_LOSS_AMT ELSE 0 END) AS ENT_TABLE_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_WIN_LOSS_AMT ELSE 0 END) AS PROP_OTHER_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_WIN_LOSS_AMT ELSE 0 END) AS MKT_OTHER_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_WIN_LOSS_AMT ELSE 0 END) AS ENT_OTHER_WIN_LOSS_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_THEO_WIN_AMT ELSE 0 END) AS PROP_SLOT_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_THEO_WIN_AMT ELSE 0 END) AS MKT_SLOT_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_THEO_WIN_AMT ELSE 0 END) AS ENT_SLOT_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_THEO_WIN_AMT ELSE 0 END) AS PROP_TABLE_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_THEO_WIN_AMT ELSE 0 END) AS MKT_TABLE_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_THEO_WIN_AMT ELSE 0 END) AS ENT_TABLE_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_THEO_WIN_AMT ELSE 0 END) AS PROP_OTHER_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_THEO_WIN_AMT ELSE 0 END) AS MKT_OTHER_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_THEO_WIN_AMT ELSE 0 END) AS ENT_OTHER_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TOTAL_THEO_WIN_AMT ELSE 0 END) AS PROP_TOTAL_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TOTAL_THEO_WIN_AMT ELSE 0 END) AS MKT_TOTAL_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TOTAL_THEO_WIN_AMT ELSE 0 END) AS ENT_TOTAL_THEO_WIN_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_POINTS_EARNED_AMT ELSE 0 END) AS PROP_SLOT_POINTS_EARNED_AMT  ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_POINTS_EARNED_AMT ELSE 0 END) AS MKT_SLOT_POINTS_EARNED_AMT  ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_POINTS_EARNED_AMT ELSE 0 END) AS ENT_SLOT_POINTS_EARNED_AMT  ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_POINTS_EARNED_AMT  ELSE 0 END) AS PROP_TABLE_POINTS_EARNED_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_POINTS_EARNED_AMT  ELSE 0 END) AS MKT_TABLE_POINTS_EARNED_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_POINTS_EARNED_AMT  ELSE 0 END) AS ENT_TABLE_POINTS_EARNED_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_POINTS_EARNED_AMT  ELSE 0 END) AS PROP_OTHER_POINTS_EARNED_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_POINTS_EARNED_AMT  ELSE 0 END) AS MKT_OTHER_POINTS_EARNED_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_POINTS_EARNED_AMT  ELSE 0 END) AS ENT_OTHER_POINTS_EARNED_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_HANDLE_PULLS ELSE 0 END) AS PROP_SLOT_HANDLE_PULLS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_HANDLE_PULLS ELSE 0 END) AS MKT_SLOT_HANDLE_PULLS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_HANDLE_PULLS ELSE 0 END) AS ENT_SLOT_HANDLE_PULLS ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_HANDLE_PULLS ELSE 0 END) AS PROP_OTHER_HANDLE_PULLS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_HANDLE_PULLS ELSE 0 END) AS MKT_OTHER_HANDLE_PULLS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_HANDLE_PULLS ELSE 0 END) AS ENT_OTHER_HANDLE_PULLS ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_TOTAL_HANDS_PLAYED ELSE 0 END) AS PROP_TABLE_TOTAL_HANDS_PLAYED,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_TOTAL_HANDS_PLAYED ELSE 0 END) AS MKT_TABLE_TOTAL_HANDS_PLAYED,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_TOTAL_HANDS_PLAYED ELSE 0 END) AS ENT_TABLE_TOTAL_HANDS_PLAYED,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_COUPON_USED ELSE 0 END) AS PROP_SLOT_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_COUPON_USED ELSE 0 END) AS MKT_SLOT_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_COUPON_USED ELSE 0 END) AS ENT_SLOT_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_COUPON_USED ELSE 0 END) AS PROP_TABLE_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_COUPON_USED ELSE 0 END) AS MKT_TABLE_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_COUPON_USED ELSE 0 END) AS ENT_TABLE_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_COUPON_USED ELSE 0 END) AS PROP_OTHER_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_COUPON_USED ELSE 0 END) AS MKT_OTHER_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_COUPON_USED ELSE 0 END) AS ENT_OTHER_COUPON_USED ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_PROMO_CASHLESS ELSE 0 END) AS PROP_SLOT_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_PROMO_CASHLESS ELSE 0 END) AS MKT_SLOT_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_PROMO_CASHLESS ELSE 0 END) AS ENT_SLOT_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_PROMO_CASHLESS ELSE 0 END) AS PROP_TABLE_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_PROMO_CASHLESS ELSE 0 END) AS MKT_TABLE_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_PROMO_CASHLESS ELSE 0 END) AS ENT_TABLE_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_PROMO_CASHLESS ELSE 0 END) AS PROP_OTHER_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_PROMO_CASHLESS ELSE 0 END) AS MKT_OTHER_PROMO_CASHLESS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_PROMO_CASHLESS ELSE 0 END) AS ENT_OTHER_PROMO_CASHLESS 
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_SLOT_TIME_PLAYED_IN_MIN  <> MKT_SLOT_TIME_PLAYED_IN_MIN  OR MKT_SLOT_TIME_PLAYED_IN_MIN  <> ENT_SLOT_TIME_PLAYED_IN_MIN  OR ENT_SLOT_TIME_PLAYED_IN_MIN  <> PROP_SLOT_TIME_PLAYED_IN_MIN ) OR
( PROP_TABLE_TIME_PLAYED_IN_MIN <> MKT_TABLE_TIME_PLAYED_IN_MIN OR MKT_TABLE_TIME_PLAYED_IN_MIN <> ENT_TABLE_TIME_PLAYED_IN_MIN OR ENT_TABLE_TIME_PLAYED_IN_MIN <> PROP_TABLE_TIME_PLAYED_IN_MIN) OR
( PROP_OTHER_TIME_PLAYED_IN_MIN <> MKT_OTHER_TIME_PLAYED_IN_MIN OR MKT_OTHER_TIME_PLAYED_IN_MIN <> ENT_OTHER_TIME_PLAYED_IN_MIN OR ENT_OTHER_TIME_PLAYED_IN_MIN <> PROP_OTHER_TIME_PLAYED_IN_MIN) OR
( PROP_TABLE_BUY_IN_AMT <> MKT_TABLE_BUY_IN_AMT OR MKT_TABLE_BUY_IN_AMT <> ENT_TABLE_BUY_IN_AMT OR ENT_TABLE_BUY_IN_AMT <> PROP_TABLE_BUY_IN_AMT ) OR
( PROP_SLOT_COIN_IN_AMT <> MKT_SLOT_COIN_IN_AMT OR MKT_SLOT_COIN_IN_AMT <> ENT_SLOT_COIN_IN_AMT OR ENT_SLOT_COIN_IN_AMT <> PROP_SLOT_COIN_IN_AMT ) OR
( PROP_SLOT_COIN_OUT_AMT <> MKT_SLOT_COIN_OUT_AMT OR MKT_SLOT_COIN_OUT_AMT <> ENT_SLOT_COIN_OUT_AMT OR ENT_SLOT_COIN_OUT_AMT <> PROP_SLOT_COIN_OUT_AMT ) OR
( PROP_TABLE_CASH_IN_AMT <> MKT_TABLE_CASH_IN_AMT OR MKT_TABLE_CASH_IN_AMT <> ENT_TABLE_CASH_IN_AMT OR ENT_TABLE_CASH_IN_AMT <> PROP_TABLE_CASH_IN_AMT ) OR
( PROP_SLOT_BILLS_IN_AMT <> MKT_SLOT_BILLS_IN_AMT OR MKT_SLOT_BILLS_IN_AMT <> ENT_SLOT_BILLS_IN_AMT OR ENT_SLOT_BILLS_IN_AMT <> PROP_SLOT_BILLS_IN_AMT ) OR
( PROP_OTHER_CASH_IN_AMT <> MKT_OTHER_CASH_IN_AMT OR MKT_OTHER_CASH_IN_AMT <> ENT_OTHER_CASH_IN_AMT OR ENT_OTHER_CASH_IN_AMT <> PROP_OTHER_CASH_IN_AMT ) OR
( PROP_TABLE_COIN_OUT_AMT <> MKT_TABLE_COIN_OUT_AMT OR MKT_TABLE_COIN_OUT_AMT <> ENT_TABLE_COIN_OUT_AMT OR ENT_TABLE_COIN_OUT_AMT <> PROP_TABLE_COIN_OUT_AMT ) OR
( PROP_OTHER_COIN_IN_AMT <> MKT_OTHER_COIN_IN_AMT OR MKT_OTHER_COIN_IN_AMT <> ENT_OTHER_COIN_IN_AMT OR ENT_OTHER_COIN_IN_AMT <> PROP_OTHER_COIN_IN_AMT ) OR
( PROP_OTHER_COIN_OUT_AMT <> MKT_OTHER_COIN_OUT_AMT OR MKT_OTHER_COIN_OUT_AMT <> ENT_OTHER_COIN_OUT_AMT OR ENT_OTHER_COIN_OUT_AMT <> PROP_OTHER_COIN_OUT_AMT ) OR
( PROP_SLOT_JACKPOT_AMT <> MKT_SLOT_JACKPOT_AMT OR MKT_SLOT_JACKPOT_AMT <> ENT_SLOT_JACKPOT_AMT OR ENT_SLOT_JACKPOT_AMT <> PROP_SLOT_JACKPOT_AMT ) OR
( PROP_OTHER_JACKPOT_AMT <> MKT_OTHER_JACKPOT_AMT OR MKT_OTHER_JACKPOT_AMT <> ENT_OTHER_JACKPOT_AMT OR ENT_OTHER_JACKPOT_AMT <> PROP_OTHER_JACKPOT_AMT ) OR
( PROP_SLOT_WIN_LOSS_AMT <> MKT_SLOT_WIN_LOSS_AMT OR MKT_SLOT_WIN_LOSS_AMT <> ENT_SLOT_WIN_LOSS_AMT OR ENT_SLOT_WIN_LOSS_AMT <> PROP_SLOT_WIN_LOSS_AMT ) OR
( PROP_TABLE_WIN_LOSS_AMT <> MKT_TABLE_WIN_LOSS_AMT OR MKT_TABLE_WIN_LOSS_AMT <> ENT_TABLE_WIN_LOSS_AMT OR ENT_TABLE_WIN_LOSS_AMT <> PROP_TABLE_WIN_LOSS_AMT ) OR
( PROP_OTHER_WIN_LOSS_AMT <> MKT_OTHER_WIN_LOSS_AMT OR MKT_OTHER_WIN_LOSS_AMT <> ENT_OTHER_WIN_LOSS_AMT OR ENT_OTHER_WIN_LOSS_AMT <> PROP_OTHER_WIN_LOSS_AMT ) OR
( PROP_SLOT_THEO_WIN_AMT <> MKT_SLOT_THEO_WIN_AMT OR MKT_SLOT_THEO_WIN_AMT <> ENT_SLOT_THEO_WIN_AMT OR ENT_SLOT_THEO_WIN_AMT <> PROP_SLOT_THEO_WIN_AMT ) OR
( PROP_TABLE_THEO_WIN_AMT <> MKT_TABLE_THEO_WIN_AMT OR MKT_TABLE_THEO_WIN_AMT <> ENT_TABLE_THEO_WIN_AMT OR ENT_TABLE_THEO_WIN_AMT <> PROP_TABLE_THEO_WIN_AMT ) OR
( PROP_OTHER_THEO_WIN_AMT <> MKT_OTHER_THEO_WIN_AMT OR MKT_OTHER_THEO_WIN_AMT <> ENT_OTHER_THEO_WIN_AMT OR ENT_OTHER_THEO_WIN_AMT <> PROP_OTHER_THEO_WIN_AMT ) OR
( PROP_TOTAL_THEO_WIN_AMT <> MKT_TOTAL_THEO_WIN_AMT OR MKT_TOTAL_THEO_WIN_AMT <> ENT_TOTAL_THEO_WIN_AMT OR ENT_TOTAL_THEO_WIN_AMT <> PROP_TOTAL_THEO_WIN_AMT ) OR
( PROP_SLOT_POINTS_EARNED_AMT <> MKT_SLOT_POINTS_EARNED_AMT OR MKT_SLOT_POINTS_EARNED_AMT <> ENT_SLOT_POINTS_EARNED_AMT OR ENT_SLOT_POINTS_EARNED_AMT <> PROP_SLOT_POINTS_EARNED_AMT  ) OR
( PROP_TABLE_POINTS_EARNED_AMT  <> MKT_TABLE_POINTS_EARNED_AMT  OR MKT_TABLE_POINTS_EARNED_AMT  <> ENT_TABLE_POINTS_EARNED_AMT  OR ENT_TABLE_POINTS_EARNED_AMT  <> PROP_TABLE_POINTS_EARNED_AMT ) OR
( PROP_OTHER_POINTS_EARNED_AMT  <> MKT_OTHER_POINTS_EARNED_AMT  OR MKT_OTHER_POINTS_EARNED_AMT  <> ENT_OTHER_POINTS_EARNED_AMT  OR ENT_OTHER_POINTS_EARNED_AMT  <> PROP_OTHER_POINTS_EARNED_AMT ) OR
( PROP_SLOT_HANDLE_PULLS <> MKT_SLOT_HANDLE_PULLS OR MKT_SLOT_HANDLE_PULLS <> ENT_SLOT_HANDLE_PULLS OR ENT_SLOT_HANDLE_PULLS <> PROP_SLOT_HANDLE_PULLS ) OR
( PROP_OTHER_HANDLE_PULLS <> MKT_OTHER_HANDLE_PULLS OR MKT_OTHER_HANDLE_PULLS <> ENT_OTHER_HANDLE_PULLS OR ENT_OTHER_HANDLE_PULLS <> PROP_OTHER_HANDLE_PULLS ) OR
( PROP_TABLE_TOTAL_HANDS_PLAYED <> MKT_TABLE_TOTAL_HANDS_PLAYED OR MKT_TABLE_TOTAL_HANDS_PLAYED <> ENT_TABLE_TOTAL_HANDS_PLAYED OR ENT_TABLE_TOTAL_HANDS_PLAYED <> PROP_TABLE_TOTAL_HANDS_PLAYED) OR
( PROP_SLOT_COUPON_USED <> MKT_SLOT_COUPON_USED OR MKT_SLOT_COUPON_USED <> ENT_SLOT_COUPON_USED OR ENT_SLOT_COUPON_USED <> PROP_SLOT_COUPON_USED ) OR
( PROP_TABLE_COUPON_USED <> MKT_TABLE_COUPON_USED OR MKT_TABLE_COUPON_USED <> ENT_TABLE_COUPON_USED OR ENT_TABLE_COUPON_USED <> PROP_TABLE_COUPON_USED ) OR
( PROP_OTHER_COUPON_USED <> MKT_OTHER_COUPON_USED OR MKT_OTHER_COUPON_USED <> ENT_OTHER_COUPON_USED OR ENT_OTHER_COUPON_USED <> PROP_OTHER_COUPON_USED ) OR
( PROP_SLOT_PROMO_CASHLESS <> MKT_SLOT_PROMO_CASHLESS OR MKT_SLOT_PROMO_CASHLESS <> ENT_SLOT_PROMO_CASHLESS OR ENT_SLOT_PROMO_CASHLESS <> PROP_SLOT_PROMO_CASHLESS ) OR
( PROP_TABLE_PROMO_CASHLESS <> MKT_TABLE_PROMO_CASHLESS OR MKT_TABLE_PROMO_CASHLESS <> ENT_TABLE_PROMO_CASHLESS OR ENT_TABLE_PROMO_CASHLESS <> PROP_TABLE_PROMO_CASHLESS ) OR
( PROP_OTHER_PROMO_CASHLESS <> MKT_OTHER_PROMO_CASHLESS OR MKT_OTHER_PROMO_CASHLESS <> ENT_OTHER_PROMO_CASHLESS OR ENT_OTHER_PROMO_CASHLESS <> PROP_OTHER_PROMO_CASHLESS );




/* --------------------------------------------
                    Hotel    
--------------------------------------------*/


SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_ROOM_AMT ELSE 0 END) AS PROP_HOTEL_COMP_ROOM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_ROOM_AMT ELSE 0 END) AS MKT_HOTEL_COMP_ROOM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_ROOM_AMT ELSE 0 END) AS ENT_HOTEL_COMP_ROOM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_OTHER_AMT  ELSE 0 END) AS PROP_HOTEL_COMP_OTHER_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_OTHER_AMT  ELSE 0 END) AS MKT_HOTEL_COMP_OTHER_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_OTHER_AMT  ELSE 0 END) AS ENT_HOTEL_COMP_OTHER_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_AMT_TOTAL  ELSE 0 END) AS PROP_HOTEL_COMP_AMT_TOTAL ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_AMT_TOTAL  ELSE 0 END) AS MKT_HOTEL_COMP_AMT_TOTAL ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_AMT_TOTAL  ELSE 0 END) AS ENT_HOTEL_COMP_AMT_TOTAL ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_ROOM_TAX ELSE 0 END) AS PROP_HOTEL_COMP_ROOM_TAX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_ROOM_TAX ELSE 0 END) AS MKT_HOTEL_COMP_ROOM_TAX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_ROOM_TAX ELSE 0 END) AS ENT_HOTEL_COMP_ROOM_TAX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_OTHER_TAX  ELSE 0 END) AS PROP_HOTEL_COMP_OTHER_TAX ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_OTHER_TAX  ELSE 0 END) AS MKT_HOTEL_COMP_OTHER_TAX ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_OTHER_TAX  ELSE 0 END) AS ENT_HOTEL_COMP_OTHER_TAX ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_ROOM_AMT ELSE 0 END) AS PROP_HOTEL_ROOM_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_ROOM_AMT ELSE 0 END) AS MKT_HOTEL_ROOM_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_ROOM_AMT ELSE 0 END) AS ENT_HOTEL_ROOM_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_OTHER_AMT ELSE 0 END) AS PROP_HOTEL_OTHER_AMT    ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_OTHER_AMT ELSE 0 END) AS MKT_HOTEL_OTHER_AMT    ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_OTHER_AMT ELSE 0 END) AS ENT_HOTEL_OTHER_AMT    ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_AMT_TOTAL ELSE 0 END) AS PROP_HOTEL_AMT_TOTAL    ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_AMT_TOTAL ELSE 0 END) AS MKT_HOTEL_AMT_TOTAL    ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_AMT_TOTAL ELSE 0 END) AS ENT_HOTEL_AMT_TOTAL    ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_ROOM_TAX ELSE 0 END) AS PROP_HOTEL_ROOM_TAX ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_ROOM_TAX ELSE 0 END) AS MKT_HOTEL_ROOM_TAX ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_ROOM_TAX ELSE 0 END) AS ENT_HOTEL_ROOM_TAX ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_OTHER_TAX ELSE 0 END) AS PROP_HOTEL_OTHER_TAX    ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_OTHER_TAX ELSE 0 END) AS MKT_HOTEL_OTHER_TAX    ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_OTHER_TAX ELSE 0 END) AS ENT_HOTEL_OTHER_TAX    ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_TIP_AMT ELSE 0 END) AS PROP_HOTEL_TIP_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_TIP_AMT ELSE 0 END) AS MKT_HOTEL_TIP_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_TIP_AMT ELSE 0 END) AS ENT_HOTEL_TIP_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_TKT_FOOD_BEVERAGE_AMT  ELSE 0 END) AS PROP_HOTEL_TKT_FOOD_BEVERAGE_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_TKT_FOOD_BEVERAGE_AMT  ELSE 0 END) AS MKT_HOTEL_TKT_FOOD_BEVERAGE_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_TKT_FOOD_BEVERAGE_AMT  ELSE 0 END) AS ENT_HOTEL_TKT_FOOD_BEVERAGE_AMT ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT ELSE 0 END) AS PROP_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT ELSE 0 END) AS MKT_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT ELSE 0 END) AS ENT_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_TKT_OTHER_AMT ELSE 0 END) AS PROP_HOTEL_TKT_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_TKT_OTHER_AMT ELSE 0 END) AS MKT_HOTEL_TKT_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_TKT_OTHER_AMT ELSE 0 END) AS ENT_HOTEL_TKT_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN HOTEL_COMP_TKT_OTHER_AMT ELSE 0 END) AS PROP_HOTEL_COMP_TKT_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN HOTEL_COMP_TKT_OTHER_AMT ELSE 0 END) AS MKT_HOTEL_COMP_TKT_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN HOTEL_COMP_TKT_OTHER_AMT ELSE 0 END) AS ENT_HOTEL_COMP_TKT_OTHER_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_HOTEL_COMP_ROOM_AMT  <> MKT_HOTEL_COMP_ROOM_AMT  OR MKT_HOTEL_COMP_ROOM_AMT  <> ENT_HOTEL_COMP_ROOM_AMT  OR ENT_HOTEL_COMP_ROOM_AMT  <> PROP_HOTEL_COMP_ROOM_AMT ) OR
( PROP_HOTEL_COMP_OTHER_AMT <> MKT_HOTEL_COMP_OTHER_AMT OR MKT_HOTEL_COMP_OTHER_AMT <> ENT_HOTEL_COMP_OTHER_AMT OR ENT_HOTEL_COMP_OTHER_AMT <> PROP_HOTEL_COMP_OTHER_AMT  ) OR
( PROP_HOTEL_COMP_AMT_TOTAL <> MKT_HOTEL_COMP_AMT_TOTAL OR MKT_HOTEL_COMP_AMT_TOTAL <> ENT_HOTEL_COMP_AMT_TOTAL OR ENT_HOTEL_COMP_AMT_TOTAL <> PROP_HOTEL_COMP_AMT_TOTAL  ) OR
( PROP_HOTEL_COMP_ROOM_TAX  <> MKT_HOTEL_COMP_ROOM_TAX  OR MKT_HOTEL_COMP_ROOM_TAX  <> ENT_HOTEL_COMP_ROOM_TAX  OR ENT_HOTEL_COMP_ROOM_TAX  <> PROP_HOTEL_COMP_ROOM_TAX ) OR
( PROP_HOTEL_COMP_OTHER_TAX <> MKT_HOTEL_COMP_OTHER_TAX OR MKT_HOTEL_COMP_OTHER_TAX <> ENT_HOTEL_COMP_OTHER_TAX OR ENT_HOTEL_COMP_OTHER_TAX <> PROP_HOTEL_COMP_OTHER_TAX  ) OR
( PROP_HOTEL_ROOM_AMT <> MKT_HOTEL_ROOM_AMT OR MKT_HOTEL_ROOM_AMT <> ENT_HOTEL_ROOM_AMT OR ENT_HOTEL_ROOM_AMT <> PROP_HOTEL_ROOM_AMT ) OR
( PROP_HOTEL_OTHER_AMT <> MKT_HOTEL_OTHER_AMT OR MKT_HOTEL_OTHER_AMT <> ENT_HOTEL_OTHER_AMT OR ENT_HOTEL_OTHER_AMT <> PROP_HOTEL_OTHER_AMT ) OR
( PROP_HOTEL_AMT_TOTAL <> MKT_HOTEL_AMT_TOTAL OR MKT_HOTEL_AMT_TOTAL <> ENT_HOTEL_AMT_TOTAL OR ENT_HOTEL_AMT_TOTAL <> PROP_HOTEL_AMT_TOTAL ) OR
( PROP_HOTEL_ROOM_TAX <> MKT_HOTEL_ROOM_TAX OR MKT_HOTEL_ROOM_TAX <> ENT_HOTEL_ROOM_TAX OR ENT_HOTEL_ROOM_TAX <> PROP_HOTEL_ROOM_TAX ) OR
( PROP_HOTEL_OTHER_TAX <> MKT_HOTEL_OTHER_TAX OR MKT_HOTEL_OTHER_TAX <> ENT_HOTEL_OTHER_TAX OR ENT_HOTEL_OTHER_TAX <> PROP_HOTEL_OTHER_TAX ) OR
( PROP_HOTEL_TIP_AMT  <> MKT_HOTEL_TIP_AMT  OR MKT_HOTEL_TIP_AMT  <> ENT_HOTEL_TIP_AMT  OR ENT_HOTEL_TIP_AMT  <> PROP_HOTEL_TIP_AMT ) OR
( PROP_HOTEL_TKT_FOOD_BEVERAGE_AMT <> MKT_HOTEL_TKT_FOOD_BEVERAGE_AMT OR MKT_HOTEL_TKT_FOOD_BEVERAGE_AMT <> ENT_HOTEL_TKT_FOOD_BEVERAGE_AMT OR ENT_HOTEL_TKT_FOOD_BEVERAGE_AMT <> PROP_HOTEL_TKT_FOOD_BEVERAGE_AMT  ) OR
( PROP_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT  <> MKT_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT  OR MKT_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT  <> ENT_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT  OR ENT_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT  <> PROP_HOTEL_COMP_TKT_FOOD_BEVERAGE_AMT ) OR
( PROP_HOTEL_TKT_OTHER_AMT  <> MKT_HOTEL_TKT_OTHER_AMT  OR MKT_HOTEL_TKT_OTHER_AMT  <> ENT_HOTEL_TKT_OTHER_AMT  OR ENT_HOTEL_TKT_OTHER_AMT  <> PROP_HOTEL_TKT_OTHER_AMT ) OR
( PROP_HOTEL_COMP_TKT_OTHER_AMT <> MKT_HOTEL_COMP_TKT_OTHER_AMT OR MKT_HOTEL_COMP_TKT_OTHER_AMT <> ENT_HOTEL_COMP_TKT_OTHER_AMT OR ENT_HOTEL_COMP_TKT_OTHER_AMT <> PROP_HOTEL_COMP_TKT_OTHER_AMT );



/* --------------------------------------------
                    POS     
--------------------------------------------*/


SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_SALES_GROSS_AMT ELSE 0 END) AS PROP_POS_SALES_GROSS_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_SALES_GROSS_AMT ELSE 0 END) AS MKT_POS_SALES_GROSS_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_SALES_GROSS_AMT ELSE 0 END) AS ENT_POS_SALES_GROSS_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_SALES_NET_AMT ELSE 0 END) AS PROP_POS_SALES_NET_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_SALES_NET_AMT ELSE 0 END) AS MKT_POS_SALES_NET_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_SALES_NET_AMT ELSE 0 END) AS ENT_POS_SALES_NET_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_DISCOUNT_AMT ELSE 0 END) AS PROP_POS_DISCOUNT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_DISCOUNT_AMT ELSE 0 END) AS MKT_POS_DISCOUNT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_DISCOUNT_AMT ELSE 0 END) AS ENT_POS_DISCOUNT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TAX_AMT ELSE 0 END) AS PROP_POS_TAX_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TAX_AMT ELSE 0 END) AS MKT_POS_TAX_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TAX_AMT ELSE 0 END) AS ENT_POS_TAX_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_GRATUITY_AMT ELSE 0 END) AS PROP_POS_GRATUITY_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_GRATUITY_AMT ELSE 0 END) AS MKT_POS_GRATUITY_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_GRATUITY_AMT ELSE 0 END) AS ENT_POS_GRATUITY_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TIP_AMT ELSE 0 END) AS PROP_POS_TIP_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TIP_AMT ELSE 0 END) AS MKT_POS_TIP_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TIP_AMT ELSE 0 END) AS ENT_POS_TIP_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_SERVICE_CHARGE_AMT ELSE 0 END) AS PROP_POS_SERVICE_CHARGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_SERVICE_CHARGE_AMT ELSE 0 END) AS MKT_POS_SERVICE_CHARGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_SERVICE_CHARGE_AMT ELSE 0 END) AS ENT_POS_SERVICE_CHARGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_NBR_SECONDS_OPEN ELSE 0 END) AS PROP_POS_NBR_SECONDS_OPEN,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_NBR_SECONDS_OPEN ELSE 0 END) AS MKT_POS_NBR_SECONDS_OPEN,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_NBR_SECONDS_OPEN ELSE 0 END) AS ENT_POS_NBR_SECONDS_OPEN,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TAXABLE_SALES_AMT ELSE 0 END) AS PROP_POS_TAXABLE_SALES_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TAXABLE_SALES_AMT ELSE 0 END) AS MKT_POS_TAXABLE_SALES_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TAXABLE_SALES_AMT ELSE 0 END) AS ENT_POS_TAXABLE_SALES_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_NONTAXABLE_SALES_AMT ELSE 0 END) AS PROP_POS_NONTAXABLE_SALES_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_NONTAXABLE_SALES_AMT ELSE 0 END) AS MKT_POS_NONTAXABLE_SALES_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_NONTAXABLE_SALES_AMT ELSE 0 END) AS ENT_POS_NONTAXABLE_SALES_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TOTAL_SERVICE_CHARGE_AMT ELSE 0 END) AS PROP_POS_TOTAL_SERVICE_CHARGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TOTAL_SERVICE_CHARGE_AMT ELSE 0 END) AS MKT_POS_TOTAL_SERVICE_CHARGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TOTAL_SERVICE_CHARGE_AMT ELSE 0 END) AS ENT_POS_TOTAL_SERVICE_CHARGE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_FOOD_AMT ELSE 0 END) AS PROP_POS_FOOD_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_FOOD_AMT ELSE 0 END) AS MKT_POS_FOOD_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_FOOD_AMT ELSE 0 END) AS ENT_POS_FOOD_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_LIQUOR_AMT ELSE 0 END) AS PROP_POS_LIQUOR_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_LIQUOR_AMT ELSE 0 END) AS MKT_POS_LIQUOR_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_LIQUOR_AMT ELSE 0 END) AS ENT_POS_LIQUOR_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_BEER_AMT ELSE 0 END) AS PROP_POS_BEER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_BEER_AMT ELSE 0 END) AS MKT_POS_BEER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_BEER_AMT ELSE 0 END) AS ENT_POS_BEER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_WINE_AMT ELSE 0 END) AS PROP_POS_WINE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_WINE_AMT ELSE 0 END) AS MKT_POS_WINE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_WINE_AMT ELSE 0 END) AS ENT_POS_WINE_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_RETAIL_AMT ELSE 0 END) AS PROP_POS_RETAIL_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_RETAIL_AMT ELSE 0 END) AS MKT_POS_RETAIL_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_RETAIL_AMT ELSE 0 END) AS ENT_POS_RETAIL_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_NA_BEV_AMT ELSE 0 END) AS PROP_POS_NA_BEV_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_NA_BEV_AMT ELSE 0 END) AS MKT_POS_NA_BEV_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_NA_BEV_AMT ELSE 0 END) AS ENT_POS_NA_BEV_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TOBACCO_AMT ELSE 0 END) AS PROP_POS_TOBACCO_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TOBACCO_AMT ELSE 0 END) AS MKT_POS_TOBACCO_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TOBACCO_AMT ELSE 0 END) AS ENT_POS_TOBACCO_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_OTHER_AMT ELSE 0 END) AS PROP_POS_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_OTHER_AMT ELSE 0 END) AS MKT_POS_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_OTHER_AMT ELSE 0 END) AS ENT_POS_OTHER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TOTAL_ITEM_AMT ELSE 0 END) AS PROP_POS_TOTAL_ITEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TOTAL_ITEM_AMT ELSE 0 END) AS MKT_POS_TOTAL_ITEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TOTAL_ITEM_AMT ELSE 0 END) AS ENT_POS_TOTAL_ITEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_NBR_LINE_ITEMS ELSE 0 END) AS PROP_POS_NBR_LINE_ITEMS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_NBR_LINE_ITEMS ELSE 0 END) AS MKT_POS_NBR_LINE_ITEMS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_NBR_LINE_ITEMS ELSE 0 END) AS ENT_POS_NBR_LINE_ITEMS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_LINE_ITEM_QTY ELSE 0 END) AS PROP_POS_LINE_ITEM_QTY,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_LINE_ITEM_QTY ELSE 0 END) AS MKT_POS_LINE_ITEM_QTY,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_LINE_ITEM_QTY ELSE 0 END) AS ENT_POS_LINE_ITEM_QTY,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_COMP_TENDER_AMT ELSE 0 END) AS PROP_POS_COMP_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_COMP_TENDER_AMT ELSE 0 END) AS MKT_POS_COMP_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_COMP_TENDER_AMT ELSE 0 END) AS ENT_POS_COMP_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_CASH_TENDER_AMT ELSE 0 END) AS PROP_POS_CASH_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_CASH_TENDER_AMT ELSE 0 END) AS MKT_POS_CASH_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_CASH_TENDER_AMT ELSE 0 END) AS ENT_POS_CASH_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_ROOM_TENDER_AMT ELSE 0 END) AS PROP_POS_ROOM_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_ROOM_TENDER_AMT ELSE 0 END) AS MKT_POS_ROOM_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_ROOM_TENDER_AMT ELSE 0 END) AS ENT_POS_ROOM_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_OTHER_TENDER_AMT ELSE 0 END) AS PROP_POS_OTHER_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_OTHER_TENDER_AMT ELSE 0 END) AS MKT_POS_OTHER_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_OTHER_TENDER_AMT ELSE 0 END) AS ENT_POS_OTHER_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POS_TOTAL_TENDER_AMT ELSE 0 END) AS PROP_POS_TOTAL_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POS_TOTAL_TENDER_AMT ELSE 0 END) AS MKT_POS_TOTAL_TENDER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POS_TOTAL_TENDER_AMT ELSE 0 END) AS ENT_POS_TOTAL_TENDER_AMT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_POS_SALES_GROSS_AMT  <> MKT_POS_SALES_GROSS_AMT  OR MKT_POS_SALES_GROSS_AMT  <> ENT_POS_SALES_GROSS_AMT  OR ENT_POS_SALES_GROSS_AMT  <> PROP_POS_SALES_GROSS_AMT ) OR
( PROP_POS_SALES_NET_AMT  <> MKT_POS_SALES_NET_AMT  OR MKT_POS_SALES_NET_AMT  <> ENT_POS_SALES_NET_AMT  OR ENT_POS_SALES_NET_AMT  <> PROP_POS_SALES_NET_AMT ) OR
( PROP_POS_DISCOUNT_AMT  <> MKT_POS_DISCOUNT_AMT  OR MKT_POS_DISCOUNT_AMT  <> ENT_POS_DISCOUNT_AMT  OR ENT_POS_DISCOUNT_AMT  <> PROP_POS_DISCOUNT_AMT ) OR
( PROP_POS_TAX_AMT  <> MKT_POS_TAX_AMT  OR MKT_POS_TAX_AMT  <> ENT_POS_TAX_AMT  OR ENT_POS_TAX_AMT  <> PROP_POS_TAX_AMT ) OR
( PROP_POS_GRATUITY_AMT  <> MKT_POS_GRATUITY_AMT  OR MKT_POS_GRATUITY_AMT  <> ENT_POS_GRATUITY_AMT  OR ENT_POS_GRATUITY_AMT  <> PROP_POS_GRATUITY_AMT ) OR
( PROP_POS_TIP_AMT  <> MKT_POS_TIP_AMT  OR MKT_POS_TIP_AMT  <> ENT_POS_TIP_AMT  OR ENT_POS_TIP_AMT  <> PROP_POS_TIP_AMT ) OR
( PROP_POS_SERVICE_CHARGE_AMT  <> MKT_POS_SERVICE_CHARGE_AMT  OR MKT_POS_SERVICE_CHARGE_AMT  <> ENT_POS_SERVICE_CHARGE_AMT  OR ENT_POS_SERVICE_CHARGE_AMT  <> PROP_POS_SERVICE_CHARGE_AMT ) OR
( PROP_POS_NBR_SECONDS_OPEN  <> MKT_POS_NBR_SECONDS_OPEN  OR MKT_POS_NBR_SECONDS_OPEN  <> ENT_POS_NBR_SECONDS_OPEN  OR ENT_POS_NBR_SECONDS_OPEN  <> PROP_POS_NBR_SECONDS_OPEN ) OR
( PROP_POS_TAXABLE_SALES_AMT  <> MKT_POS_TAXABLE_SALES_AMT  OR MKT_POS_TAXABLE_SALES_AMT  <> ENT_POS_TAXABLE_SALES_AMT  OR ENT_POS_TAXABLE_SALES_AMT  <> PROP_POS_TAXABLE_SALES_AMT ) OR
( PROP_POS_NONTAXABLE_SALES_AMT  <> MKT_POS_NONTAXABLE_SALES_AMT  OR MKT_POS_NONTAXABLE_SALES_AMT  <> ENT_POS_NONTAXABLE_SALES_AMT  OR ENT_POS_NONTAXABLE_SALES_AMT  <> PROP_POS_NONTAXABLE_SALES_AMT ) OR
( PROP_POS_TOTAL_SERVICE_CHARGE_AMT  <> MKT_POS_TOTAL_SERVICE_CHARGE_AMT  OR MKT_POS_TOTAL_SERVICE_CHARGE_AMT  <> ENT_POS_TOTAL_SERVICE_CHARGE_AMT  OR ENT_POS_TOTAL_SERVICE_CHARGE_AMT  <> PROP_POS_TOTAL_SERVICE_CHARGE_AMT ) OR
( PROP_POS_FOOD_AMT  <> MKT_POS_FOOD_AMT  OR MKT_POS_FOOD_AMT  <> ENT_POS_FOOD_AMT  OR ENT_POS_FOOD_AMT  <> PROP_POS_FOOD_AMT ) OR
( PROP_POS_LIQUOR_AMT  <> MKT_POS_LIQUOR_AMT  OR MKT_POS_LIQUOR_AMT  <> ENT_POS_LIQUOR_AMT  OR ENT_POS_LIQUOR_AMT  <> PROP_POS_LIQUOR_AMT ) OR
( PROP_POS_BEER_AMT  <> MKT_POS_BEER_AMT  OR MKT_POS_BEER_AMT  <> ENT_POS_BEER_AMT  OR ENT_POS_BEER_AMT  <> PROP_POS_BEER_AMT ) OR
( PROP_POS_WINE_AMT  <> MKT_POS_WINE_AMT  OR MKT_POS_WINE_AMT  <> ENT_POS_WINE_AMT  OR ENT_POS_WINE_AMT  <> PROP_POS_WINE_AMT ) OR
( PROP_POS_RETAIL_AMT  <> MKT_POS_RETAIL_AMT  OR MKT_POS_RETAIL_AMT  <> ENT_POS_RETAIL_AMT  OR ENT_POS_RETAIL_AMT  <> PROP_POS_RETAIL_AMT ) OR
( PROP_POS_NA_BEV_AMT  <> MKT_POS_NA_BEV_AMT  OR MKT_POS_NA_BEV_AMT  <> ENT_POS_NA_BEV_AMT  OR ENT_POS_NA_BEV_AMT  <> PROP_POS_NA_BEV_AMT ) OR
( PROP_POS_TOBACCO_AMT  <> MKT_POS_TOBACCO_AMT  OR MKT_POS_TOBACCO_AMT  <> ENT_POS_TOBACCO_AMT  OR ENT_POS_TOBACCO_AMT  <> PROP_POS_TOBACCO_AMT ) OR
( PROP_POS_OTHER_AMT  <> MKT_POS_OTHER_AMT  OR MKT_POS_OTHER_AMT  <> ENT_POS_OTHER_AMT  OR ENT_POS_OTHER_AMT  <> PROP_POS_OTHER_AMT ) OR
( PROP_POS_TOTAL_ITEM_AMT  <> MKT_POS_TOTAL_ITEM_AMT  OR MKT_POS_TOTAL_ITEM_AMT  <> ENT_POS_TOTAL_ITEM_AMT  OR ENT_POS_TOTAL_ITEM_AMT  <> PROP_POS_TOTAL_ITEM_AMT ) OR
( PROP_POS_NBR_LINE_ITEMS  <> MKT_POS_NBR_LINE_ITEMS  OR MKT_POS_NBR_LINE_ITEMS  <> ENT_POS_NBR_LINE_ITEMS  OR ENT_POS_NBR_LINE_ITEMS  <> PROP_POS_NBR_LINE_ITEMS ) OR
( PROP_POS_LINE_ITEM_QTY  <> MKT_POS_LINE_ITEM_QTY  OR MKT_POS_LINE_ITEM_QTY  <> ENT_POS_LINE_ITEM_QTY  OR ENT_POS_LINE_ITEM_QTY  <> PROP_POS_LINE_ITEM_QTY ) OR
( PROP_POS_COMP_TENDER_AMT  <> MKT_POS_COMP_TENDER_AMT  OR MKT_POS_COMP_TENDER_AMT  <> ENT_POS_COMP_TENDER_AMT  OR ENT_POS_COMP_TENDER_AMT  <> PROP_POS_COMP_TENDER_AMT ) OR
( PROP_POS_CASH_TENDER_AMT  <> MKT_POS_CASH_TENDER_AMT  OR MKT_POS_CASH_TENDER_AMT  <> ENT_POS_CASH_TENDER_AMT  OR ENT_POS_CASH_TENDER_AMT  <> PROP_POS_CASH_TENDER_AMT ) OR
( PROP_POS_ROOM_TENDER_AMT  <> MKT_POS_ROOM_TENDER_AMT  OR MKT_POS_ROOM_TENDER_AMT  <> ENT_POS_ROOM_TENDER_AMT  OR ENT_POS_ROOM_TENDER_AMT  <> PROP_POS_ROOM_TENDER_AMT ) OR
( PROP_POS_OTHER_TENDER_AMT  <> MKT_POS_OTHER_TENDER_AMT  OR MKT_POS_OTHER_TENDER_AMT  <> ENT_POS_OTHER_TENDER_AMT  OR ENT_POS_OTHER_TENDER_AMT  <> PROP_POS_OTHER_TENDER_AMT ) OR
( PROP_POS_TOTAL_TENDER_AMT  <> MKT_POS_TOTAL_TENDER_AMT  OR MKT_POS_TOTAL_TENDER_AMT  <> ENT_POS_TOTAL_TENDER_AMT  OR ENT_POS_TOTAL_TENDER_AMT  <> PROP_POS_TOTAL_TENDER_AMT );







/* --------------------------------------------
                    Offer    
--------------------------------------------*/



SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_CASH_COST ELSE 0 END) AS PROP_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_CASH_COST ELSE 0 END) AS MKT_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_CASH_COST ELSE 0 END) AS ENT_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_HOTEL_COST ELSE 0 END) AS PROP_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_HOTEL_COST ELSE 0 END) AS MKT_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_HOTEL_COST ELSE 0 END) AS ENT_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_RC_COST ELSE 0 END) AS PROP_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_RC_COST ELSE 0 END) AS MKT_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_RC_COST ELSE 0 END) AS ENT_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_OTHER_COST ELSE 0 END) AS PROP_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_OTHER_COST ELSE 0 END) AS MKT_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_OTHER_COST ELSE 0 END) AS ENT_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_FSP_COST ELSE 0 END) AS PROP_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_FSP_COST ELSE 0 END) AS MKT_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_FSP_COST ELSE 0 END) AS ENT_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_TOTAL_COST ELSE 0 END) AS PROP_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_TOTAL_COST ELSE 0 END) AS MKT_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_TOTAL_COST ELSE 0 END) AS ENT_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS PROP_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS MKT_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS ENT_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS PROP_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS MKT_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS ENT_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS PROP_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS MKT_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS ENT_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS PROP_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS MKT_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS ENT_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_COST
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_OFFER_CASH_COST  <> MKT_OFFER_CASH_COST  OR MKT_OFFER_CASH_COST  <> ENT_OFFER_CASH_COST  OR ENT_OFFER_CASH_COST  <> PROP_OFFER_CASH_COST ) OR
( PROP_OFFER_HOTEL_COST  <> MKT_OFFER_HOTEL_COST  OR MKT_OFFER_HOTEL_COST  <> ENT_OFFER_HOTEL_COST  OR ENT_OFFER_HOTEL_COST  <> PROP_OFFER_HOTEL_COST ) OR
( PROP_OFFER_RC_COST  <> MKT_OFFER_RC_COST  OR MKT_OFFER_RC_COST  <> ENT_OFFER_RC_COST  OR ENT_OFFER_RC_COST  <> PROP_OFFER_RC_COST ) OR
( PROP_OFFER_OTHER_COST  <> MKT_OFFER_OTHER_COST  OR MKT_OFFER_OTHER_COST  <> ENT_OFFER_OTHER_COST  OR ENT_OFFER_OTHER_COST  <> PROP_OFFER_OTHER_COST ) OR
( PROP_OFFER_FSP_COST  <> MKT_OFFER_FSP_COST  OR MKT_OFFER_FSP_COST  <> ENT_OFFER_FSP_COST  OR ENT_OFFER_FSP_COST  <> PROP_OFFER_FSP_COST ) OR
( PROP_OFFER_TOTAL_COST  <> MKT_OFFER_TOTAL_COST  OR MKT_OFFER_TOTAL_COST  <> ENT_OFFER_TOTAL_COST  OR ENT_OFFER_TOTAL_COST  <> PROP_OFFER_TOTAL_COST ) OR
( PROP_OFFER_NBR_CASH_COUPONS  <> MKT_OFFER_NBR_CASH_COUPONS  OR MKT_OFFER_NBR_CASH_COUPONS  <> ENT_OFFER_NBR_CASH_COUPONS  OR ENT_OFFER_NBR_CASH_COUPONS  <> PROP_OFFER_NBR_CASH_COUPONS ) OR
( PROP_OFFER_NBR_HOTEL_COUPONS  <> MKT_OFFER_NBR_HOTEL_COUPONS  OR MKT_OFFER_NBR_HOTEL_COUPONS  <> ENT_OFFER_NBR_HOTEL_COUPONS  OR ENT_OFFER_NBR_HOTEL_COUPONS  <> PROP_OFFER_NBR_HOTEL_COUPONS ) OR
( PROP_OFFER_NBR_RC_COUPONS  <> MKT_OFFER_NBR_RC_COUPONS  OR MKT_OFFER_NBR_RC_COUPONS  <> ENT_OFFER_NBR_RC_COUPONS  OR ENT_OFFER_NBR_RC_COUPONS  <> PROP_OFFER_NBR_RC_COUPONS ) OR
( PROP_OFFER_NBR_OTHER_COUPONS  <> MKT_OFFER_NBR_OTHER_COUPONS  OR MKT_OFFER_NBR_OTHER_COUPONS  <> ENT_OFFER_NBR_OTHER_COUPONS  OR ENT_OFFER_NBR_OTHER_COUPONS  <> PROP_OFFER_NBR_OTHER_COUPONS ) OR
( PROP_OFFER_NBR_FSP_COUPONS  <> MKT_OFFER_NBR_FSP_COUPONS  OR MKT_OFFER_NBR_FSP_COUPONS  <> ENT_OFFER_NBR_FSP_COUPONS  OR ENT_OFFER_NBR_FSP_COUPONS  <> PROP_OFFER_NBR_FSP_COUPONS ) OR
( PROP_OFFER_NBR_TOTAL_COUPONS  <> MKT_OFFER_NBR_TOTAL_COUPONS  OR MKT_OFFER_NBR_TOTAL_COUPONS  <> ENT_OFFER_NBR_TOTAL_COUPONS  OR ENT_OFFER_NBR_TOTAL_COUPONS  <> PROP_OFFER_NBR_TOTAL_COUPONS ) OR
( PROP_OFFER_DM_REEL_REWARDS_COST  <> MKT_OFFER_DM_REEL_REWARDS_COST  OR MKT_OFFER_DM_REEL_REWARDS_COST  <> ENT_OFFER_DM_REEL_REWARDS_COST  OR ENT_OFFER_DM_REEL_REWARDS_COST  <> PROP_OFFER_DM_REEL_REWARDS_COST ) OR
( PROP_OFFER_EMAIL_REEL_REWARDS_COST  <> MKT_OFFER_EMAIL_REEL_REWARDS_COST  OR MKT_OFFER_EMAIL_REEL_REWARDS_COST  <> ENT_OFFER_EMAIL_REEL_REWARDS_COST  OR ENT_OFFER_EMAIL_REEL_REWARDS_COST  <> PROP_OFFER_EMAIL_REEL_REWARDS_COST ) OR
( PROP_OFFER_NBR_DM_REEL_REWARDS  <> MKT_OFFER_NBR_DM_REEL_REWARDS  OR MKT_OFFER_NBR_DM_REEL_REWARDS  <> ENT_OFFER_NBR_DM_REEL_REWARDS  OR ENT_OFFER_NBR_DM_REEL_REWARDS  <> PROP_OFFER_NBR_DM_REEL_REWARDS ) OR
( PROP_OFFER_NBR_EMAIL_REEL_REWARDS  <> MKT_OFFER_NBR_EMAIL_REEL_REWARDS  OR MKT_OFFER_NBR_EMAIL_REEL_REWARDS  <> ENT_OFFER_NBR_EMAIL_REEL_REWARDS  OR ENT_OFFER_NBR_EMAIL_REEL_REWARDS  <> PROP_OFFER_NBR_EMAIL_REEL_REWARDS ) OR
( PROP_OFFER_CASH_REDEEM_AMT  <> MKT_OFFER_CASH_REDEEM_AMT  OR MKT_OFFER_CASH_REDEEM_AMT  <> ENT_OFFER_CASH_REDEEM_AMT  OR ENT_OFFER_CASH_REDEEM_AMT  <> PROP_OFFER_CASH_REDEEM_AMT ) OR
( PROP_OFFER_HOTEL_REDEEM_AMT  <> MKT_OFFER_HOTEL_REDEEM_AMT  OR MKT_OFFER_HOTEL_REDEEM_AMT  <> ENT_OFFER_HOTEL_REDEEM_AMT  OR ENT_OFFER_HOTEL_REDEEM_AMT  <> PROP_OFFER_HOTEL_REDEEM_AMT ) OR
( PROP_OFFER_RC_REDEEM_AMT  <> MKT_OFFER_RC_REDEEM_AMT  OR MKT_OFFER_RC_REDEEM_AMT  <> ENT_OFFER_RC_REDEEM_AMT  OR ENT_OFFER_RC_REDEEM_AMT  <> PROP_OFFER_RC_REDEEM_AMT ) OR
( PROP_OFFER_OTHER_REDEEM_AMT  <> MKT_OFFER_OTHER_REDEEM_AMT  OR MKT_OFFER_OTHER_REDEEM_AMT  <> ENT_OFFER_OTHER_REDEEM_AMT  OR ENT_OFFER_OTHER_REDEEM_AMT  <> PROP_OFFER_OTHER_REDEEM_AMT ) OR
( PROP_OFFER_FSP_REDEEM_AMT  <> MKT_OFFER_FSP_REDEEM_AMT  OR MKT_OFFER_FSP_REDEEM_AMT  <> ENT_OFFER_FSP_REDEEM_AMT  OR ENT_OFFER_FSP_REDEEM_AMT  <> PROP_OFFER_FSP_REDEEM_AMT ) OR
( PROP_OFFER_TOTAL_REDEEM_AMT  <> MKT_OFFER_TOTAL_REDEEM_AMT  OR MKT_OFFER_TOTAL_REDEEM_AMT  <> ENT_OFFER_TOTAL_REDEEM_AMT  OR ENT_OFFER_TOTAL_REDEEM_AMT  <> PROP_OFFER_TOTAL_REDEEM_AMT ) OR
( PROP_OFFER_DRAWING_OTP_NBR_ENTRIES  <> MKT_OFFER_DRAWING_OTP_NBR_ENTRIES  OR MKT_OFFER_DRAWING_OTP_NBR_ENTRIES  <> ENT_OFFER_DRAWING_OTP_NBR_ENTRIES  OR ENT_OFFER_DRAWING_OTP_NBR_ENTRIES  <> PROP_OFFER_DRAWING_OTP_NBR_ENTRIES ) OR
( PROP_OFFER_DRAWING_OTP_REDEEMED_AMT  <> MKT_OFFER_DRAWING_OTP_REDEEMED_AMT  OR MKT_OFFER_DRAWING_OTP_REDEEMED_AMT  <> ENT_OFFER_DRAWING_OTP_REDEEMED_AMT  OR ENT_OFFER_DRAWING_OTP_REDEEMED_AMT  <> PROP_OFFER_DRAWING_OTP_REDEEMED_AMT ) OR
( PROP_OFFER_DRAWING_OTP_COST  <> MKT_OFFER_DRAWING_OTP_COST  OR MKT_OFFER_DRAWING_OTP_COST  <> ENT_OFFER_DRAWING_OTP_COST  OR ENT_OFFER_DRAWING_OTP_COST  <> PROP_OFFER_DRAWING_OTP_COST );




/* --------------------------------------------
                    Comp     
--------------------------------------------*/


SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CW_DLRS_USED ELSE 0 END) AS PROP_CW_DLRS_USED,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CW_DLRS_USED ELSE 0 END) AS MKT_CW_DLRS_USED,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CW_DLRS_USED ELSE 0 END) AS ENT_CW_DLRS_USED,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CW_DLRS_USED_FOOD ELSE 0 END) AS PROP_CW_DLRS_USED_FOOD,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CW_DLRS_USED_FOOD ELSE 0 END) AS MKT_CW_DLRS_USED_FOOD,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CW_DLRS_USED_FOOD ELSE 0 END) AS ENT_CW_DLRS_USED_FOOD,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CW_DLRS_USED_ROOM ELSE 0 END) AS PROP_CW_DLRS_USED_ROOM,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CW_DLRS_USED_ROOM ELSE 0 END) AS MKT_CW_DLRS_USED_ROOM,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CW_DLRS_USED_ROOM ELSE 0 END) AS ENT_CW_DLRS_USED_ROOM,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CW_DLRS_USED_OTHER ELSE 0 END) AS PROP_CW_DLRS_USED_OTHER,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CW_DLRS_USED_OTHER ELSE 0 END) AS MKT_CW_DLRS_USED_OTHER,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CW_DLRS_USED_OTHER ELSE 0 END) AS ENT_CW_DLRS_USED_OTHER,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN RC_DLRS_USED ELSE 0 END) AS PROP_RC_DLRS_USED,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN RC_DLRS_USED ELSE 0 END) AS MKT_RC_DLRS_USED,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN RC_DLRS_USED ELSE 0 END) AS ENT_RC_DLRS_USED,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN RC_DLRS_USED_FOOD ELSE 0 END) AS PROP_RC_DLRS_USED_FOOD,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN RC_DLRS_USED_FOOD ELSE 0 END) AS MKT_RC_DLRS_USED_FOOD,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN RC_DLRS_USED_FOOD ELSE 0 END) AS ENT_RC_DLRS_USED_FOOD,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN RC_DLRS_USED_ROOM ELSE 0 END) AS PROP_RC_DLRS_USED_ROOM,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN RC_DLRS_USED_ROOM ELSE 0 END) AS MKT_RC_DLRS_USED_ROOM,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN RC_DLRS_USED_ROOM ELSE 0 END) AS ENT_RC_DLRS_USED_ROOM,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN RC_DLRS_USED_OTHER ELSE 0 END) AS PROP_RC_DLRS_USED_OTHER,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN RC_DLRS_USED_OTHER ELSE 0 END) AS MKT_RC_DLRS_USED_OTHER,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN RC_DLRS_USED_OTHER ELSE 0 END) AS ENT_RC_DLRS_USED_OTHER,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN RC_FP_CONVERT ELSE 0 END) AS PROP_RC_FP_CONVERT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN RC_FP_CONVERT ELSE 0 END) AS MKT_RC_FP_CONVERT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN RC_FP_CONVERT ELSE 0 END) AS ENT_RC_FP_CONVERT
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_CW_DLRS_USED  <> MKT_CW_DLRS_USED  OR MKT_CW_DLRS_USED  <> ENT_CW_DLRS_USED  OR ENT_CW_DLRS_USED  <> PROP_CW_DLRS_USED ) OR
( PROP_CW_DLRS_USED_FOOD  <> MKT_CW_DLRS_USED_FOOD  OR MKT_CW_DLRS_USED_FOOD  <> ENT_CW_DLRS_USED_FOOD  OR ENT_CW_DLRS_USED_FOOD  <> PROP_CW_DLRS_USED_FOOD ) OR
( PROP_CW_DLRS_USED_ROOM  <> MKT_CW_DLRS_USED_ROOM  OR MKT_CW_DLRS_USED_ROOM  <> ENT_CW_DLRS_USED_ROOM  OR ENT_CW_DLRS_USED_ROOM  <> PROP_CW_DLRS_USED_ROOM ) OR
( PROP_CW_DLRS_USED_OTHER  <> MKT_CW_DLRS_USED_OTHER  OR MKT_CW_DLRS_USED_OTHER  <> ENT_CW_DLRS_USED_OTHER  OR ENT_CW_DLRS_USED_OTHER  <> PROP_CW_DLRS_USED_OTHER ) OR
( PROP_RC_DLRS_USED  <> MKT_RC_DLRS_USED  OR MKT_RC_DLRS_USED  <> ENT_RC_DLRS_USED  OR ENT_RC_DLRS_USED  <> PROP_RC_DLRS_USED ) OR
( PROP_RC_DLRS_USED_FOOD  <> MKT_RC_DLRS_USED_FOOD  OR MKT_RC_DLRS_USED_FOOD  <> ENT_RC_DLRS_USED_FOOD  OR ENT_RC_DLRS_USED_FOOD  <> PROP_RC_DLRS_USED_FOOD ) OR
( PROP_RC_DLRS_USED_ROOM  <> MKT_RC_DLRS_USED_ROOM  OR MKT_RC_DLRS_USED_ROOM  <> ENT_RC_DLRS_USED_ROOM  OR ENT_RC_DLRS_USED_ROOM  <> PROP_RC_DLRS_USED_ROOM ) OR
( PROP_RC_DLRS_USED_OTHER  <> MKT_RC_DLRS_USED_OTHER  OR MKT_RC_DLRS_USED_OTHER  <> ENT_RC_DLRS_USED_OTHER  OR ENT_RC_DLRS_USED_OTHER  <> PROP_RC_DLRS_USED_OTHER ) OR
( PROP_RC_FP_CONVERT  <> MKT_RC_FP_CONVERT  OR MKT_RC_FP_CONVERT  <> ENT_RC_FP_CONVERT  OR ENT_RC_FP_CONVERT  <> PROP_RC_FP_CONVERT );




/* --------------------------------------------
                    Markers    
--------------------------------------------*/


SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_MARKER_AMT ELSE 0 END) AS PROP_TABLE_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_MARKER_AMT ELSE 0 END) AS MKT_TABLE_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_MARKER_AMT ELSE 0 END) AS ENT_TABLE_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_MARKER_AMT ELSE 0 END) AS PROP_SLOT_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_MARKER_AMT ELSE 0 END) AS MKT_SLOT_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_MARKER_AMT ELSE 0 END) AS ENT_SLOT_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_MARKER_AMT ELSE 0 END) AS PROP_OTHER_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_MARKER_AMT ELSE 0 END) AS MKT_OTHER_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_MARKER_AMT ELSE 0 END) AS ENT_OTHER_MARKER_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_SFK_DEPOSIT_AMT ELSE 0 END) AS PROP_TABLE_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_SFK_DEPOSIT_AMT ELSE 0 END) AS MKT_TABLE_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_SFK_DEPOSIT_AMT ELSE 0 END) AS ENT_TABLE_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_SFK_DEPOSIT_AMT ELSE 0 END) AS PROP_SLOT_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_SFK_DEPOSIT_AMT ELSE 0 END) AS MKT_SLOT_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_SFK_DEPOSIT_AMT ELSE 0 END) AS ENT_SLOT_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_SFK_DEPOSIT_AMT ELSE 0 END) AS PROP_OTHER_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_SFK_DEPOSIT_AMT ELSE 0 END) AS MKT_OTHER_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_SFK_DEPOSIT_AMT ELSE 0 END) AS ENT_OTHER_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TOTAL_SFKCCK_AMT ELSE 0 END) AS PROP_TOTAL_SFKCCK_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TOTAL_SFKCCK_AMT ELSE 0 END) AS MKT_TOTAL_SFKCCK_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TOTAL_SFKCCK_AMT ELSE 0 END) AS ENT_TOTAL_SFKCCK_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TOTAL_SFK_DEPOSIT_AMT ELSE 0 END) AS PROP_TOTAL_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TOTAL_SFK_DEPOSIT_AMT ELSE 0 END) AS MKT_TOTAL_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TOTAL_SFK_DEPOSIT_AMT ELSE 0 END) AS ENT_TOTAL_SFK_DEPOSIT_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_NBR_MARKER_TRX ELSE 0 END) AS PROP_TABLE_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_NBR_MARKER_TRX ELSE 0 END) AS MKT_TABLE_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_NBR_MARKER_TRX ELSE 0 END) AS ENT_TABLE_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_NBR_MARKER_TRX ELSE 0 END) AS PROP_SLOT_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_NBR_MARKER_TRX ELSE 0 END) AS MKT_SLOT_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_NBR_MARKER_TRX ELSE 0 END) AS ENT_SLOT_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_NBR_MARKER_TRX ELSE 0 END) AS PROP_OTHER_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_NBR_MARKER_TRX ELSE 0 END) AS MKT_OTHER_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_NBR_MARKER_TRX ELSE 0 END) AS ENT_OTHER_NBR_MARKER_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TABLE_NBR_SFK_TRX ELSE 0 END) AS PROP_TABLE_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TABLE_NBR_SFK_TRX ELSE 0 END) AS MKT_TABLE_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TABLE_NBR_SFK_TRX ELSE 0 END) AS ENT_TABLE_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SLOT_NBR_SFK_TRX ELSE 0 END) AS PROP_SLOT_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SLOT_NBR_SFK_TRX ELSE 0 END) AS MKT_SLOT_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SLOT_NBR_SFK_TRX ELSE 0 END) AS ENT_SLOT_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OTHER_NBR_SFK_TRX ELSE 0 END) AS PROP_OTHER_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OTHER_NBR_SFK_TRX ELSE 0 END) AS MKT_OTHER_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OTHER_NBR_SFK_TRX ELSE 0 END) AS ENT_OTHER_NBR_SFK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TOTAL_NBR_SFKCCK_TRX ELSE 0 END) AS PROP_TOTAL_NBR_SFKCCK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TOTAL_NBR_SFKCCK_TRX ELSE 0 END) AS MKT_TOTAL_NBR_SFKCCK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TOTAL_NBR_SFKCCK_TRX ELSE 0 END) AS ENT_TOTAL_NBR_SFKCCK_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TOTAL_NBR_SFK_DEPOSIT_TRX ELSE 0 END) AS PROP_TOTAL_NBR_SFK_DEPOSIT_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN TOTAL_NBR_SFK_DEPOSIT_TRX ELSE 0 END) AS MKT_TOTAL_NBR_SFK_DEPOSIT_TRX,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TOTAL_NBR_SFK_DEPOSIT_TRX ELSE 0 END) AS ENT_TOTAL_NBR_SFK_DEPOSIT_TRX
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_TABLE_MARKER_AMT  <> MKT_TABLE_MARKER_AMT  OR MKT_TABLE_MARKER_AMT  <> ENT_TABLE_MARKER_AMT  OR ENT_TABLE_MARKER_AMT  <> PROP_TABLE_MARKER_AMT ) OR
( PROP_SLOT_MARKER_AMT  <> MKT_SLOT_MARKER_AMT  OR MKT_SLOT_MARKER_AMT  <> ENT_SLOT_MARKER_AMT  OR ENT_SLOT_MARKER_AMT  <> PROP_SLOT_MARKER_AMT ) OR
( PROP_OTHER_MARKER_AMT  <> MKT_OTHER_MARKER_AMT  OR MKT_OTHER_MARKER_AMT  <> ENT_OTHER_MARKER_AMT  OR ENT_OTHER_MARKER_AMT  <> PROP_OTHER_MARKER_AMT ) OR
( PROP_TABLE_SFK_DEPOSIT_AMT  <> MKT_TABLE_SFK_DEPOSIT_AMT  OR MKT_TABLE_SFK_DEPOSIT_AMT  <> ENT_TABLE_SFK_DEPOSIT_AMT  OR ENT_TABLE_SFK_DEPOSIT_AMT  <> PROP_TABLE_SFK_DEPOSIT_AMT ) OR
( PROP_SLOT_SFK_DEPOSIT_AMT  <> MKT_SLOT_SFK_DEPOSIT_AMT  OR MKT_SLOT_SFK_DEPOSIT_AMT  <> ENT_SLOT_SFK_DEPOSIT_AMT  OR ENT_SLOT_SFK_DEPOSIT_AMT  <> PROP_SLOT_SFK_DEPOSIT_AMT ) OR
( PROP_OTHER_SFK_DEPOSIT_AMT  <> MKT_OTHER_SFK_DEPOSIT_AMT  OR MKT_OTHER_SFK_DEPOSIT_AMT  <> ENT_OTHER_SFK_DEPOSIT_AMT  OR ENT_OTHER_SFK_DEPOSIT_AMT  <> PROP_OTHER_SFK_DEPOSIT_AMT ) OR
( PROP_TOTAL_SFKCCK_AMT  <> MKT_TOTAL_SFKCCK_AMT  OR MKT_TOTAL_SFKCCK_AMT  <> ENT_TOTAL_SFKCCK_AMT  OR ENT_TOTAL_SFKCCK_AMT  <> PROP_TOTAL_SFKCCK_AMT ) OR
( PROP_TOTAL_SFK_DEPOSIT_AMT  <> MKT_TOTAL_SFK_DEPOSIT_AMT  OR MKT_TOTAL_SFK_DEPOSIT_AMT  <> ENT_TOTAL_SFK_DEPOSIT_AMT  OR ENT_TOTAL_SFK_DEPOSIT_AMT  <> PROP_TOTAL_SFK_DEPOSIT_AMT ) OR
( PROP_TABLE_NBR_MARKER_TRX  <> MKT_TABLE_NBR_MARKER_TRX  OR MKT_TABLE_NBR_MARKER_TRX  <> ENT_TABLE_NBR_MARKER_TRX  OR ENT_TABLE_NBR_MARKER_TRX  <> PROP_TABLE_NBR_MARKER_TRX ) OR
( PROP_SLOT_NBR_MARKER_TRX  <> MKT_SLOT_NBR_MARKER_TRX  OR MKT_SLOT_NBR_MARKER_TRX  <> ENT_SLOT_NBR_MARKER_TRX  OR ENT_SLOT_NBR_MARKER_TRX  <> PROP_SLOT_NBR_MARKER_TRX ) OR
( PROP_OTHER_NBR_MARKER_TRX  <> MKT_OTHER_NBR_MARKER_TRX  OR MKT_OTHER_NBR_MARKER_TRX  <> ENT_OTHER_NBR_MARKER_TRX  OR ENT_OTHER_NBR_MARKER_TRX  <> PROP_OTHER_NBR_MARKER_TRX ) OR
( PROP_TABLE_NBR_SFK_TRX  <> MKT_TABLE_NBR_SFK_TRX  OR MKT_TABLE_NBR_SFK_TRX  <> ENT_TABLE_NBR_SFK_TRX  OR ENT_TABLE_NBR_SFK_TRX  <> PROP_TABLE_NBR_SFK_TRX ) OR
( PROP_SLOT_NBR_SFK_TRX  <> MKT_SLOT_NBR_SFK_TRX  OR MKT_SLOT_NBR_SFK_TRX  <> ENT_SLOT_NBR_SFK_TRX  OR ENT_SLOT_NBR_SFK_TRX  <> PROP_SLOT_NBR_SFK_TRX ) OR
( PROP_OTHER_NBR_SFK_TRX  <> MKT_OTHER_NBR_SFK_TRX  OR MKT_OTHER_NBR_SFK_TRX  <> ENT_OTHER_NBR_SFK_TRX  OR ENT_OTHER_NBR_SFK_TRX  <> PROP_OTHER_NBR_SFK_TRX ) OR
( PROP_TOTAL_NBR_SFKCCK_TRX  <> MKT_TOTAL_NBR_SFKCCK_TRX  OR MKT_TOTAL_NBR_SFKCCK_TRX  <> ENT_TOTAL_NBR_SFKCCK_TRX  OR ENT_TOTAL_NBR_SFKCCK_TRX  <> PROP_TOTAL_NBR_SFKCCK_TRX ) OR
( PROP_TOTAL_NBR_SFK_DEPOSIT_TRX  <> MKT_TOTAL_NBR_SFK_DEPOSIT_TRX  OR MKT_TOTAL_NBR_SFK_DEPOSIT_TRX  <> ENT_TOTAL_NBR_SFK_DEPOSIT_TRX  OR ENT_TOTAL_NBR_SFK_DEPOSIT_TRX  <> PROP_TOTAL_NBR_SFK_DEPOSIT_TRX );





/* --------------------------------------------
                    Freeplay    
--------------------------------------------*/

WITH ABS_LOGIC AS
(
	SELECT
		TD.TRIP_MASTER_ID,
		COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
		CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
	FROM
		DAAS_CORE.TRIP_DETAIL TD
	JOIN 
		DAAS_CORE.TRIP_MASTER TM 
	ON
		TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
	JOIN
		DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
	ON
		TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
	WHERE
		TD.TRANSACTION_TYPE = 'FREEPLAY'
	AND 
		TM.DELETE_IND = 'N'
	GROUP BY
		TD.TRIP_MASTER_ID
	)
	SELECT
		GUEST_UNIQUE_ID,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_POINT_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_POINT_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_POINT_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_DOLLAR_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_DOLLAR_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
	FROM 
		DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW TS
	JOIN 
		ABS_LOGIC AL
	ON 
		TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
	AND 
		DLC_FSP_FLG = 'Y'
	AND TS.GUEST_UNIQUE_ID <> -1
	GROUP BY GUEST_UNIQUE_ID
	HAVING 
	(PROPERTY_DLC_FSP_POINT_AMT<>MARKET_DLC_FSP_POINT_AMT OR MARKET_DLC_FSP_POINT_AMT<>ENTERPRISE_DLC_FSP_POINT_AMT OR PROPERTY_DLC_FSP_POINT_AMT<>ENTERPRISE_DLC_FSP_POINT_AMT)
	OR 
	(PROPERTY_DLC_FSP_DOLLAR_AMT<>MARKET_DLC_FSP_DOLLAR_AMT OR MARKET_DLC_FSP_DOLLAR_AMT<>ENTERPRISE_DLC_FSP_DOLLAR_AMT OR PROPERTY_DLC_FSP_DOLLAR_AMT<>ENTERPRISE_DLC_FSP_DOLLAR_AMT);
