CREATE TABLE IF NOT EXISTS DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW  
(
	I_CLIENTID                 INTEGER,
	I_SENDID                   INTEGER NOT NULL,
	C_SUBSCRIBER_KEY           VARCHAR(100) NOT NULL,
	I_DMID                     NUMBER(38,0),
	C_EMAILADDRESS             VARCHAR(200) ,
	I_SUBSCRIBERID             INTEGER,
	I_LISTID                   INTEGER,
	D_EVENTDATE                TIMESTAMP_NTZ(9),
	C_EVENTTYPE                VARCHAR(200) ,
	C_BOUNCE_CATEGORY          VARCHAR(100) ,
	I_SMTP_CODE                INTEGER,
	C_BOUNCE_REASON            VARCHAR(16777216) ,
	C_BATCHID                  VARCHAR(100) NOT NULL,
	C_TRIGGEREDSENDEXTERNALKEY VARCHAR(200) ,
	C_QUALITY_CD 			   VARCHAR(1) DEFAULT ' ',
	D_TIMESTAMP                TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	SOURCE_SYSTEM_NAME 		   VARCHAR(100),
	TIME_ZONE 				   VARCHAR(100),
	CREATED_DATE 			   TIMESTAMP_NTZ(9),
	CREATED_BY				   VARCHAR(100),
	UPDATED_DATE 			   TIMESTAMP_NTZ(9),
	UPDATED_BY 				   VARCHAR(100),
	BATCH_ID				   NUMBER(38,0),
	REPLAY_COUNTER 			   NUMBER(38,0),
	SOURCE_FILE_NAME 		   VARCHAR(200),
	DELETE_IND				   VARCHAR(1),
	LAST_DML_CD				   VARCHAR(1),
	MD5_CHECKSUM			   VARCHAR(32)
);

ALTER TABLE IF EXISTS DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW ADD SEARCH OPTIMIZATION ON EQUALITY(I_SENDID,I_DMID,C_BATCHID);