CREATE OR REPLACE TASK DAAS_COMMON.STG2RAW_CD_ET_BOUNCES_EVENT_TASK  
WAREHOUSE = DAAS_$ENV_IT_SRCTORAW_COMPUTE
SCHEDULE = 'USING CRON 0 10 * * * America/Los_Angeles'
WHEN SYSTEM$STREAM_HAS_DATA('DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG_STREAM')
AS
CALL DAAS_COMMON.BATCH_CONTROL_DATA_LOAD_WRAPPER_PROC('CD_ET_BOUNCES_EVENT_RAW','','Stg To Raw');