CREATE TASK DAAS_ADHOC.DIGITAL_PLAY_REPLAY_TASK
WAREHOUSE = DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L
AS
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('UPDATE DAAS_CORE.DIGITAL_TRANSACTIONS_FACT 
SET REPLAY_COUNTER=COALESCE(REPLAY_COUNTER,0)+1
WHERE CID IN(
SELECT DTF.CID 
FROM DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = \'William Hill\' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END 
WHERE (DGXBL.GUEST_UNIQUE_ID,TO_DATE(DTF.REPORT_DT)) IN (
SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_TEMP.DIGITAL_PLAY_VALIDATION))');