--Updated validation query
WITH ELIGIBLE_DIGITAL_FACT AS
(
SELECT
     DGXBL.GUEST_UNIQUE_ID
    ,'DIGITAL-'||DTF.BRAND_CD AS PROPERTY_CD
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
	DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
    ,PROPERTY_CD
	,DATE(DTF.REPORT_DT) 
),
DIGITAL_FACT AS
(
SELECT 
     GUEST_UNIQUE_ID
	,GUEST_ACTIVITY_DATE
	,SUM(CASINO_GGR) CASINO_GGR
	,SUM(SPORTS_GGR) SPORTS_GGR
	,SUM(POKER_GGR) POKER_GGR
	,SUM(SPORTS_THEO) SPORTS_THEO
	,SUM(CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(CASINO_WAGER) CASINO_WAGER
	,SUM(SPORTS_WAGER) SPORTS_WAGER
	,SUM(CASINO_BONUS) CASINO_BONUS
	,SUM(SPORTS_BONUS) SPORTS_BONUS
    ,MAX(UPDATED_DTTM) UPDATED_DTTM
FROM 
    ELIGIBLE_DIGITAL_FACT EDF
WHERE (EDF.CASINO_GGR+EDF.SPORTS_GGR+EDF.POKER_GGR+EDF.SPORTS_THEO+EDF.CASINO_NET_THEO+EDF.CASINO_WAGER+EDF.SPORTS_WAGER+EDF.CASINO_BONUS
+EDF.SPORTS_BONUS) <> 0
GROUP BY 
     GUEST_UNIQUE_ID
	,GUEST_ACTIVITY_DATE 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;

---------With view
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;

SELECT 
     DGXBL.GUEST_UNIQUE_ID
    ,'DIGITAL-'||DTF.BRAND_CD AS PROPERTY_CD
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
	DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
WHERE (GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE,PROPERTY_CD) IN (SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE,PROPERTY_CD 
                                                            FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
                                                            WHERE DIGITAL_FLG = 'Y' AND TRIP_TYPE='PROPERTY')
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
    ,PROPERTY_CD
	,DATE(DTF.REPORT_DT) 
HAVING SUM(DTF.CASINO_GGR)+SUM(DTF.SPORTS_GGR)+SUM(DTF.POKER_GGR)+SUM(DTF.CASINO_NET_THEO)
      +SUM(DTF.CASINO_WAGER)+SUM(DTF.SPORTS_WAGER)+SUM(DTF.CASINO_BONUS)+SUM(DTF.SPORTS_BONUS)=0;
 
-------With table
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM (SELECT
	DAILY_ACTIVITY_SUMMARY.GUEST_UNIQUE_ID AS GUEST_UNIQUE_ID,
	DAILY_ACTIVITY_SUMMARY.TRIP_TYPE AS TRIP_TYPE,
	DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE AS GUEST_ACTIVITY_DATE,
	DAILY_ACTIVITY_SUMMARY.CASINO_GGR AS CASINO_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_GGR AS SPORTS_GGR,
	DAILY_ACTIVITY_SUMMARY.POKER_GGR AS POKER_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_THEO AS SPORTS_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_NET_THEO AS CASINO_NET_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_WAGER AS CASINO_WAGER,
	DAILY_ACTIVITY_SUMMARY.SPORTS_WAGER AS SPORTS_WAGER,
	DAILY_ACTIVITY_SUMMARY.CASINO_BONUS AS CASINO_BONUS,
	DAILY_ACTIVITY_SUMMARY.SPORTS_BONUS AS SPORTS_BONUS,
	DAILY_ACTIVITY_SUMMARY.DIGITAL_FLG AS DIGITAL_FLG,
	DAILY_ACTIVITY_SUMMARY.UPDATED_DTTM AS UPDATED_DTTM
FROM
	DAAS_CORE.DAILY_ACTIVITY_SUMMARY DAILY_ACTIVITY_SUMMARY
JOIN 
    DAAS_CORE.TRIP_MASTER TRIP_MASTER 
ON
    DAILY_ACTIVITY_SUMMARY.TRIP_MASTER_ID = TRIP_MASTER.TRIP_MASTER_ID
WHERE
    TRIP_MASTER.DELETE_IND = 'N' 
AND DAILY_ACTIVITY_SUMMARY.TRIP_MASTER_ID <> -1 
AND DAILY_ACTIVITY_SUMMARY.DELETE_IND = 'N'
AND DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE <= CURRENT_DATE
UNION ALL
SELECT
	DAILY_ACTIVITY_SUMMARY.GUEST_UNIQUE_ID AS GUEST_UNIQUE_ID,
	DAILY_ACTIVITY_SUMMARY.TRIP_TYPE AS TRIP_TYPE,
	DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE AS GUEST_ACTIVITY_DATE,
	DAILY_ACTIVITY_SUMMARY.CASINO_GGR AS CASINO_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_GGR AS SPORTS_GGR,
	DAILY_ACTIVITY_SUMMARY.POKER_GGR AS POKER_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_THEO AS SPORTS_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_NET_THEO AS CASINO_NET_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_WAGER AS CASINO_WAGER,
	DAILY_ACTIVITY_SUMMARY.SPORTS_WAGER AS SPORTS_WAGER,
	DAILY_ACTIVITY_SUMMARY.CASINO_BONUS AS CASINO_BONUS,
	DAILY_ACTIVITY_SUMMARY.SPORTS_BONUS AS SPORTS_BONUS,
	DAILY_ACTIVITY_SUMMARY.DIGITAL_FLG AS DIGITAL_FLG,
	DAILY_ACTIVITY_SUMMARY.UPDATED_DTTM AS UPDATED_DTTM
FROM
	DAAS_CORE.DAILY_ACTIVITY_SUMMARY DAILY_ACTIVITY_SUMMARY
WHERE
    DAILY_ACTIVITY_SUMMARY.TRIP_MASTER_ID = -1 
AND DAILY_ACTIVITY_SUMMARY.DELETE_IND = 'N'
AND DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE <= CURRENT_DATE)
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;

--CHECK BATCH_ID
SELECT DISTINCT BACTH_ID FROM ( WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
	,MAX(DTF.BATCH_ID) BATCH_ID
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM (SELECT
	DAILY_ACTIVITY_SUMMARY.GUEST_UNIQUE_ID AS GUEST_UNIQUE_ID,
	DAILY_ACTIVITY_SUMMARY.TRIP_TYPE AS TRIP_TYPE,
	DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE AS GUEST_ACTIVITY_DATE,
	DAILY_ACTIVITY_SUMMARY.CASINO_GGR AS CASINO_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_GGR AS SPORTS_GGR,
	DAILY_ACTIVITY_SUMMARY.POKER_GGR AS POKER_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_THEO AS SPORTS_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_NET_THEO AS CASINO_NET_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_WAGER AS CASINO_WAGER,
	DAILY_ACTIVITY_SUMMARY.SPORTS_WAGER AS SPORTS_WAGER,
	DAILY_ACTIVITY_SUMMARY.CASINO_BONUS AS CASINO_BONUS,
	DAILY_ACTIVITY_SUMMARY.SPORTS_BONUS AS SPORTS_BONUS,
	DAILY_ACTIVITY_SUMMARY.DIGITAL_FLG AS DIGITAL_FLG,
	DAILY_ACTIVITY_SUMMARY.UPDATED_DTTM AS UPDATED_DTTM
FROM
	DAAS_CORE.DAILY_ACTIVITY_SUMMARY DAILY_ACTIVITY_SUMMARY
JOIN 
    DAAS_CORE.TRIP_MASTER TRIP_MASTER 
ON
    DAILY_ACTIVITY_SUMMARY.TRIP_MASTER_ID = TRIP_MASTER.TRIP_MASTER_ID
WHERE
    TRIP_MASTER.DELETE_IND = 'N' 
AND DAILY_ACTIVITY_SUMMARY.TRIP_MASTER_ID <> -1 
AND DAILY_ACTIVITY_SUMMARY.DELETE_IND = 'N'
AND DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE <= CURRENT_DATE
UNION ALL
SELECT
	DAILY_ACTIVITY_SUMMARY.GUEST_UNIQUE_ID AS GUEST_UNIQUE_ID,
	DAILY_ACTIVITY_SUMMARY.TRIP_TYPE AS TRIP_TYPE,
	DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE AS GUEST_ACTIVITY_DATE,
	DAILY_ACTIVITY_SUMMARY.CASINO_GGR AS CASINO_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_GGR AS SPORTS_GGR,
	DAILY_ACTIVITY_SUMMARY.POKER_GGR AS POKER_GGR,
	DAILY_ACTIVITY_SUMMARY.SPORTS_THEO AS SPORTS_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_NET_THEO AS CASINO_NET_THEO,
	DAILY_ACTIVITY_SUMMARY.CASINO_WAGER AS CASINO_WAGER,
	DAILY_ACTIVITY_SUMMARY.SPORTS_WAGER AS SPORTS_WAGER,
	DAILY_ACTIVITY_SUMMARY.CASINO_BONUS AS CASINO_BONUS,
	DAILY_ACTIVITY_SUMMARY.SPORTS_BONUS AS SPORTS_BONUS,
	DAILY_ACTIVITY_SUMMARY.DIGITAL_FLG AS DIGITAL_FLG,
	DAILY_ACTIVITY_SUMMARY.UPDATED_DTTM AS UPDATED_DTTM
FROM
	DAAS_CORE.DAILY_ACTIVITY_SUMMARY DAILY_ACTIVITY_SUMMARY
WHERE
    DAILY_ACTIVITY_SUMMARY.TRIP_MASTER_ID = -1 
AND DAILY_ACTIVITY_SUMMARY.DELETE_IND = 'N'
AND DAILY_ACTIVITY_SUMMARY.GUEST_ACTIVITY_DATE <= CURRENT_DATE)
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
,DIGITAL_FACT.BATCH_ID
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM);

---Updated validation query
--ENTERPRISE
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND (CASINO_GGR_DIFF+SPORTS_GGR_DIFF+POKER_GGR_DIFF+SPORTS_THEO_DIFF+CASINO_NET_THEO_DIFF+CASINO_WAGER_DIFF+SPORTS_WAGER_DIFF+
      CASINO_BONUS_DIFF+SPORTS_BONUS_DIFF) <> 0
AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;


--PROPERTY
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,SUM(CASINO_GGR) CASINO_GGR
,SUM(SPORTS_GGR) SPORTS_GGR
,SUM(POKER_GGR) POKER_GGR
,SUM(SPORTS_THEO) SPORTS_THEO
,SUM(CASINO_NET_THEO) CASINO_NET_THEO
,SUM(CASINO_WAGER) CASINO_WAGER
,SUM(SPORTS_WAGER) SPORTS_WAGER
,SUM(CASINO_BONUS) CASINO_BONUS
,SUM(SPORTS_BONUS) SPORTS_BONUS
,MAX(UPDATED_DTTM) UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'PROPERTY'
GROUP BY GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND (CASINO_GGR_DIFF+SPORTS_GGR_DIFF+POKER_GGR_DIFF+SPORTS_THEO_DIFF+CASINO_NET_THEO_DIFF+CASINO_WAGER_DIFF+SPORTS_WAGER_DIFF+
      CASINO_BONUS_DIFF+SPORTS_BONUS_DIFF) <> 0
AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;

--MARKET
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'MARKET'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND (CASINO_GGR_DIFF+SPORTS_GGR_DIFF+POKER_GGR_DIFF+SPORTS_THEO_DIFF+CASINO_NET_THEO_DIFF+CASINO_WAGER_DIFF+SPORTS_WAGER_DIFF+
      CASINO_BONUS_DIFF+SPORTS_BONUS_DIFF) <> 0
AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;

--PROP VS MKT VS ENT
SELECT
	GUEST_UNIQUE_ID,
	GUEST_ACTIVITY_DATE,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CASINO_GGR  ELSE 0 END) AS PROP_CASINO_GGR ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CASINO_GGR  ELSE 0 END) AS MKT_CASINO_GGR ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CASINO_GGR  ELSE 0 END) AS ENT_CASINO_GGR ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SPORTS_GGR ELSE 0 END) AS PROP_SPORTS_GGR,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SPORTS_GGR ELSE 0 END) AS MKT_SPORTS_GGR,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SPORTS_GGR ELSE 0 END) AS ENT_SPORTS_GGR,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN POKER_GGR ELSE 0 END) AS PROP_POKER_GGR,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN POKER_GGR ELSE 0 END) AS MKT_POKER_GGR,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN POKER_GGR ELSE 0 END) AS ENT_POKER_GGR,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SPORTS_THEO ELSE 0 END) AS PROP_SPORTS_THEO ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SPORTS_THEO ELSE 0 END) AS MKT_SPORTS_THEO ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SPORTS_THEO ELSE 0 END) AS ENT_SPORTS_THEO ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CASINO_NET_THEO ELSE 0 END) AS PROP_CASINO_NET_THEO ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CASINO_NET_THEO ELSE 0 END) AS MKT_CASINO_NET_THEO ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CASINO_NET_THEO ELSE 0 END) AS ENT_CASINO_NET_THEO ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CASINO_WAGER ELSE 0 END) AS PROP_CASINO_WAGER ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CASINO_WAGER ELSE 0 END) AS MKT_CASINO_WAGER ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CASINO_WAGER ELSE 0 END) AS ENT_CASINO_WAGER ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SPORTS_WAGER ELSE 0 END) AS PROP_SPORTS_WAGER ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SPORTS_WAGER ELSE 0 END) AS MKT_SPORTS_WAGER ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SPORTS_WAGER ELSE 0 END) AS ENT_SPORTS_WAGER ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN CASINO_BONUS ELSE 0 END) AS PROP_CASINO_BONUS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN CASINO_BONUS ELSE 0 END) AS MKT_CASINO_BONUS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN CASINO_BONUS ELSE 0 END) AS ENT_CASINO_BONUS ,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN SPORTS_BONUS ELSE 0 END) AS PROP_SPORTS_BONUS ,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN SPORTS_BONUS ELSE 0 END) AS MKT_SPORTS_BONUS ,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN SPORTS_BONUS ELSE 0 END) AS ENT_SPORTS_BONUS  
FROM
	DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
	AND DIGITAL_FLG = 'Y'
GROUP BY 
	GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE
HAVING 
( PROP_CASINO_GGR  <> MKT_CASINO_GGR  OR MKT_CASINO_GGR  <> ENT_CASINO_GGR  OR ENT_CASINO_GGR  <> PROP_CASINO_GGR ) OR
( PROP_SPORTS_GGR <> MKT_SPORTS_GGR OR MKT_SPORTS_GGR <> ENT_SPORTS_GGR OR ENT_SPORTS_GGR <> PROP_SPORTS_GGR) OR
( PROP_POKER_GGR <> MKT_POKER_GGR OR MKT_POKER_GGR <> ENT_POKER_GGR OR ENT_POKER_GGR <> PROP_POKER_GGR) OR
( PROP_SPORTS_THEO <> MKT_SPORTS_THEO OR MKT_SPORTS_THEO <> ENT_SPORTS_THEO OR ENT_SPORTS_THEO <> PROP_SPORTS_THEO ) OR
( PROP_CASINO_NET_THEO <> MKT_CASINO_NET_THEO OR MKT_CASINO_NET_THEO <> ENT_CASINO_NET_THEO OR ENT_CASINO_NET_THEO <> PROP_CASINO_NET_THEO ) OR
( PROP_CASINO_WAGER <> MKT_CASINO_WAGER OR MKT_CASINO_WAGER <> ENT_CASINO_WAGER OR ENT_CASINO_WAGER <> PROP_CASINO_WAGER ) OR
( PROP_SPORTS_WAGER <> MKT_SPORTS_WAGER OR MKT_SPORTS_WAGER <> ENT_SPORTS_WAGER OR ENT_SPORTS_WAGER <> PROP_SPORTS_WAGER ) OR
( PROP_CASINO_BONUS <> MKT_CASINO_BONUS OR MKT_CASINO_BONUS <> ENT_CASINO_BONUS OR ENT_CASINO_BONUS <> PROP_CASINO_BONUS ) OR
( PROP_SPORTS_BONUS <> MKT_SPORTS_BONUS OR MKT_SPORTS_BONUS <> ENT_SPORTS_BONUS OR ENT_SPORTS_BONUS <> PROP_SPORTS_BONUS );

---
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DGXBL.SOURCE_SYSTEM_NM = 'WH' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
WHERE (CASINO_GGR <> 0
OR SPORTS_GGR <> 0
OR POKER_GGR <> 0
OR SPORTS_THEO <> 0
OR CASINO_NET_THEO <> 0
OR CASINO_WAGER <> 0
OR SPORTS_WAGER <> 0
OR CASINO_BONUS <> 0
OR SPORTS_BONUS <> 0
) AND (CASINO_GGR+SPORTS_GGR+POKER_GGR+SPORTS_THEO+CASINO_NET_THEO+CASINO_WAGER+SPORTS_WAGER+
      CASINO_BONUS+SPORTS_BONUS) <> 0
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND (CASINO_GGR_DIFF+SPORTS_GGR_DIFF+POKER_GGR_DIFF+SPORTS_THEO_DIFF+CASINO_NET_THEO_DIFF+CASINO_WAGER_DIFF+SPORTS_WAGER_DIFF+
      CASINO_BONUS_DIFF+SPORTS_BONUS_DIFF) <> 0
AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;

---
WITH DIGITAL_FACT AS
(
SELECT 
     DGXBL.GUEST_UNIQUE_ID
	,TO_DATE(DTF.REPORT_DT) AS GUEST_ACTIVITY_DATE
	,SUM(DTF.CASINO_GGR) CASINO_GGR
	,SUM(DTF.SPORTS_GGR) SPORTS_GGR
	,SUM(DTF.POKER_GGR) POKER_GGR
	,SUM(DTF.SPORTS_THEO) SPORTS_THEO
	,SUM(DTF.CASINO_NET_THEO) CASINO_NET_THEO
	,SUM(DTF.CASINO_WAGER) CASINO_WAGER
	,SUM(DTF.SPORTS_WAGER) SPORTS_WAGER
	,SUM(DTF.CASINO_BONUS) CASINO_BONUS
	,SUM(DTF.SPORTS_BONUS) SPORTS_BONUS
    ,MAX(DTF.UPDATED_DTTM) UPDATED_DTTM
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DGXBL.SOURCE_SYSTEM_NM = 'WH' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
WHERE 
(CASINO_GGR <> 0
OR SPORTS_GGR <> 0
OR POKER_GGR <> 0
OR SPORTS_THEO <> 0
OR CASINO_NET_THEO <> 0
OR CASINO_WAGER <> 0
OR SPORTS_WAGER <> 0
OR CASINO_BONUS <> 0
OR SPORTS_BONUS <> 0
)
GROUP BY 
     DGXBL.GUEST_UNIQUE_ID
	,DATE(DTF.REPORT_DT) 
),
DAILY_ACTIVITY AS
(
SELECT 
GUEST_UNIQUE_ID
,GUEST_ACTIVITY_DATE
,CASINO_GGR
,SPORTS_GGR
,POKER_GGR
,SPORTS_THEO
,CASINO_NET_THEO
,CASINO_WAGER
,SPORTS_WAGER
,CASINO_BONUS
,SPORTS_BONUS
,UPDATED_DTTM
FROM DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE DIGITAL_FLG = 'Y'  AND TRIP_TYPE = 'ENTERPRISE'
)
SELECT 
DIGITAL_FACT.GUEST_UNIQUE_ID
,DIGITAL_FACT.GUEST_ACTIVITY_DATE
,DIGITAL_FACT.UPDATED_DTTM DIGITAL_UPDATE_DTTM
,DAILY_ACTIVITY.UPDATED_DTTM DAILY_ACTIVITY_DTTM
,(DIGITAL_FACT.CASINO_GGR - DAILY_ACTIVITY.CASINO_GGR) AS CASINO_GGR_DIFF 
,(DIGITAL_FACT.SPORTS_GGR - DAILY_ACTIVITY.SPORTS_GGR) AS SPORTS_GGR_DIFF
,(DIGITAL_FACT.POKER_GGR - DAILY_ACTIVITY.POKER_GGR) AS POKER_GGR_DIFF
,(DIGITAL_FACT.SPORTS_THEO - DAILY_ACTIVITY.SPORTS_THEO) AS SPORTS_THEO_DIFF
,(DIGITAL_FACT.CASINO_NET_THEO - DAILY_ACTIVITY.CASINO_NET_THEO) AS CASINO_NET_THEO_DIFF 
,(DIGITAL_FACT.CASINO_WAGER - DAILY_ACTIVITY.CASINO_WAGER) AS CASINO_WAGER_DIFF 
,(DIGITAL_FACT.SPORTS_WAGER - DAILY_ACTIVITY.SPORTS_WAGER) AS SPORTS_WAGER_DIFF
,(DIGITAL_FACT.CASINO_BONUS - DAILY_ACTIVITY.CASINO_BONUS) AS CASINO_BONUS_DIFF
,(DIGITAL_FACT.SPORTS_BONUS - DAILY_ACTIVITY.SPORTS_BONUS) AS SPORTS_BONUS_DIFF
FROM DIGITAL_FACT
JOIN DAILY_ACTIVITY
ON DAILY_ACTIVITY.GUEST_UNIQUE_ID = DIGITAL_FACT.GUEST_UNIQUE_ID
AND DAILY_ACTIVITY.GUEST_ACTIVITY_DATE = DIGITAL_FACT.GUEST_ACTIVITY_DATE
WHERE 
(CASINO_GGR_DIFF <> 0
OR SPORTS_GGR_DIFF <> 0
OR POKER_GGR_DIFF <> 0
OR SPORTS_THEO_DIFF <> 0
OR CASINO_NET_THEO_DIFF <> 0
OR CASINO_WAGER_DIFF <> 0
OR SPORTS_WAGER_DIFF <> 0
OR CASINO_BONUS_DIFF <> 0
OR SPORTS_BONUS_DIFF <> 0
) AND (CASINO_GGR_DIFF+SPORTS_GGR_DIFF+POKER_GGR_DIFF+SPORTS_THEO_DIFF+CASINO_NET_THEO_DIFF+CASINO_WAGER_DIFF+SPORTS_WAGER_DIFF+
      CASINO_BONUS_DIFF+SPORTS_BONUS_DIFF) <> 0
AND DIGITAL_FACT.GUEST_UNIQUE_ID <> -1
AND DAILY_ACTIVITY.UPDATED_DTTM >= DIGITAL_FACT.UPDATED_DTTM;