-------------------------DEV---------------------------
LS @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/ET;
--CD_ET_2024_02_15_SF_000@CD_Open.txt@2024-02-18
--CD_ET_2024_02_19_SF_000@CD_Open.txt@2024-02-19

--------------------------NON CD OBJECT----------------

SHOW PIPES LIKE '%cd_et_bounces_event_daas_snowpipe%' IN DAAS_STG_EXACT_TARGET;

//COPY INTO DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG
(
	I_CLIENTID,                
	I_SENDID,                  
	C_SUBSCRIBER_KEY,          
	C_EMAILADDRESS,            
	I_SUBSCRIBERID,            
	I_LISTID,                 
	D_EVENTDATE,               
	C_EVENTTYPE,               
	C_BOUNCE_CATEGORY,         
	I_SMTP_CODE,               
	C_BOUNCE_REASON,           
	C_BATCHID,                 
	C_TRIGGEREDSENDEXTERNALKEY,
	SOURCE_SYSTEM_NAME,        
	TIME_ZONE, 				  
	CREATED_DATE, 			  
	CREATED_BY,				  
	UPDATED_DATE,			  
	UPDATED_BY, 				  
	REPLAY_COUNTER, 			  
	SOURCE_FILE_NAME
)
FROM
(SELECT 
	TRIM($1),
	TRIM($2),
	TRIM($3),
	TRIM($4),
	TRIM($5),
	TRIM($6),
	TRIM($7),
	TRIM($8),
	TRIM($9),
	TRIM($10),
	TRIM($11),
	TRIM($12),
	TRIM($13),
	'EXACT TARGET',
	'US/CENTRAL',
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	0,
	METADATA$FILENAME
FROM @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/ET
)
PATTERN = '.*Bounces.*'
/*FILE_FORMAT = 'DAAS_COMMON.ET_PIPE_FORMAT'*/ 
file_format = (type = csv field_delimiter = '|' skip_header = 1 escape = '\134' encoding = 'iso-8859-1') 
force = true;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG; AT (OFFSET =>-60*60*3);


//TRUNCATE TABLE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG
WHERE I_CLIENTID=6253030 AND C_BATCHID=302816;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG
WHERE I_CLIENTID=6253030 AND C_BATCHID=656575;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG
WHERE I_CLIENTID=6253030 AND C_BATCHID=302829;

//UPDATE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG SET C_EMAILADDRESS='test'
//WHERE I_CLIENTID=6253030 AND C_BATCHID=302816;
//
//UPDATE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG SET C_EMAILADDRESS='test'
//WHERE I_CLIENTID=6253030 AND C_BATCHID=656575;
//
//UPDATE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG SET C_EMAILADDRESS='test'
//WHERE I_CLIENTID=6253030 AND C_BATCHID=302829;

SELECT * FROM  DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

//UPDATE DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW SET MD5_CHECKSUM='test123'
//WHERE I_CLIENTID=6253030 AND C_BATCHID=302816;
//
//UPDATE DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW SET MD5_CHECKSUM='test234'
//WHERE I_CLIENTID=6253030 AND C_BATCHID=656575;
//
//UPDATE DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW SET MD5_CHECKSUM='test456'
//WHERE I_CLIENTID=6253030 AND C_BATCHID=302829;

//CREATE OR REPLACE STREAM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG_STREAM ON TABLE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG; 

//TRUNCATE TABLE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG;

//TRUNCATE TABLE DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG_STREAM;

CALL DAAS_COMMON.BATCH_CONTROL_DATA_LOAD_WRAPPER_PROC('ET_BOUNCES_EVENT_RAW','','Stg TO Raw');

SELECT COUNT(*) FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

UPDATE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG SET REPLAY_COUNTER=REPLAY_COUNTER+1;

SELECT * FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW
MINUS 
SELECT * FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW AT(OFFSET => -60*15);--528

SELECT * FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW
WHERE I_CLIENTID=6253030 AND I_SENDID=1298799 AND C_SUBSCRIBER_KEY='dawn@amctrans.com';

UPDATE DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG 
SET REPLAY_COUNTER=REPLAY_COUNTER+1;

select * from daas_common.job where job_name='CD_ET_BOUNCES_EVENT_RAW';

SELECT * FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

//TRUNCATE TABLE DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

SELECT * FROM DAAS_CORE_MARKETING_VW.ET_BOUNCES_EVENT_VW;

SELECT * FROM DAAS_TERADATA_RAW.ET_BOUNCES_EVENT;

-----------------------CD OBJECT---------------

//TRUNCATE TABLE DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG;

SELECT * FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG;

SELECT * FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG_STREAM;

//UPDATE DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG 
//SET REPLAY_COUNTER=REPLAY_COUNTER+1;

CALL DAAS_COMMON.BATCH_CONTROL_DATA_LOAD_WRAPPER_PROC('CD_ET_BOUNCES_EVENT_RAW','','Stg TO Raw');

//TRUNCATE TABLE DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW; 

SELECT COUNT(*) FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW;

SELECT * FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW;

DESC TABLE DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW;

UPDATE DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW SET MD5_CHECKSUM='test123'
WHERE I_CLIENTID=6253031 AND C_BATCHID='725636';

UPDATE DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW SET MD5_CHECKSUM='test234'
WHERE I_CLIENTID=6253031 AND C_BATCHID='725643';

UPDATE DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW SET MD5_CHECKSUM='test456'
WHERE I_CLIENTID=6253031 AND C_BATCHID='725662';

SELECT * FROM DAAS_CORE_MARKETING_VW.CD_ET_BOUNCES_EVENT_VW;

SELECT * FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG;

//COPY INTO DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG
(
	I_CLIENTID,                
	I_SENDID,                  
	C_SUBSCRIBER_KEY,          
	C_EMAILADDRESS,            
	I_SUBSCRIBERID,            
	I_LISTID,                 
	D_EVENTDATE,               
	C_EVENTTYPE,               
	C_BOUNCE_CATEGORY,         
	I_SMTP_CODE,               
	C_BOUNCE_REASON,           
	C_BATCHID,                 
	C_TRIGGEREDSENDEXTERNALKEY,
	SOURCE_SYSTEM_NAME,        
	TIME_ZONE, 				  
	CREATED_DATE, 			  
	CREATED_BY,				  
	UPDATED_DATE,			  
	UPDATED_BY, 				  
	REPLAY_COUNTER, 			  
	SOURCE_FILE_NAME
)
FROM
(SELECT 
	TRIM($1),
	TRIM($2),
	TRIM($3),
	TRIM($4),
	TRIM($5),
	TRIM($6),
	TRIM($7),
	TRIM($8),
	TRIM($9),
	TRIM($10),
	TRIM($11),
	TRIM($12),
	TRIM($13),
	'EXACT TARGET',
	'US/CENTRAL',
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	0,
	METADATA$FILENAME
FROM @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/CD_ET
)
PATTERN = '.*CD_Bounces.*'
/*FILE_FORMAT = 'DAAS_COMMON.ET_PIPE_FORMAT'*/
file_format = (type = csv field_delimiter = '|' skip_header = 1 escape = '\134' encoding = 'iso-8859-1') 
force=true;
------------------------
SELECT
	SRC.I_CLIENTID,                
	SRC.I_SENDID,                  
	SRC.C_SUBSCRIBER_KEY,          
	DAAS_COMMON.EXACT_TARGET_I_DMID_UDF(SRC.C_SUBSCRIBER_KEY) AS I_DMID,                    
	SRC.C_EMAILADDRESS,            
	SRC.I_SUBSCRIBERID,            
	SRC.I_LISTID,                  
	SRC.D_EVENTDATE,               
	SRC.C_EVENTTYPE,               
	SRC.C_BOUNCE_CATEGORY,        
	SRC.I_SMTP_CODE,               
	SRC.C_BOUNCE_REASON,          
	SRC.C_BATCHID,                 
	SRC.C_TRIGGEREDSENDEXTERNALKEY,
	' ' AS C_QUALITY_CD,			  
	CURRENT_TIMESTAMP AS D_TIMESTAMP,               
	SRC.SOURCE_SYSTEM_NAME, 		  
	SRC.TIME_ZONE, 				  
	CURRENT_TIMESTAMP AS CREATED_DTTM,
	CURRENT_USER AS CREATED_BY,
	CURRENT_TIMESTAMP AS UPDATED_DTTM,
	CURRENT_USER AS UPDATED_BY,
	2070185 AS BATCH_ID,
	SRC.REPLAY_COUNTER,
	SRC.SOURCE_FILE_NAME,
	'N' AS DELETE_IND,
	'I' AS LAST_DML_CD,
	MD5(
		COALESCE(SRC.i_clientid, '')||'~'||
		COALESCE(SRC.c_emailaddress::VARCHAR, '')||'~'||
		COALESCE(SRC.i_subscriberid::VARCHAR, '')||'~'||
		COALESCE(SRC.i_listid::VARCHAR, '')||'~'||
		COALESCE(SRC.d_eventdate::VARCHAR, '')||'~'||
		COALESCE(SRC.c_eventtype::VARCHAR, '')||'~'||
		COALESCE(SRC.c_bounce_category::VARCHAR, '')||'~'||
		COALESCE(SRC.i_smtp_code::VARCHAR, '')||'~'||
		COALESCE(SRC.c_bounce_reason::VARCHAR, '')||'~'||
		COALESCE(SRC.c_triggeredsendexternalkey::VARCHAR, '')
	) AS MD5_CHECKSUM
FROM	
	DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG SRC
WHERE NOT EXISTS
(
	SELECT 
		1
	FROM
		DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW RAW
	WHERE
		I_SENDID = RAW.I_SENDID
	AND I_DMID = RAW.I_DMID
	AND C_BATCHID = RAW.C_BATCHID
)
OR MD5_CHECKSUM NOT IN (
SELECT RAW.MD5_CHECKSUM 
FROM
		DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW RAW
	WHERE
		I_SENDID = RAW.I_SENDID
    AND I_DMID = RAW.I_DMID
	AND C_BATCHID = RAW.C_BATCHID);
    

//COPY INTO DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG
(
	I_CLIENTID,                
	I_SENDID,                  
	C_SUBSCRIBER_KEY,          
	C_EMAILADDRESS,            
	I_SUBSCRIBERID,            
	I_LISTID,                 
	D_EVENTDATE,               
	C_EVENTTYPE,               
	C_BOUNCE_CATEGORY,         
	I_SMTP_CODE,               
	C_BOUNCE_REASON,           
	C_BATCHID,                 
	C_TRIGGEREDSENDEXTERNALKEY,
	SOURCE_SYSTEM_NAME,        
	TIME_ZONE, 				  
	CREATED_DATE, 			  
	CREATED_BY,				  
	UPDATED_DATE,			  
	UPDATED_BY, 				  
	REPLAY_COUNTER, 			  
	SOURCE_FILE_NAME
)
FROM
(SELECT 
	TRIM($1),
	TRIM($2),
	TRIM($3),
	TRIM($4),
	TRIM($5),
	TRIM($6),
	TRIM($7),
	TRIM($8),
	TRIM($9),
	TRIM($10),
	TRIM($11),
	TRIM($12),
	TRIM($13),
	'EXACT TARGET',
	'US/CENTRAL',
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	0,
	METADATA$FILENAME
FROM @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/CD_ET
)
PATTERN = '.*CD_Bounces.*'
/*FILE_FORMAT = 'DAAS_COMMON.ET_PIPE_FORMAT'*/
file_format = (type = csv field_delimiter = '|' skip_header = 1 escape = '\134' encoding = 'iso-8859-1') ;

-------------------

select * from DAAS_STG_EXACT_TARGET.CD_ET_OPEN_EVENT_STG;

COPY INTO DAAS_STG_EXACT_TARGET.CD_ET_OPEN_EVENT_STG
(
	I_CLIENTID,
	I_SENDID,
	C_SUBSCRIBER_KEY,
	C_EMAILADDRESS,
	I_SUBSCRIBERID,
	I_LISTID,
	D_EVENTDATE,
	C_EVENTTYPE,
	C_BATCHID,
	C_TRIGGEREDSENDEXTERNALKEY,
	SOURCE_SYSTEM_NAME,
	TIME_ZONE,
	CREATED_DATE,
	CREATED_BY,
	UPDATED_DATE,
	UPDATED_BY,
	REPLAY_COUNTER,
	SOURCE_FILE_NAME
)
FROM
(SELECT 
	TRIM($1),
	TRIM($2),
	TRIM($3),
	TRIM($4),
	TRIM($5),
	TRIM($6),
	TRIM($7),
	TRIM($8),
	TRIM($9),
	TRIM($10),
	'EXACT TARGET',
	'US/CENTRAL',
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	CURRENT_TIMESTAMP,
	CURRENT_USER,
	0,
	METADATA$FILENAME
FROM @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/OUT/CD_ET
)
PATTERN = '.*CD_Open.*'
/* file_format = 'DAAS_COMMON.ET_PIPE_FORMAT' */
file_format = (type = csv field_delimiter = '|' skip_header = 1 escape = '\134' encoding = 'iso-8859-1') 
;

LS @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/CD_ET PATTERN = '.*CD_Open.*';
--CD_ET_2024_02_15_SF_000@CD_Open.txt@2024-02-18
--CD_ET_2024_02_19_SF_000@CD_Open.txt@2024-02-19

SELECT * FROM DAAS_TERADATA_RAW.CD_ET_BOUNCES_EVENT;

SELECT * FROM DAAS_CORE_MARKETING_VW.CD_ET_BOUNCES_EVENT_VW;

DESC TABLE DAAS_TERADATA_RAW.ET_BOUNCES_EVENT;
DESC TABLE DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

SELECT GET_DDL('TABLE','DAAS_TERADATA_RAW.CD_ET_BOUNCES_EVENT');
SELECT GET_DDL('TABLE','DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW');

SELECT * FROM DAAS_TERADATA_RAW.ET_BOUNCES_EVENT;

SELECT * FROM DAAS_CORE_MARKETING_VW.ET_BOUNCES_EVENT_VW;

SELECT COUNT(*) FROM DAAS_TERADATA_RAW.ET_BOUNCES_EVENT;--1000
SELECT COUNT(*) FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;--47524

WITH RAW_CTE AS
(
SELECT
	 TD_RAW.I_CLIENTID                
	,TD_RAW.I_SENDID                  
	,TD_RAW.C_SUBSCRIBER_KEY          
	,TD_RAW.I_DMID
	,LKP.PRIMARY_ACCOUNT_NBR AS I_XREF_DMID
	,TD_RAW.C_EMAILADDRESS            
	,TD_RAW.I_SUBSCRIBERID            
	,TD_RAW.I_LISTID                  
	,TD_RAW.D_EVENTDATE               
	,TD_RAW.C_EVENTTYPE               
	,TD_RAW.C_BOUNCE_CATEGORY         
	,TD_RAW.I_SMTP_CODE               
	,TD_RAW.C_BOUNCE_REASON           
	,TD_RAW.C_BATCHID                 
	,TD_RAW.C_TRIGGEREDSENDEXTERNALKEY
	,TD_RAW.C_QUALITY_CD 			  
	,TD_RAW.D_TIMESTAMP
FROM
	DAAS_TERADATA_RAW.ET_BOUNCES_EVENT TD_RAW
JOIN
	DAAS_CORE.GUEST_XREF_BRIDGE_LKP LKP
ON
	TRY_TO_NUMBER(TD_RAW.I_DMID) = LKP.XREF_ACCOUNT_NBR
WHERE
	LKP.XREF_ACCOUNT_NBR <> -1
UNION ALL
SELECT
	 RAW.I_CLIENTID                
	,RAW.I_SENDID                  
	,RAW.C_SUBSCRIBER_KEY          
	,RAW.I_DMID   
	,LKP.PRIMARY_ACCOUNT_NBR AS I_XREF_DMID	
	,RAW.C_EMAILADDRESS            
	,RAW.I_SUBSCRIBERID            
	,RAW.I_LISTID                  
	,RAW.D_EVENTDATE               
	,RAW.C_EVENTTYPE               
	,RAW.C_BOUNCE_CATEGORY         
	,RAW.I_SMTP_CODE               
	,RAW.C_BOUNCE_REASON           
	,RAW.C_BATCHID                 
	,RAW.C_TRIGGEREDSENDEXTERNALKEY
	,RAW.C_QUALITY_CD 			  
	,RAW.D_TIMESTAMP
FROM
	DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW RAW
JOIN
	DAAS_CORE.GUEST_XREF_BRIDGE_LKP LKP
ON
	RAW.I_DMID = LKP.XREF_ACCOUNT_NBR
WHERE
	LKP.XREF_ACCOUNT_NBR <> -1
)
SELECT
	 I_CLIENTID                
	,I_SENDID                  
	,C_SUBSCRIBER_KEY          
	,I_DMID
	,I_XREF_DMID	
	,C_EMAILADDRESS            
	,I_SUBSCRIBERID            
	,I_LISTID                  
	,D_EVENTDATE               
	,C_EVENTTYPE               
	,C_BOUNCE_CATEGORY         
	,I_SMTP_CODE               
	,C_BOUNCE_REASON           
	,C_BATCHID                 
	,C_TRIGGEREDSENDEXTERNALKEY
	,C_QUALITY_CD 			  
	,D_TIMESTAMP
FROM
	RAW_CTE
QUALIFY ROW_NUMBER() OVER(PARTITION BY I_SENDID, I_DMID, C_BATCHID
ORDER BY D_EVENTDATE DESC, D_TIMESTAMP DESC) = 1;--28,572 

SELECT D_EVENTDATE,D_TIMESTAMP,* FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW
WHERE I_SENDID=1284972 AND C_BATCHID=6022;

SELECT D_EVENTDATE,D_TIMESTAMP,* FROM DAAS_TERADATA_RAW.CD_ET_BOUNCES_EVENT
WHERE I_SENDID=1284972 AND C_BATCHID=6022;

SELECT * FROM DAAS_TERADATA_RAW.CD_ET_BOUNCES_EVENT
WHERE (I_SENDID,C_BATCHID) IN (SELECT DISTINCT I_SENDID,C_BATCHID FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW);

SELECT COUNT(*) FROM DAAS_TERADATA_RAW.ET_BOUNCES_EVENT;--1000
SELECT COUNT(*) FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;--47524

SELECT D_EVENTDATE,D_TIMESTAMP,* FROM DAAS_CORE_MARKETING_VW.CD_ET_BOUNCES_EVENT_VW 
WHERE I_SENDID=1284972 AND C_BATCHID=6022;


SELECT * FROM DAAS_CORE_MARKETING_VW.CD_ET_BOUNCES_EVENT_VW;

SELECT * FROM DAAS_TERADATA_RAW.CD_ET_BOUNCES_EVENT limit 1;

DESC TABLE DAAS_TERADATA_RAW.CD_ET_BOUNCES_EVENT;

//DROP PIPE DAAS_COMMON.STG_ET_BOUNCES_EVENT_DAAS_SNOWPIPE;

INSERT INTO DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW
(I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,I_DMID,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,D_EVENTDATE,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY,C_QUALITY_CD,D_TIMESTAMP) 
VALUES
(6253031,1284972,'81EDC29B71226B08_NY',0,'shawncaines72@gmail.com',202646656,40,'2024-01-20 10:16:55.000','Bounce','Soft bounce',452,'Mailbox Full',6022,'','','2024-01-20 21:53:15.000');

--------------------------------------UAT----------------------------------
LS @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/ET;

SELECT * FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG;--36,088 

SELECT COUNT(*) FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG_STREAM;

SELECT * FROM DAAS_SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY 
WHERE TABLE_CATALOG_NAME = 'DAAS_UAT' 
AND TABLE_SCHEMA_NAME = 'DAAS_STG_EXACT_TARGET' 
AND TABLE_NAME = 'ET_BOUNCES_EVENT_STG' 
ORDER BY LAST_LOAD_TIME DESC
LIMIT 10;
 
 
SELECT * FROM DAAS_SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE TABLE_CATALOG_NAME = 'DAAS_UAT'
AND TABLE_SCHEMA_NAME = 'DAAS_STG_EXACT_TARGET'
AND TABLE_NAME = 'CD_ET_BOUNCES_EVENT_STG'
ORDER BY LAST_LOAD_TIME DESC
LIMIT 10;

SHOW GRANTS TO ROLE DMK1_UAT;

//CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_STG_EXACT_TARGET', 'ET_BOUNCES_EVENT_STG', '', 
'ET_INCREMENTAL', 1000000000);

//CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_STG_EXACT_TARGET', 'CD_ET_BOUNCES_EVENT_STG', '', 
'CD_ET_INCREMENTAL', 1000000000);

SELECT COUNT(*) FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

SHOW STREAMS LIKE 'ET_BOUNCES_EVENT_STG_STREAM';

ALTER TASK DAAS_COMMON.STG2RAW_ET_BOUNCES_EVENT_TASK RESUME;
ALTER TASK DAAS_COMMON.STG2RAW_CD_ET_BOUNCES_EVENT_TASK RESUME;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG;

SELECT I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY
FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG
MINUS
SELECT I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY
FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW ;

SELECT I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY
FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW 
MINUS
SELECT I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY
FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG;

SELECT I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY
FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG 
MINUS
SELECT I_CLIENTID,I_SENDID,C_SUBSCRIBER_KEY,C_EMAILADDRESS,I_SUBSCRIBERID,I_LISTID,C_EVENTTYPE,C_BOUNCE_CATEGORY,I_SMTP_CODE,C_BOUNCE_REASON,C_BATCHID,C_TRIGGEREDSENDEXTERNALKEY
FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW;

LS @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/ET;
LS @DAAS_COMMON.DAAS_EXT_STG_HOSTED/exact-target/out/CD_ET;

SHOW PIPES LIKE 'STG_CD_ET_STATUS_CHANGE_DAAS_SNOWPIPE';--CD_ET_2024_02_14_status_000@CD_StatusChange.txt
--2024-02-21 01:42:47.015 -0800

SELECT * FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG;--1725 

SELECT COUNT(*) FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG_STREAM;

SELECT * FROM DAAS_SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY 
WHERE TABLE_CATALOG_NAME = 'DAAS_UAT' 
AND TABLE_SCHEMA_NAME = 'DAAS_STG_EXACT_TARGET' 
AND TABLE_NAME = 'ET_BOUNCES_EVENT_STG' 
ORDER BY LAST_LOAD_TIME DESC
LIMIT 10;
 
 
SELECT * FROM DAAS_SNOWFLAKE.ACCOUNT_USAGE.COPY_HISTORY
WHERE TABLE_CATALOG_NAME = 'DAAS_UAT'
AND TABLE_SCHEMA_NAME = 'DAAS_STG_EXACT_TARGET';
AND TABLE_NAME = 'CD_ET_STATUS_CHANGE_STG'
ORDER BY LAST_LOAD_TIME DESC
LIMIT 10;

SHOW GRANTS TO ROLE DMK1_UAT;

//CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_STG_EXACT_TARGET', 'ET_BOUNCES_EVENT_STG', '', 
'ET_INCREMENTAL', 1000000000);

//CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_STG_EXACT_TARGET', 'CD_ET_BOUNCES_EVENT_STG', '', 
'CD_ET_INCREMENTAL', 1000000000);

SELECT COUNT(*) FROM DAAS_RAW_EXACT_TARGET.ET_BOUNCES_EVENT_RAW;

SHOW STREAMS LIKE 'ET_BOUNCES_EVENT_STG_STREAM';

//ALTER TASK DAAS_COMMON.STG2RAW_ET_BOUNCES_EVENT_TASK RESUME;
//ALTER TASK DAAS_COMMON.STG2RAW_CD_ET_BOUNCES_EVENT_TASK RESUME;

ALTER TASK DAAS_COMMON.STG2RAW_ET_BOUNCES_EVENT_TASK RESUME;
ALTER TASK DAAS_COMMON.STG2RAW_CD_ET_BOUNCES_EVENT_TASK RESUME;

SELECT * FROM DAAS_STG_EXACT_TARGET.ET_BOUNCES_EVENT_STG_STREAM;
SELECT * FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG_STREAM;

EXECUTE TASK DAAS_COMMON.STG2RAW_ET_BOUNCES_EVENT_TASK;
EXECUTE TASK DAAS_COMMON.STG2RAW_CD_ET_BOUNCES_EVENT_TASK;

SELECT * FROM DAAS_COMMON.BATCH_S01 WHERE JOB_ID=931;
SELECT * FROM DAAS_COMMON.BATCH_METRICS_S01 WHERE BATCH_ID=5164694;
SELECT * FROM DAAS_COMMON.JOB WHERE JOB_NAME LIKE '%BOUNCES%';--931 ET 5164684,939 CD_ET 5164694
 
SELECT 'CD_ET_BOUNCES_EVENT_STG',COUNT(*) FROM DAAS_STG_EXACT_TARGET.CD_ET_BOUNCES_EVENT_STG
UNION 
SELECT 'CD_ET_BOUNCES_EVENT_RAW',COUNT(*) FROM DAAS_RAW_EXACT_TARGET.CD_ET_BOUNCES_EVENT_RAW;