CREATE TABLE "DAAS_TERADATA_RAW"."EB_SOURCE_DATA_ELEMENT_RAW"(
    I_SOURCE_DATA_ELEMENT_ID INTEGER      NOT NULL,
    C_SOURCE_DATA_ELEMENT    VARCHAR(512) NOT NULL,
    C_QUALITY_CD             VARCHAR(1)   NOT NULL,
    D_TIMESTAMP              DATETIME     NOT NULL
)
;