CREATE OR REPLACE VIEW DAAS_RAW_EBANK_VW.EB_SOURCE_DATA_ELEMENT_VW(
	SOURCE_DATA_ELEMENT_ID,
	SOURCE_DATA_ELEMENT,
	QUALITY_CD,
	SOURCE_TIMESTAMP,
	SOURCE_SYSTEM_NM,
	TIME_ZONE,
	CREATED_DTTM,
	CREATED_BY,
	UPDATED_DTTM,
	UPDATED_BY
) AS
SELECT
	I_SOURCE_DATA_ELEMENT_ID AS SOURCE_DATA_ELEMENT_ID,
	C_SOURCE_DATA_ELEMENT AS SOURCE_DATA_ELEMENT,
	C_QUALITY_CD AS QUALITY_CD,
	D_TIMESTAMP AS SOURCE_TIMESTAMP,
	'EBANK' AS SOURCE_SYSTEM_NM,
	'US/CENTRAL' AS TIME_ZONE,
	CURRENT_TIMESTAMP AS CREATED_DTTM,
	CURRENT_USER AS CREATED_BY,
	CURRENT_TIMESTAMP AS UPDATED_DTTM,
	CURRENT_USER AS UPDATED_BY
FROM
	DAAS_TERADATA_RAW.EB_SOURCE_DATA_ELEMENT_RAW;	
	
	