CREATE OR REPLACE TABLE DAAS_TERADATA_RAW.EB_GAMING_HOSPITALITY_RAW (
	I_GAMING_HOSPITALITY_ID NUMBER(38,0) NOT NULL,
	C_GAMING_HOSPITALITY VARCHAR(64),
	C_QUALITY_CD VARCHAR(1),
	D_TIMESTAMP TIMESTAMP_NTZ(9)
);