CREATE OR REPLACE TABLE DAAS_TERADATA_RAW.EB_SOURCE_DATA_ELEMENT_RAW (
	I_SOURCE_DATA_ELEMENT_ID NUMBER(38,0) NOT NULL,
	C_SOURCE_DATA_ELEMENT VARCHAR(512) NOT NULL,
	C_QUALITY_CD VARCHAR(1) NOT NULL,
	D_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL
);