CREATE OR REPLACE PROCEDURE DAAS_ADHOC.TRIP_METRICS_MISMATCHES_OFFER_ADHOC_REQUEST_PROC()
RETURNS VARCHAR NOT NULL
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$

/*
#############################################################################################################
Author: Hemanth
Purpose: This procedure will capture discrepancy guests from OFFER domain
Created Date: 08/30/2023
#############################################################################################################
*/

proc_output = "";
proc_step = "";

try
{
	snowflake.execute( {sqlText: "BEGIN;" } );

	/* Create temp table to store discrepancy Guests from TRIP_SUMMARY */
	
	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.OFFER_TS_DISCREPANCY_GUEST_IDS AS 
	SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_CASH_COST ELSE 0 END) AS PROP_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_CASH_COST ELSE 0 END) AS MKT_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_CASH_COST ELSE 0 END) AS ENT_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_HOTEL_COST ELSE 0 END) AS PROP_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_HOTEL_COST ELSE 0 END) AS MKT_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_HOTEL_COST ELSE 0 END) AS ENT_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_RC_COST ELSE 0 END) AS PROP_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_RC_COST ELSE 0 END) AS MKT_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_RC_COST ELSE 0 END) AS ENT_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_OTHER_COST ELSE 0 END) AS PROP_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_OTHER_COST ELSE 0 END) AS MKT_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_OTHER_COST ELSE 0 END) AS ENT_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_FSP_COST ELSE 0 END) AS PROP_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_FSP_COST ELSE 0 END) AS MKT_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_FSP_COST ELSE 0 END) AS ENT_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_TOTAL_COST ELSE 0 END) AS PROP_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_TOTAL_COST ELSE 0 END) AS MKT_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_TOTAL_COST ELSE 0 END) AS ENT_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS PROP_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS MKT_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS ENT_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS PROP_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS MKT_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS ENT_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS PROP_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS MKT_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS ENT_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS PROP_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS MKT_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS ENT_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_COST
FROM
	DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_OFFER_CASH_COST  <> MKT_OFFER_CASH_COST  OR MKT_OFFER_CASH_COST  <> ENT_OFFER_CASH_COST  OR ENT_OFFER_CASH_COST  <> PROP_OFFER_CASH_COST ) OR
( PROP_OFFER_HOTEL_COST  <> MKT_OFFER_HOTEL_COST  OR MKT_OFFER_HOTEL_COST  <> ENT_OFFER_HOTEL_COST  OR ENT_OFFER_HOTEL_COST  <> PROP_OFFER_HOTEL_COST ) OR
( PROP_OFFER_RC_COST  <> MKT_OFFER_RC_COST  OR MKT_OFFER_RC_COST  <> ENT_OFFER_RC_COST  OR ENT_OFFER_RC_COST  <> PROP_OFFER_RC_COST ) OR
( PROP_OFFER_OTHER_COST  <> MKT_OFFER_OTHER_COST  OR MKT_OFFER_OTHER_COST  <> ENT_OFFER_OTHER_COST  OR ENT_OFFER_OTHER_COST  <> PROP_OFFER_OTHER_COST ) OR
( PROP_OFFER_FSP_COST  <> MKT_OFFER_FSP_COST  OR MKT_OFFER_FSP_COST  <> ENT_OFFER_FSP_COST  OR ENT_OFFER_FSP_COST  <> PROP_OFFER_FSP_COST ) OR
( PROP_OFFER_TOTAL_COST  <> MKT_OFFER_TOTAL_COST  OR MKT_OFFER_TOTAL_COST  <> ENT_OFFER_TOTAL_COST  OR ENT_OFFER_TOTAL_COST  <> PROP_OFFER_TOTAL_COST ) OR
( PROP_OFFER_NBR_CASH_COUPONS  <> MKT_OFFER_NBR_CASH_COUPONS  OR MKT_OFFER_NBR_CASH_COUPONS  <> ENT_OFFER_NBR_CASH_COUPONS  OR ENT_OFFER_NBR_CASH_COUPONS  <> PROP_OFFER_NBR_CASH_COUPONS ) OR
( PROP_OFFER_NBR_HOTEL_COUPONS  <> MKT_OFFER_NBR_HOTEL_COUPONS  OR MKT_OFFER_NBR_HOTEL_COUPONS  <> ENT_OFFER_NBR_HOTEL_COUPONS  OR ENT_OFFER_NBR_HOTEL_COUPONS  <> PROP_OFFER_NBR_HOTEL_COUPONS ) OR
( PROP_OFFER_NBR_RC_COUPONS  <> MKT_OFFER_NBR_RC_COUPONS  OR MKT_OFFER_NBR_RC_COUPONS  <> ENT_OFFER_NBR_RC_COUPONS  OR ENT_OFFER_NBR_RC_COUPONS  <> PROP_OFFER_NBR_RC_COUPONS ) OR
( PROP_OFFER_NBR_OTHER_COUPONS  <> MKT_OFFER_NBR_OTHER_COUPONS  OR MKT_OFFER_NBR_OTHER_COUPONS  <> ENT_OFFER_NBR_OTHER_COUPONS  OR ENT_OFFER_NBR_OTHER_COUPONS  <> PROP_OFFER_NBR_OTHER_COUPONS ) OR
( PROP_OFFER_NBR_FSP_COUPONS  <> MKT_OFFER_NBR_FSP_COUPONS  OR MKT_OFFER_NBR_FSP_COUPONS  <> ENT_OFFER_NBR_FSP_COUPONS  OR ENT_OFFER_NBR_FSP_COUPONS  <> PROP_OFFER_NBR_FSP_COUPONS ) OR
( PROP_OFFER_NBR_TOTAL_COUPONS  <> MKT_OFFER_NBR_TOTAL_COUPONS  OR MKT_OFFER_NBR_TOTAL_COUPONS  <> ENT_OFFER_NBR_TOTAL_COUPONS  OR ENT_OFFER_NBR_TOTAL_COUPONS  <> PROP_OFFER_NBR_TOTAL_COUPONS ) OR
( PROP_OFFER_DM_REEL_REWARDS_COST  <> MKT_OFFER_DM_REEL_REWARDS_COST  OR MKT_OFFER_DM_REEL_REWARDS_COST  <> ENT_OFFER_DM_REEL_REWARDS_COST  OR ENT_OFFER_DM_REEL_REWARDS_COST <> PROP_OFFER_DM_REEL_REWARDS_COST ) OR
( PROP_OFFER_EMAIL_REEL_REWARDS_COST  <> MKT_OFFER_EMAIL_REEL_REWARDS_COST  OR MKT_OFFER_EMAIL_REEL_REWARDS_COST  <> ENT_OFFER_EMAIL_REEL_REWARDS_COST  OR ENT_OFFER_EMAIL_REEL_REWARDS_COST  <> PROP_OFFER_EMAIL_REEL_REWARDS_COST ) OR
( PROP_OFFER_NBR_DM_REEL_REWARDS  <> MKT_OFFER_NBR_DM_REEL_REWARDS  OR MKT_OFFER_NBR_DM_REEL_REWARDS  <> ENT_OFFER_NBR_DM_REEL_REWARDS  OR ENT_OFFER_NBR_DM_REEL_REWARDS  <> PROP_OFFER_NBR_DM_REEL_REWARDS ) OR
( PROP_OFFER_NBR_EMAIL_REEL_REWARDS  <> MKT_OFFER_NBR_EMAIL_REEL_REWARDS  OR MKT_OFFER_NBR_EMAIL_REEL_REWARDS  <> ENT_OFFER_NBR_EMAIL_REEL_REWARDS  OR ENT_OFFER_NBR_EMAIL_REEL_REWARDS  <> PROP_OFFER_NBR_EMAIL_REEL_REWARDS ) OR
( PROP_OFFER_CASH_REDEEM_AMT  <> MKT_OFFER_CASH_REDEEM_AMT  OR MKT_OFFER_CASH_REDEEM_AMT  <> ENT_OFFER_CASH_REDEEM_AMT  OR ENT_OFFER_CASH_REDEEM_AMT  <> PROP_OFFER_CASH_REDEEM_AMT ) OR
( PROP_OFFER_HOTEL_REDEEM_AMT  <> MKT_OFFER_HOTEL_REDEEM_AMT  OR MKT_OFFER_HOTEL_REDEEM_AMT  <> ENT_OFFER_HOTEL_REDEEM_AMT  OR ENT_OFFER_HOTEL_REDEEM_AMT  <> PROP_OFFER_HOTEL_REDEEM_AMT ) OR
( PROP_OFFER_RC_REDEEM_AMT  <> MKT_OFFER_RC_REDEEM_AMT  OR MKT_OFFER_RC_REDEEM_AMT  <> ENT_OFFER_RC_REDEEM_AMT  OR ENT_OFFER_RC_REDEEM_AMT  <> PROP_OFFER_RC_REDEEM_AMT ) OR
( PROP_OFFER_OTHER_REDEEM_AMT  <> MKT_OFFER_OTHER_REDEEM_AMT  OR MKT_OFFER_OTHER_REDEEM_AMT  <> ENT_OFFER_OTHER_REDEEM_AMT  OR ENT_OFFER_OTHER_REDEEM_AMT  <> PROP_OFFER_OTHER_REDEEM_AMT ) OR
( PROP_OFFER_FSP_REDEEM_AMT  <> MKT_OFFER_FSP_REDEEM_AMT  OR MKT_OFFER_FSP_REDEEM_AMT  <> ENT_OFFER_FSP_REDEEM_AMT  OR ENT_OFFER_FSP_REDEEM_AMT  <> PROP_OFFER_FSP_REDEEM_AMT ) OR
( PROP_OFFER_TOTAL_REDEEM_AMT  <> MKT_OFFER_TOTAL_REDEEM_AMT  OR MKT_OFFER_TOTAL_REDEEM_AMT  <> ENT_OFFER_TOTAL_REDEEM_AMT  OR ENT_OFFER_TOTAL_REDEEM_AMT  <> PROP_OFFER_TOTAL_REDEEM_AMT ) OR
( PROP_OFFER_DRAWING_OTP_NBR_ENTRIES  <> MKT_OFFER_DRAWING_OTP_NBR_ENTRIES  OR MKT_OFFER_DRAWING_OTP_NBR_ENTRIES  <> ENT_OFFER_DRAWING_OTP_NBR_ENTRIES  OR ENT_OFFER_DRAWING_OTP_NBR_ENTRIES  <> PROP_OFFER_DRAWING_OTP_NBR_ENTRIES ) OR
( PROP_OFFER_DRAWING_OTP_REDEEMED_AMT  <> MKT_OFFER_DRAWING_OTP_REDEEMED_AMT  OR MKT_OFFER_DRAWING_OTP_REDEEMED_AMT  <> ENT_OFFER_DRAWING_OTP_REDEEMED_AMT  OR ENT_OFFER_DRAWING_OTP_REDEEMED_AMT  <> PROP_OFFER_DRAWING_OTP_REDEEMED_AMT ) OR
( PROP_OFFER_DRAWING_OTP_COST  <> MKT_OFFER_DRAWING_OTP_COST  OR MKT_OFFER_DRAWING_OTP_COST  <> ENT_OFFER_DRAWING_OTP_COST  OR ENT_OFFER_DRAWING_OTP_COST  <> PROP_OFFER_DRAWING_OTP_COST );`});


	/* Create temp table to store discrepancy Guests from DAILY_ACTIVITY_SUMMARY */

	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.OFFER_DAS_DISCREPANCY_GUEST_IDS AS
	SELECT
	GUEST_UNIQUE_ID,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_CASH_COST ELSE 0 END) AS PROP_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_CASH_COST ELSE 0 END) AS MKT_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_CASH_COST ELSE 0 END) AS ENT_OFFER_CASH_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_HOTEL_COST ELSE 0 END) AS PROP_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_HOTEL_COST ELSE 0 END) AS MKT_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_HOTEL_COST ELSE 0 END) AS ENT_OFFER_HOTEL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_RC_COST ELSE 0 END) AS PROP_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_RC_COST ELSE 0 END) AS MKT_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_RC_COST ELSE 0 END) AS ENT_OFFER_RC_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_OTHER_COST ELSE 0 END) AS PROP_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_OTHER_COST ELSE 0 END) AS MKT_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_OTHER_COST ELSE 0 END) AS ENT_OFFER_OTHER_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_FSP_COST ELSE 0 END) AS PROP_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_FSP_COST ELSE 0 END) AS MKT_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_FSP_COST ELSE 0 END) AS ENT_OFFER_FSP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_TOTAL_COST ELSE 0 END) AS PROP_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_TOTAL_COST ELSE 0 END) AS MKT_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_TOTAL_COST ELSE 0 END) AS ENT_OFFER_TOTAL_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_CASH_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_CASH_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_HOTEL_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_HOTEL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_RC_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_RC_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_OTHER_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_OTHER_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_FSP_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_FSP_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS PROP_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS MKT_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_TOTAL_COUPONS ELSE 0 END) AS ENT_OFFER_NBR_TOTAL_COUPONS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS PROP_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS MKT_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DM_REEL_REWARDS_COST ELSE 0 END) AS ENT_OFFER_DM_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS PROP_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS MKT_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_EMAIL_REEL_REWARDS_COST ELSE 0 END) AS ENT_OFFER_EMAIL_REEL_REWARDS_COST,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS PROP_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS MKT_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_DM_REEL_REWARDS ELSE 0 END) AS ENT_OFFER_NBR_DM_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS PROP_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS MKT_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_NBR_EMAIL_REEL_REWARDS ELSE 0 END) AS ENT_OFFER_NBR_EMAIL_REEL_REWARDS,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_CASH_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_CASH_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_HOTEL_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_HOTEL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_RC_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_RC_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_OTHER_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_OTHER_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_FSP_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_FSP_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS PROP_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS MKT_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_TOTAL_REDEEM_AMT ELSE 0 END) AS ENT_OFFER_TOTAL_REDEEM_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_NBR_ENTRIES ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_NBR_ENTRIES,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_REDEEMED_AMT ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_REDEEMED_AMT,
	SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS PROP_OFFER_DRAWING_OTP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS MKT_OFFER_DRAWING_OTP_COST,
	SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN OFFER_DRAWING_OTP_COST ELSE 0 END) AS ENT_OFFER_DRAWING_OTP_COST
FROM
	DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW
WHERE
	GUEST_UNIQUE_ID <> -1
GROUP BY 
	GUEST_UNIQUE_ID
HAVING 
( PROP_OFFER_CASH_COST  <> MKT_OFFER_CASH_COST  OR MKT_OFFER_CASH_COST  <> ENT_OFFER_CASH_COST  OR ENT_OFFER_CASH_COST  <> PROP_OFFER_CASH_COST ) OR
( PROP_OFFER_HOTEL_COST  <> MKT_OFFER_HOTEL_COST  OR MKT_OFFER_HOTEL_COST  <> ENT_OFFER_HOTEL_COST  OR ENT_OFFER_HOTEL_COST  <> PROP_OFFER_HOTEL_COST ) OR
( PROP_OFFER_RC_COST  <> MKT_OFFER_RC_COST  OR MKT_OFFER_RC_COST  <> ENT_OFFER_RC_COST  OR ENT_OFFER_RC_COST  <> PROP_OFFER_RC_COST ) OR
( PROP_OFFER_OTHER_COST  <> MKT_OFFER_OTHER_COST  OR MKT_OFFER_OTHER_COST  <> ENT_OFFER_OTHER_COST  OR ENT_OFFER_OTHER_COST  <> PROP_OFFER_OTHER_COST ) OR
( PROP_OFFER_FSP_COST  <> MKT_OFFER_FSP_COST  OR MKT_OFFER_FSP_COST  <> ENT_OFFER_FSP_COST  OR ENT_OFFER_FSP_COST  <> PROP_OFFER_FSP_COST ) OR
( PROP_OFFER_TOTAL_COST  <> MKT_OFFER_TOTAL_COST  OR MKT_OFFER_TOTAL_COST  <> ENT_OFFER_TOTAL_COST  OR ENT_OFFER_TOTAL_COST  <> PROP_OFFER_TOTAL_COST ) OR
( PROP_OFFER_NBR_CASH_COUPONS  <> MKT_OFFER_NBR_CASH_COUPONS  OR MKT_OFFER_NBR_CASH_COUPONS  <> ENT_OFFER_NBR_CASH_COUPONS  OR ENT_OFFER_NBR_CASH_COUPONS  <> PROP_OFFER_NBR_CASH_COUPONS ) OR
( PROP_OFFER_NBR_HOTEL_COUPONS  <> MKT_OFFER_NBR_HOTEL_COUPONS  OR MKT_OFFER_NBR_HOTEL_COUPONS  <> ENT_OFFER_NBR_HOTEL_COUPONS  OR ENT_OFFER_NBR_HOTEL_COUPONS  <> PROP_OFFER_NBR_HOTEL_COUPONS ) OR
( PROP_OFFER_NBR_RC_COUPONS  <> MKT_OFFER_NBR_RC_COUPONS  OR MKT_OFFER_NBR_RC_COUPONS  <> ENT_OFFER_NBR_RC_COUPONS  OR ENT_OFFER_NBR_RC_COUPONS  <> PROP_OFFER_NBR_RC_COUPONS ) OR
( PROP_OFFER_NBR_OTHER_COUPONS  <> MKT_OFFER_NBR_OTHER_COUPONS  OR MKT_OFFER_NBR_OTHER_COUPONS  <> ENT_OFFER_NBR_OTHER_COUPONS  OR ENT_OFFER_NBR_OTHER_COUPONS  <> PROP_OFFER_NBR_OTHER_COUPONS ) OR
( PROP_OFFER_NBR_FSP_COUPONS  <> MKT_OFFER_NBR_FSP_COUPONS  OR MKT_OFFER_NBR_FSP_COUPONS  <> ENT_OFFER_NBR_FSP_COUPONS  OR ENT_OFFER_NBR_FSP_COUPONS  <> PROP_OFFER_NBR_FSP_COUPONS ) OR
( PROP_OFFER_NBR_TOTAL_COUPONS  <> MKT_OFFER_NBR_TOTAL_COUPONS  OR MKT_OFFER_NBR_TOTAL_COUPONS  <> ENT_OFFER_NBR_TOTAL_COUPONS  OR ENT_OFFER_NBR_TOTAL_COUPONS  <> PROP_OFFER_NBR_TOTAL_COUPONS ) OR
( PROP_OFFER_DM_REEL_REWARDS_COST  <> MKT_OFFER_DM_REEL_REWARDS_COST  OR MKT_OFFER_DM_REEL_REWARDS_COST  <> ENT_OFFER_DM_REEL_REWARDS_COST  OR ENT_OFFER_DM_REEL_REWARDS_COST  <> PROP_OFFER_DM_REEL_REWARDS_COST ) OR
( PROP_OFFER_EMAIL_REEL_REWARDS_COST  <> MKT_OFFER_EMAIL_REEL_REWARDS_COST  OR MKT_OFFER_EMAIL_REEL_REWARDS_COST  <> ENT_OFFER_EMAIL_REEL_REWARDS_COST  OR ENT_OFFER_EMAIL_REEL_REWARDS_COST  <> PROP_OFFER_EMAIL_REEL_REWARDS_COST ) OR
( PROP_OFFER_NBR_DM_REEL_REWARDS  <> MKT_OFFER_NBR_DM_REEL_REWARDS  OR MKT_OFFER_NBR_DM_REEL_REWARDS  <> ENT_OFFER_NBR_DM_REEL_REWARDS  OR ENT_OFFER_NBR_DM_REEL_REWARDS  <> PROP_OFFER_NBR_DM_REEL_REWARDS ) OR
( PROP_OFFER_NBR_EMAIL_REEL_REWARDS  <> MKT_OFFER_NBR_EMAIL_REEL_REWARDS  OR MKT_OFFER_NBR_EMAIL_REEL_REWARDS  <> ENT_OFFER_NBR_EMAIL_REEL_REWARDS  OR ENT_OFFER_NBR_EMAIL_REEL_REWARDS  <> PROP_OFFER_NBR_EMAIL_REEL_REWARDS ) OR
( PROP_OFFER_CASH_REDEEM_AMT  <> MKT_OFFER_CASH_REDEEM_AMT  OR MKT_OFFER_CASH_REDEEM_AMT  <> ENT_OFFER_CASH_REDEEM_AMT  OR ENT_OFFER_CASH_REDEEM_AMT  <> PROP_OFFER_CASH_REDEEM_AMT ) OR
( PROP_OFFER_HOTEL_REDEEM_AMT  <> MKT_OFFER_HOTEL_REDEEM_AMT  OR MKT_OFFER_HOTEL_REDEEM_AMT  <> ENT_OFFER_HOTEL_REDEEM_AMT  OR ENT_OFFER_HOTEL_REDEEM_AMT  <> PROP_OFFER_HOTEL_REDEEM_AMT ) OR
( PROP_OFFER_RC_REDEEM_AMT  <> MKT_OFFER_RC_REDEEM_AMT  OR MKT_OFFER_RC_REDEEM_AMT  <> ENT_OFFER_RC_REDEEM_AMT  OR ENT_OFFER_RC_REDEEM_AMT  <> PROP_OFFER_RC_REDEEM_AMT ) OR
( PROP_OFFER_OTHER_REDEEM_AMT  <> MKT_OFFER_OTHER_REDEEM_AMT  OR MKT_OFFER_OTHER_REDEEM_AMT  <> ENT_OFFER_OTHER_REDEEM_AMT  OR ENT_OFFER_OTHER_REDEEM_AMT  <> PROP_OFFER_OTHER_REDEEM_AMT ) OR
( PROP_OFFER_FSP_REDEEM_AMT  <> MKT_OFFER_FSP_REDEEM_AMT  OR MKT_OFFER_FSP_REDEEM_AMT  <> ENT_OFFER_FSP_REDEEM_AMT  OR ENT_OFFER_FSP_REDEEM_AMT  <> PROP_OFFER_FSP_REDEEM_AMT ) OR
( PROP_OFFER_TOTAL_REDEEM_AMT  <> MKT_OFFER_TOTAL_REDEEM_AMT  OR MKT_OFFER_TOTAL_REDEEM_AMT  <> ENT_OFFER_TOTAL_REDEEM_AMT  OR ENT_OFFER_TOTAL_REDEEM_AMT  <> PROP_OFFER_TOTAL_REDEEM_AMT ) OR
( PROP_OFFER_DRAWING_OTP_NBR_ENTRIES  <> MKT_OFFER_DRAWING_OTP_NBR_ENTRIES  OR MKT_OFFER_DRAWING_OTP_NBR_ENTRIES  <> ENT_OFFER_DRAWING_OTP_NBR_ENTRIES  OR ENT_OFFER_DRAWING_OTP_NBR_ENTRIES  <> PROP_OFFER_DRAWING_OTP_NBR_ENTRIES ) OR
( PROP_OFFER_DRAWING_OTP_REDEEMED_AMT  <> MKT_OFFER_DRAWING_OTP_REDEEMED_AMT  OR MKT_OFFER_DRAWING_OTP_REDEEMED_AMT  <> ENT_OFFER_DRAWING_OTP_REDEEMED_AMT  OR ENT_OFFER_DRAWING_OTP_REDEEMED_AMT  <> PROP_OFFER_DRAWING_OTP_REDEEMED_AMT ) OR
( PROP_OFFER_DRAWING_OTP_COST  <> MKT_OFFER_DRAWING_OTP_COST  OR MKT_OFFER_DRAWING_OTP_COST  <> ENT_OFFER_DRAWING_OTP_COST  OR ENT_OFFER_DRAWING_OTP_COST  <> PROP_OFFER_DRAWING_OTP_COST );` } );	
	
	
	/* Combine both temp tables and get distinct Guests */
	
	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.OFFER_DISCREPANCY_GUEST_IDS AS
	SELECT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFER_TS_DISCREPANCY_GUEST_IDS
	UNION
	SELECT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFER_DAS_DISCREPANCY_GUEST_IDS
	;` } );	
	

	snowflake.execute( {sqlText: "COMMIT;" } );

	proc_output = "SUCCESS";
}	

catch (err) 
{ 
snowflake.execute( {sqlText: "ROLLBACK;" } );

proc_output += "\n Failed: Code: " + err.code + "\n  State: " + err.state;
proc_output += "\n  Message: " + err.message;
proc_output += "\nStack Trace:\n" + err.stackTraceTxt;
}
 
return proc_output;
$$;