CREATE TABLE "DAAS_TERADATA_RAW"."EB_GAMING_HOSPITALITY_RAW"
(     I_GAMING_HOSPITALITY_ID NUMBER NOT NULL,
      C_GAMING_HOSPITALITY VARCHAR(64),
      C_QUALITY_CD CHAR(1),
       D_TIMESTAMP TIMESTAMP_NTZ(9));
	   