CREATE OR REPLACE VIEW DAAS_RAW_EBANK_VW.EB_GAMING_HOSPITALITY_VW(
	GAMING_HOSPITALITY_ID,
	GAMING_HOSPITALITY,
	QUALITY_CD,
	SOURCE_TIMESTAMP,
	SOURCE_SYSTEM_NM,
	TIME_ZONE,
	CREATED_DTTM,
	CREATED_BY,
	UPDATED_DTTM,
	UPDATED_BY
) AS
SELECT
	I_GAMING_HOSPITALITY_ID AS GAMING_HOSPITALITY_ID,
	C_GAMING_HOSPITALITY AS GAMING_HOSPITALITY,
	C_QUALITY_CD AS QUALITY_CD,
	D_TIMESTAMP AS SOURCE_TIMESTAMP,
	'EBANK' AS SOURCE_SYSTEM_NM,
	'US/CENTRAL' AS TIME_ZONE,
	CURRENT_TIMESTAMP AS CREATED_DTTM,
	CURRENT_USER AS CREATED_BY,
	CURRENT_TIMESTAMP AS UPDATED_DTTM,
	CURRENT_USER AS UPDATED_BY
FROM
	DAAS_TERADATA_RAW.EB_GAMING_HOSPITALITY_RAW;	