SELECT * FROM "DAAS_DEV"."DAAS_TERADATA_RAW"."EB_SOURCE_DATA_ELEMENT_RAW";--168

SELECT * FROM "DAAS_DEV"."DAAS_TERADATA_RAW"."EB_GAMING_HOSPITALITY_RAW";--2

SELECT GET_DDL('VIEW','DAAS_RAW_EBANK_VW.EB_SOURCE_DATA_ELEMENT_VW');

SELECT GET_DDL('VIEW','DAAS_TERADATA_RAW.EB_TRANSACTION_TYPE_RAW');

SELECT * FROM DAAS_RAW_EBANK_VW.EB_ACTIVITY_TYPE_VW;

SELECT DISTINCT GAMING_HOSPITALITY_ID,GAMING_HOSPITALITY_TYPE 
FROM DAAS_CORE.FUND_TRANSACTION_DETAIL_FACT;

SELECT * FROM DAAS_CORE.FUND_TRANSACTION_DETAIL_FACT LIMIT 10;

SELECT DISTINCT SOURCE_DATA_TYPE_KEY FROM DAAS_CORE.FUND_TRANSACTION_SOURCE_DATA_FACT;

CREATE OR REPLACE VIEW DAAS_RAW_EBANK_VW.EB_GAMING_HOSPITALITY_VW(
	GAMING_HOSPITALITY_ID,
	GAMING_HOSPITALITY,
	QUALITY_CD,
	SOURCE_TIMESTAMP,
	SOURCE_SYSTEM_NM,
	TIME_ZONE,
	CREATED_DTTM,
	CREATED_BY,
	UPDATED_DTTM,
	UPDATED_BY
) AS
SELECT
	I_GAMING_HOSPITALITY_ID AS GAMING_HOSPITALITY_ID,
	C_GAMING_HOSPITALITY AS GAMING_HOSPITALITY,
	C_QUALITY_CD AS QUALITY_CD,
	D_TIMESTAMP AS SOURCE_TIMESTAMP,
	'EBANK' AS SOURCE_SYSTEM_NM,
	'US/CENTRAL' AS TIME_ZONE,
	CURRENT_TIMESTAMP AS CREATED_DTTM,
	CURRENT_USER AS CREATED_BY,
	CURRENT_TIMESTAMP AS UPDATED_DTTM,
	CURRENT_USER AS UPDATED_BY
FROM
	DAAS_TERADATA_RAW.EB_GAMING_HOSPITALITY_RAW;

CREATE OR REPLACE VIEW DAAS_RAW_EBANK_VW.EB_SOURCE_DATA_ELEMENT_VW(
	SOURCE_DATA_ELEMENT_ID,
	SOURCE_DATA_ELEMENT,
	QUALITY_CD,
	SOURCE_TIMESTAMP,
	SOURCE_SYSTEM_NM,
	TIME_ZONE,
	CREATED_DTTM,
	CREATED_BY,
	UPDATED_DTTM,
	UPDATED_BY
) AS
SELECT
	I_SOURCE_DATA_ELEMENT_ID AS SOURCE_DATA_ELEMENT_ID,
	C_SOURCE_DATA_ELEMENT AS SOURCE_DATA_ELEMENT,
	C_QUALITY_CD AS QUALITY_CD,
	D_TIMESTAMP AS SOURCE_TIMESTAMP,
	'EBANK' AS SOURCE_SYSTEM_NM,
	'US/CENTRAL' AS TIME_ZONE,
	CURRENT_TIMESTAMP AS CREATED_DTTM,
	CURRENT_USER AS CREATED_BY,
	CURRENT_TIMESTAMP AS UPDATED_DTTM,
	CURRENT_USER AS UPDATED_BY
FROM
	DAAS_TERADATA_RAW.EB_SOURCE_DATA_ELEMENT_RAW;
    
SHOW VIEWS LIKE '%EB_GAMING_HOSPITALITY_VW%' IN DAAS_RAW_EBANK_VW;

SHOW VIEWS LIKE '%EB_SOURCE_DATA_ELEMENT_VW%' IN DAAS_RAW_EBANK_VW;

SELECT DISTINCT GAMING_HOSPITALITY 
FROM DAAS_RAW_EBANK_VW.EB_GAMING_HOSPITALITY_VW;

SELECT * FROM DAAS_RAW_EBANK_VW.EB_SOURCE_DATA_ELEMENT_VW;

SELECT DISTINCT SOURCE_DATA_ELEMENT 
FROM DAAS_RAW_EBANK_VW.EB_SOURCE_DATA_ELEMENT_VW;

SELECT 'EB_GAMING_HOSPITALITY_RAW',COUNT(*) AS TABLE_COUNT FROM DAAS_TERADATA_RAW.EB_GAMING_HOSPITALITY_RAW
UNION 
SELECT 'EB_GAMING_HOSPITALITY_VW',COUNT(*) AS TABLE_COUNT FROM DAAS_RAW_EBANK_VW.EB_GAMING_HOSPITALITY_VW;

SELECT 'EB_SOURCE_DATA_ELEMENT_RAW',COUNT(*) AS TABLE_COUNT FROM DAAS_TERADATA_RAW.EB_SOURCE_DATA_ELEMENT_RAW
UNION 
SELECT 'EB_SOURCE_DATA_ELEMENT_VW',COUNT(*) AS TABLE_COUNT FROM DAAS_RAW_EBANK_VW.EB_SOURCE_DATA_ELEMENT_VW;

SELECT DISTINCT GAMING_HOSPITALITY_TYPE FROM DAAS_CORE.FUND_TRANSACTION_DETAIL_FACT
MINUS 
SELECT DISTINCT C_GAMING_HOSPITALITY FROM DAAS_TERADATA_RAW.EB_GAMING_HOSPITALITY_RAW;

SELECT GAMING_HOSPITALITY_ID,GAMING_HOSPITALITY_TYPE,* 
FROM DAAS_CORE.FUND_TRANSACTION_DETAIL_FACT
WHERE GAMING_HOSPITALITY_TYPE='Gaming' LIMIT 10;

SELECT * FROM DAAS_TERADATA_RAW.EB_GAMING_HOSPITALITY_RAW
WHERE C_GAMING_HOSPITALITY='Gaming';

SELECT DISTINCT GAMING_HOSPITALITY_ID,GAMING_HOSPITALITY_TYPE 
FROM DAAS_CORE.FUND_TRANSACTION_DETAIL_FACT;

SELECT DISTINCT UPPER(SOURCE_DATA_TYPE_KEY) FROM DAAS_CORE.FUND_TRANSACTION_SOURCE_DATA_FACT
MINUS 
SELECT DISTINCT UPPER(C_SOURCE_DATA_ELEMENT) FROM DAAS_TERADATA_RAW.EB_SOURCE_DATA_ELEMENT_RAW;--10