CREATE OR REPLACE PROCEDURE DAAS_ADHOC.TRIP_METRICS_MISMATCHES_FREEPLAY_ADHOC_REQUEST_PROC()
RETURNS VARCHAR NOT NULL
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$

/*
#############################################################################################################
Author: Priyanka P
Purpose: This procedure will capture discrepancy guests from Freeplay domain
Created Date: 08/30/2023
#############################################################################################################
*/

proc_output = "";
proc_step = "";

try
{
	snowflake.execute( {sqlText: "BEGIN;" } );

	/* Create temp table to store discrepancy Guests from TRIP_SUMMARY */
	
	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.FREEPLAY_TS_DISCREPANCY_GUEST_IDS AS 
	WITH ABS_LOGIC AS
(
	SELECT
		TD.TRIP_MASTER_ID,
		COALESCE(SUM(CASE WHEN TD.DELETE_IND = 'N' THEN FREE_PLAY_POINTS END),0) AS DLC_FSP_POINT_AMT_LOGIC,
		CASE WHEN DLC_FSP_POINT_AMT_LOGIC <0 THEN -1 ELSE 1 END SIGN
	FROM
		DAAS_CORE.TRIP_DETAIL TD
	JOIN 
		DAAS_CORE.TRIP_MASTER TM 
	ON
		TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
	JOIN
		DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
	ON
		TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
	WHERE
		TD.TRANSACTION_TYPE = 'FREEPLAY'
	AND 
		TM.DELETE_IND = 'N'
	GROUP BY
		TD.TRIP_MASTER_ID
	)
	SELECT
		GUEST_UNIQUE_ID,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_POINT_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_POINT_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_POINT_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_POINT_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS PROPERTY_DLC_FSP_DOLLAR_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'MARKET' AND MARKET_CD <> 'CH2' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS MARKET_DLC_FSP_DOLLAR_AMT,
		ABS(SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN TS.DLC_FSP_DOLLAR_AMT * AL.SIGN ELSE 0 END)) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
	FROM 
		DAAS_CORE_MARKETING_VW.TRIP_SUMMARY_VW TS
	JOIN 
		ABS_LOGIC AL
	ON 
		TS.TRIP_MASTER_ID = AL.TRIP_MASTER_ID 
	AND 
		DLC_FSP_FLG = 'Y'
	AND TS.GUEST_UNIQUE_ID <> -1
	GROUP BY GUEST_UNIQUE_ID
	HAVING 
	(PROPERTY_DLC_FSP_POINT_AMT<>MARKET_DLC_FSP_POINT_AMT OR MARKET_DLC_FSP_POINT_AMT<>ENTERPRISE_DLC_FSP_POINT_AMT OR PROPERTY_DLC_FSP_POINT_AMT<>ENTERPRISE_DLC_FSP_POINT_AMT)
	OR 
	(PROPERTY_DLC_FSP_DOLLAR_AMT<>MARKET_DLC_FSP_DOLLAR_AMT OR MARKET_DLC_FSP_DOLLAR_AMT<>ENTERPRISE_DLC_FSP_DOLLAR_AMT OR PROPERTY_DLC_FSP_DOLLAR_AMT<>ENTERPRISE_DLC_FSP_DOLLAR_AMT)
	` } );


	/* Create temp table to store discrepancy Guests from DAILY_ACTIVITY_SUMMARY */

	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.FREEPLAY_DAS_DISCREPANCY_GUEST_IDS AS
	WITH FREEPLAY_TRIP_DAYS AS
(
    SELECT
        TM.TRIP_MASTER_ID,
        DD.DATE AS GUEST_ACTIVITY_DATE
    FROM
        DAAS_CORE.TRIP_MASTER TM
    JOIN
        DAAS_COMMON.DATE_DIM DD
     ON
        DD.DATE BETWEEN TM.TRIP_START_DT AND TM.TRIP_END_DT
     WHERE
        TM.DELETE_IND = 'N'
    
     AND TM.MARKET_CD <> 'CH2'
        GROUP BY
            TM.TRIP_MASTER_ID,
            GUEST_ACTIVITY_DATE
),
	TRIP_GUEST_FREEPLAY AS 
	(
	SELECT
		TM.TRIP_MASTER_ID,
		GUEST_UNIQUE_ID,
		FREEPLAY_TRIP_DAYS.GUEST_ACTIVITY_DATE,
		CASE WHEN SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN  FREE_PLAY_POINTS ELSE 0 END)<0 THEN -1 ELSE 1 END AS PROPERTY_SIGN,
		CASE WHEN SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN  FREE_PLAY_POINTS ELSE 0 END)<0 THEN -1 ELSE 1 END AS MARKET_SIGN,
		CASE WHEN SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN FREE_PLAY_POINTS ELSE 0 END)<0 THEN -1 ELSE 1 END AS ENTERPRISE_SIGN
	FROM
		DAAS_CORE.TRIP_DETAIL TD
	JOIN 
		DAAS_CORE.TRIP_MASTER TM 
	ON
		TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
	JOIN
		DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT CFPDF
	ON
		TD.TRANSACTION_TABLE_SK = CFPDF.COMP_FREE_PLAY_DETAIL_FACT_SK
	JOIN 
		FREEPLAY_TRIP_DAYS
	ON
		FREEPLAY_TRIP_DAYS.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
		AND FREEPLAY_TRIP_DAYS.GUEST_ACTIVITY_DATE = TD.BUSINESS_START_DT
	WHERE
		TD.TRANSACTION_TYPE = 'FREEPLAY'
	AND 
		TM.DELETE_IND = 'N'
	AND TD.DELETE_IND = 'N'
	AND TM.MARKET_CD <> 'CH2'
	AND GUEST_UNIQUE_ID <> -1
	GROUP BY
		TM.TRIP_MASTER_ID,
		GUEST_UNIQUE_ID,
		FREEPLAY_TRIP_DAYS.GUEST_ACTIVITY_DATE
	)
	SELECT 
		DAS.GUEST_UNIQUE_ID,
		DAS.GUEST_ACTIVITY_DATE,
		SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN  DLC_FSP_POINT_AMT*PROPERTY_SIGN ELSE 0 END) AS PROPERTY_DLC_FSP_POINT_AMT,
		SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN  DLC_FSP_POINT_AMT*MARKET_SIGN ELSE 0 END) AS MARKET_DLC_FSP_POINT_AMT,
		SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN  DLC_FSP_POINT_AMT*ENTERPRISE_SIGN ELSE 0 END) AS ENTERPRISE_DLC_FSP_POINT_AMT,
		SUM(CASE WHEN TRIP_TYPE = 'PROPERTY' THEN  DLC_FSP_DOLLAR_AMT*PROPERTY_SIGN ELSE 0 END) AS PROPERTY_DLC_FSP_DOLLAR_AMT,
		SUM(CASE WHEN TRIP_TYPE = 'MARKET' THEN  DLC_FSP_DOLLAR_AMT*MARKET_SIGN ELSE 0 END) AS MARKET_DLC_FSP_DOLLAR_AMT,
		SUM(CASE WHEN TRIP_TYPE = 'ENTERPRISE' THEN  DLC_FSP_DOLLAR_AMT*ENTERPRISE_SIGN ELSE 0 END) AS ENTERPRISE_DLC_FSP_DOLLAR_AMT
	FROM 
		DAAS_CORE_MARKETING_VW.DAILY_ACTIVITY_SUMMARY_VW DAS
	JOIN 
		TRIP_GUEST_FREEPLAY TGF
	ON 
		DAS.TRIP_MASTER_ID = TGF.TRIP_MASTER_ID
	AND DAS.GUEST_ACTIVITY_DATE = TGF.GUEST_ACTIVITY_DATE
	GROUP BY 
		DAS.GUEST_UNIQUE_ID,
		DAS.GUEST_ACTIVITY_DATE
	HAVING 
	(PROPERTY_DLC_FSP_POINT_AMT<>MARKET_DLC_FSP_POINT_AMT OR MARKET_DLC_FSP_POINT_AMT<>ENTERPRISE_DLC_FSP_POINT_AMT OR PROPERTY_DLC_FSP_POINT_AMT<>ENTERPRISE_DLC_FSP_POINT_AMT)
	OR 
	(PROPERTY_DLC_FSP_DOLLAR_AMT<>MARKET_DLC_FSP_DOLLAR_AMT OR MARKET_DLC_FSP_DOLLAR_AMT<>ENTERPRISE_DLC_FSP_DOLLAR_AMT OR PROPERTY_DLC_FSP_DOLLAR_AMT<>ENTERPRISE_DLC_FSP_DOLLAR_AMT)
		;` } );	
	
	
	/* Combine both temp tables and get distinct Guests */
	
	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.FREEPLAY_DISCREPANCY_GUEST_IDS AS
	SELECT GUEST_UNIQUE_ID FROM DAAS_TEMP.FREEPLAY_TS_DISCREPANCY_GUEST_IDS
	UNION
	SELECT GUEST_UNIQUE_ID FROM DAAS_TEMP.FREEPLAY_DAS_DISCREPANCY_GUEST_IDS
	;` } );	
	

	snowflake.execute( {sqlText: "COMMIT;" } );

	proc_output = "SUCCESS";
}	

catch (err) 
{ 
	snowflake.execute( {sqlText: "ROLLBACK;" } );
	
	proc_output += "\n Failed: Code: " + err.code + "\n  State: " + err.state;
	proc_output += "\n  Message: " + err.message;
	proc_output += "\nStack Trace:\n" + err.stackTraceTxt;
}
 
return proc_output;
$$;