-----------------------------------------DEV----------------------------------------------------------------
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 885 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_FILTERED_TXNS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 629 ORDER BY BATCH_ID DESC LIMIT 5; -- RATINGS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 713 ORDER BY BATCH_ID DESC LIMIT 5; -- HOTEL
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 712 ORDER BY BATCH_ID DESC LIMIT 5; -- POS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 764 ORDER BY BATCH_ID DESC LIMIT 5; -- OFFER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 767 ORDER BY BATCH_ID DESC LIMIT 5; -- COMP
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 731 ORDER BY BATCH_ID DESC LIMIT 5; -- MARKERS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 720 ORDER BY BATCH_ID DESC LIMIT 5; -- FREEPLAY
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 636 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_RECALCULATION
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 688 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE_CHECK
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 691 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 696 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_GUEST_GUESTXREF
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 702 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_TRIP_MASTER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 697 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 722 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_SUMMARY_WRAPPER

---------------------------------------------------------------------------------------------------------------------------
-----------------------------------------UAT----------------------------------------------------------------
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 731 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_FILTERED_TXNS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 525 ORDER BY BATCH_ID DESC LIMIT 5; -- RATINGS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 637 ORDER BY BATCH_ID DESC LIMIT 5; -- HOTEL
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 638 ORDER BY BATCH_ID DESC LIMIT 5; -- POS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 657 ORDER BY BATCH_ID DESC LIMIT 5; -- OFFER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 656 ORDER BY BATCH_ID DESC LIMIT 5; -- COMP
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 654 ORDER BY BATCH_ID DESC LIMIT 5; -- MARKERS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 653 ORDER BY BATCH_ID DESC LIMIT 5; -- FREEPLAY
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 523 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_RECALCULATION
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 526 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE_CHECK
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 527 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 528 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_GUEST_GUESTXREF
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 532 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_TRIP_MASTER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 529 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 655 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_SUMMARY_WRAPPER


---------------------------------------------------------------------------------------------------------------------------
-----------------------------------------PROD----------------------------------------------------------------
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 583  ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_FILTERED_TXNS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 558 ORDER BY BATCH_ID DESC LIMIT 5; -- RATINGS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 566 ORDER BY BATCH_ID DESC LIMIT 5; -- HOTEL
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 567 ORDER BY BATCH_ID DESC LIMIT 5; -- POS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 579 ORDER BY BATCH_ID DESC LIMIT 5; -- OFFER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 580 ORDER BY BATCH_ID DESC LIMIT 5; -- COMP
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 581 ORDER BY BATCH_ID DESC LIMIT 5; -- MARKERS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 582 ORDER BY BATCH_ID DESC LIMIT 5; -- FREEPLAY
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 556 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_RECALCULATION
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 559 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE_CHECK
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 560 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 564 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_GUEST_GUESTXREF
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 561 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_TRIP_MASTER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 562 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 578 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_SUMMARY_WRAPPER

-------------------------------------------------------------------------------------------------
---------------------------------------CHECK TASK STATUS------------------------------------------
select *
from table(information_schema.task_history(
scheduled_time_range_start=>dateadd('hour',-1,current_timestamp()),
result_limit => 10,
task_name=>'TRIP_ROOT_TASK'));

------CHECK WAREHOUSE RUNNING WHICH QUERY
SELECT * FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_WAREHOUSE(WAREHOUSE_NAME=>'DAAS_UAT_IT_WHSRCTORAW_COMPUTE')) 
WHERE USER_NAME = 'SYSTEM' 
ORDER BY START_TIME DESC;

-------STREAM
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'RATINGS_FACT', 'DAAS_CORE', 'RATINGS_FACT_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT', 'DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'HOTEL_FOLIO_DETAIL_FACT', 'DAAS_CORE', 'HOTEL_FOLIO_DETAIL_FACT_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'CHECK_SALES_FACT', 'DAAS_CORE', 'CHECK_SALES_FACT_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'CHECK_ATTRIBUTE_DIM', 'DAAS_CORE', 'CHECK_ATTRIBUTE_DIM_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'CHECK_ITEM_FACT', 'DAAS_CORE', 'CHECK_ITEM_FACT_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'CHECK_TENDER_FACT', 'DAAS_CORE', 'CHECK_TENDER_FACT_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE_MARKETING_VW', 'OFFER_LEDGER_FACT_TRIP_VW', 'DAAS_CORE', 'OFFER_LEDGER_FACT_TRIP_STREAM', NULL);
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'COMP_DETAIL_FACT', 'DAAS_CORE', 'COMP_DETAIL_FACT_COMP_DOMAIN_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'COMP_FREE_PLAY_DETAIL_FACT', 'DAAS_CORE', 'COMP_FREE_PLAY_DETAIL_FACT_COMP_DOMAIN_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'CAGE_TRANSACTION_ISSUE_DETAIL_FACT', 'DAAS_CORE', 'CAGE_TRANSACTION_ISSUE_DETAIL_FACT_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'COMP_FREE_PLAY_DETAIL_FACT', 'DAAS_CORE', 'COMP_FREE_PLAY_DETAIL_FACT_FP_DOMAIN_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'COMP_DETAIL_FACT', 'DAAS_CORE', 'COMP_DETAIL_FACT_FP_DOMAIN_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'DIGITAL_TRANSACTIONS_FACT', 'DAAS_CORE', 'DIGITAL_TRANSACTIONS_FACT_TRIP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_RECALC_QUEUE', 'DAAS_CORE', 'TRIP_RECALC_QUEUE_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_MERGE_QUEUE', 'DAAS_CORE', 'TRIP_MERGE_QUEUE_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'GUEST_XREF_BRIDGE_LKP', 'DAAS_CORE', 'GUEST_XREF_BRIDGE_LKP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'GUEST_DIM', 'DAAS_CORE', 'GUEST_DIM_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_MASTER', 'DAAS_TEMP', 'TRIP_MASTER_TRIP_MERGE_CHECK_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_MASTER', 'DAAS_CORE', 'TRIP_MASTER_TRIP_CUSTOMER_MERGE_CHECK_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_MASTER', 'DAAS_CORE', 'TRIP_MASTER_DAILY_SUMMARY_WRAPPER_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_CUSTOMER_MERGE_QUEUE', 'DAAS_CORE', 'TRIP_CUSTOMER_MERGE_QUEUE_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'POS_COMP_TENDER_LKP', 'DAAS_CORE', 'POS_COMP_TENDER_LKP_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_CORE', 'TRIP_DETAIL', 'DAAS_CORE', 'TRIP_DETAIL_SUMMARY_STREAM', NULL );
CALL DAAS_COMMON.CREATE_OR_REPLACE_STREAM('DAAS_TEMP', 'TRIP_INACTIVE_TXNS_ARCHIVAL_TEMP', 'DAAS_CORE', 'TRIP_INACTIVE_TXNS_ARCHIVAL_STREAM', NULL );

SELECT COUNT(*) FROM DAAS_CORE.RATINGS_FACT_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.HOTEL_GUEST_RESERVATIONS_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.HOTEL_FOLIO_DETAIL_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.CHECK_SALES_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.CHECK_ATTRIBUTE_DIM_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.CHECK_ITEM_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.CHECK_TENDER_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.OFFER_LEDGER_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.COMP_DETAIL_FACT_COMP_DOMAIN_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT_COMP_DOMAIN_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.CAGE_TRANSACTION_ISSUE_DETAIL_FACT_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT_FP_DOMAIN_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.COMP_DETAIL_FACT_FP_DOMAIN_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.DIGITAL_TRANSACTIONS_FACT_TRIP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_RECALC_QUEUE_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_MERGE_QUEUE_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.GUEST_XREF_BRIDGE_LKP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.GUEST_DIM_STREAM;
SELECT COUNT(*) FROM DAAS_TEMP.TRIP_MASTER_TRIP_MERGE_CHECK_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_MASTER_TRIP_CUSTOMER_MERGE_CHECK_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_MASTER_DAILY_SUMMARY_WRAPPER_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_CUSTOMER_MERGE_QUEUE_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.POS_COMP_TENDER_LKP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.POS_COMP_TENDER_LKP_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_INACTIVE_TXNS_ARCHIVAL_STREAM;
SELECT COUNT(*) FROM DAAS_CORE.TRIP_DETAIL_SUMMARY_STREAM;


