SELECT * FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY  DAS
JOIN DAAS_CORE.TRIP_MASTER TM
ON DAS.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
WHERE PROPERTY_LST IS NULL
AND TM.DELETE_IND='N'
AND DAS.DELETE_IND='N' LIMIT 10;

SELECT COUNT(*) FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY;--1199921858

SELECT * FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
WHERE GUEST_UNIQUE_ID = 17000046263
AND GUEST_ACTIVITY_DATE ='2019-03-27';

SELECT TOP 10 * FROM DAAS_DATA_OPS_VW.DAILY_SUMMARY_VW 
WHERE PROPERTY_LST IS NULL 
AND TRIP_MASTER_ID <> -1;

SELECT 'B&M TRIP',COUNT(*) FROM DAAS_DATA_OPS_VW.DAILY_SUMMARY_VW 
WHERE PROPERTY_LST IS NULL 
AND TRIP_MASTER_ID <> -1
UNION
SELECT 'DIGITAL',COUNT(*) FROM DAAS_DATA_OPS_VW.DAILY_SUMMARY_VW 
WHERE PROPERTY_LST IS NULL 
AND TRIP_MASTER_ID = -1;

SELECT DAS.GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY  DAS
JOIN DAAS_CORE.TRIP_MASTER TM
ON DAS.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
WHERE TM.DELETE_IND='N'
AND DAS.DELETE_IND='Y'
AND DAS.TRIP_MASTER_ID <> -1;

SELECT COUNT(*) FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY  DAS
JOIN DAAS_CORE.TRIP_MASTER TM
ON DAS.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
WHERE TM.DELETE_IND='N'
AND DAS.DELETE_IND='Y'
AND DAS.TRIP_MASTER_ID <> -1
AND DAS.GUEST_ACTIVITY_DATE BETWEEN TM.TRIP_START_DT AND TM.TRIP_END_DT;