--•	How many check-ins happen daily/monthly/annually? (By property if possible – high level numbers are fine).
--ANNUALY
SELECT YEAR(ARRIVAL_DT),PROPERTY_CD,COUNT(GUEST_UNIQUE_ID) 
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW
WHERE YEAR(ARRIVAL_DT) BETWEEN 2018 AND 2024
GROUP BY 1,2
ORDER BY 1,2;

--MONTHLY
SELECT YEAR(ARRIVAL_DT),MONTH(ARRIVAL_DT),PROPERTY_CD,COUNT(GUEST_UNIQUE_ID) 
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW
WHERE YEAR(ARRIVAL_DT) BETWEEN 2018 AND 2024
GROUP BY 1,2,3
ORDER BY 1,2,3;

--DAILY
SELECT ARRIVAL_DT,PROPERTY_CD,COUNT(GUEST_UNIQUE_ID) 
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW
WHERE YEAR(ARRIVAL_DT) BETWEEN 2018 AND 2024
GROUP BY 1,2 
ORDER BY 1,2;

--•	How often do multi-room check-in versus single-room check-in happen?
WITH SINGLE_ROOM AS (
SELECT ARRIVAL_DT,PROPERTY_CD,COUNT(*) SR
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW
WHERE YEAR(ARRIVAL_DT) BETWEEN 2018 AND 2024
AND NUMBER_OF_ROOMS = 1
AND GUEST_UNIQUE_ID <> 0
GROUP BY 1,2),
MULTI_ROOM AS (
SELECT ARRIVAL_DT,PROPERTY_CD,COUNT(*) MR
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW
WHERE YEAR(ARRIVAL_DT) BETWEEN 2018 AND 2024
AND NUMBER_OF_ROOMS > 1
AND GUEST_UNIQUE_ID <> 0
GROUP BY 1,2)
SELECT SINGLE_ROOM.ARRIVAL_DT,SINGLE_ROOM.PROPERTY_CD,SR,MR
FROM SINGLE_ROOM
JOIN MULTI_ROOM
ON SINGLE_ROOM.ARRIVAL_DT = MULTI_ROOM.ARRIVAL_DT
AND SINGLE_ROOM.PROPERTY_CD = MULTI_ROOM.PROPERTY_CD;