UPDATE DAAS_CORE.RATINGS_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE RATINGS_FACT_SK IN 
(SELECT RATINGS_FACT_SK FROM DAAS_CORE_GAMING_VW.RATINGS_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.HOTEL_GUEST_RESERVATIONS_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE HOTEL_GUEST_RESERVATIONS_FACT_SK IN 
(SELECT HOTEL_GUEST_RESERVATIONS_FACT_SK FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.CHECK_SALES_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE CHECK_SALES_SK IN (
SELECT CHECK_SALES_SK FROM DAAS_CORE_POS_VW.CHECK_SALES_FACT_VW
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.OFFER_LEDGER_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE OFFER_LEDGER_FACT_SK IN 
(SELECT OFFER_LEDGER_FACT_SK FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_GUEST_UNIQUE_ID_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.OFFER_LEDGER_FACT_HISTORY
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE OFFER_LEDGER_FACT_SK IN 
(SELECT OFFER_LEDGER_FACT_SK FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_GUEST_UNIQUE_ID_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.COMP_DETAIL_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE COMP_DETAIL_FACT_SK IN 
(SELECT COMP_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.COMP_DETAIL_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.CAGE_TRANSACTION_ISSUE_DETAIL_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE CAGE_TRANSACTION_ISSUE_DETAIL_FACT_SK IN 
(SELECT CAGE_TRANSACTION_ISSUE_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.CAGE_TRANSACTION_ISSUE_DETAIL_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));
 
 
UPDATE DAAS_CORE.COMP_FREE_PLAY_DETAIL_FACT
SET REPLAY_COUNTER = NVL(REPLAY_COUNTER,0) + 1
WHERE COMP_FREE_PLAY_DETAIL_FACT_SK IN 
(SELECT COMP_FREE_PLAY_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.COMP_FREE_PLAY_DETAIL_FACT_VW
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_IDS));