CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'RATINGS_FACT', 
'WHERE RATINGS_FACT_SK IN 
(SELECT RATINGS_FACT_SK FROM DAAS_CORE_GAMING_VW.RATINGS_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);
 
 
CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT', 
'WHERE HOTEL_GUEST_RESERVATIONS_FACT_SK IN 
(SELECT HOTEL_GUEST_RESERVATIONS_FACT_SK FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'CHECK_SALES_FACT', 
'WHERE CHECK_SALES_SK IN (
SELECT CHECK_SALES_SK FROM DAAS_CORE_POS_VW.CHECK_SALES_FACT_VW
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'OFFER_LEDGER_FACT', 
'WHERE OFFER_LEDGER_FACT_SK IN 
(SELECT OFFER_LEDGER_FACT_SK FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_GUEST_UNIQUE_ID_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'OFFER_LEDGER_FACT_HISTORY', 
'WHERE OFFER_LEDGER_FACT_SK IN 
(SELECT OFFER_LEDGER_FACT_SK FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_GUEST_UNIQUE_ID_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

 
CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'COMP_DETAIL_FACT', 
'WHERE COMP_DETAIL_FACT_SK IN 
(SELECT COMP_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.COMP_DETAIL_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'CAGE_TRANSACTION_ISSUE_DETAIL_FACT', 
'WHERE CAGE_TRANSACTION_ISSUE_DETAIL_FACT_SK IN 
(SELECT CAGE_TRANSACTION_ISSUE_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.CAGE_TRANSACTION_ISSUE_DETAIL_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'COMP_FREE_PLAY_DETAIL_FACT', 
'WHERE COMP_FREE_PLAY_DETAIL_FACT_SK IN 
(SELECT COMP_FREE_PLAY_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.COMP_FREE_PLAY_DETAIL_FACT_VW
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 1000000000);

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'DIGITAL_TRANSACTIONS_FACT', 
'WHERE CID IN 
(SELECT 
     DISTINCT CID 
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
    DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
    DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = ''William Hill'' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.METRIC_GUID))', 
'METRICS_MISMATCHES', 100000000);