

-->We're taking Transaction_tbl_sk and soft deleting in Trip_detail table
-->Taking corresponding Trip_master_id getting into recalc_queue

CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('CREATE OR REPLACE TABLE DAAS_TEMP.RATINGS_SK_RANK AS
SELECT
TM.TRIP_MASTER_ID,
TD.TRANSACTION_TABLE_SK,
DENSE_RANK() OVER ( ORDER BY TRIP_MASTER_ID),
ROUND(DENSE_RANK() OVER ( ORDER BY TRIP_MASTER_ID)/200000000)+1 AS RANK
FROM DAAS_CORE.TRIP_DETAIL TD
JOIN DAAS_CORE.TRIP_MASTER TM
ON TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
WHERE TRANSACTION_TABLE_SK NOT IN (SELECT DISTINCT RATINGS_FACT_SK FROM DAAS_CORE.RATINGS_FACT)
AND TD.TRANSACTION_TYPE = \'RATINGS\'
AND TM.DELETE_IND = \'N\'
AND TD.DELETE_IND = \'N\'
AND TM.GUEST_UNIQUE_ID <> -1
ORDER BY 3,1');

CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('CREATE OR REPLACE TABLE DAAS_TEMP.RATINGS_SK_RANK AS
SELECT
TM.TRIP_MASTER_ID,
TD.TRANSACTION_TABLE_SK,
DENSE_RANK() OVER ( ORDER BY TRIP_MASTER_ID),
FLOOR(DENSE_RANK() OVER ( ORDER BY TRIP_MASTER_ID)/200000000)+1 AS RANK
FROM DAAS_CORE.TRIP_DETAIL TD
JOIN DAAS_CORE.TRIP_MASTER TM
ON TD.TRIP_MASTER_ID = TM.TRIP_MASTER_ID
WHERE TRANSACTION_TABLE_SK NOT IN (SELECT DISTINCT RATINGS_FACT_SK FROM DAAS_CORE.RATINGS_FACT)
AND TD.TRANSACTION_TYPE = \'RATINGS\'
AND TM.DELETE_IND = \'N\'
AND TD.DELETE_IND = \'N\'
AND TM.GUEST_UNIQUE_ID <> -1
ORDER BY 3,1');