--Some of 0 metrics records are got deleted only for Mkt & Ent as Prop having values
--To replay such records
--If Client asked to retain those records
UPDATE DAAS_CORE.DIGITAL_TRANSACTIONS_FACT 
SET REPLAY_COUNTER=COALESCE(REPLAY_COUNTER,0)+1
WHERE CID IN(
SELECT DTF.CID 
FROM DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END 
WHERE (DGXBL.GUEST_UNIQUE_ID,TO_DATE(DTF.REPORT_DT)) IN (
SELECT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
WHERE TRIP_TYPE='PROPERTY' AND DIGITAL_FLG='Y'
 GROUP BY GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
  HAVING SUM(CASINO_GGR) = 0 
	AND SUM(SPORTS_GGR) = 0  
	AND SUM(POKER_GGR) = 0  
	AND SUM(SPORTS_THEO) = 0  
	AND SUM(CASINO_NET_THEO) = 0  
	AND SUM(CASINO_WAGER) = 0  
	AND SUM(SPORTS_WAGER) = 0  
	AND SUM(CASINO_BONUS) = 0  
	AND SUM(SPORTS_BONUS) = 0));
	
CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'DIGITAL_TRANSACTIONS_FACT', 
'WHERE CID IN(
SELECT DTF.CID 
FROM DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END 
WHERE (DGXBL.GUEST_UNIQUE_ID,TO_DATE(DTF.REPORT_DT)) IN (
SELECT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
WHERE TRIP_TYPE='PROPERTY' AND DIGITAL_FLG='Y'
 GROUP BY GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
  HAVING SUM(CASINO_GGR) = 0 
	AND SUM(SPORTS_GGR) = 0  
	AND SUM(POKER_GGR) = 0  
	AND SUM(SPORTS_THEO) = 0  
	AND SUM(CASINO_NET_THEO) = 0  
	AND SUM(CASINO_WAGER) = 0  
	AND SUM(SPORTS_WAGER) = 0  
	AND SUM(CASINO_BONUS) = 0  
	AND SUM(SPORTS_BONUS) = 0))', 
'DIGITAL_REPLAY', 100000000);	

---If client asked to delete those records
DELETE FROM
    DAAS_CORE.DAILY_ACTIVITY_SUMMARY
WHERE 
  (GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE) IN 
  (SELECT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY DTF
  WHERE TRIP_TYPE='PROPERTY'
  GROUP BY GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
 HAVING SUM(DTF.CASINO_GGR) = 0 
	AND SUM(DTF.SPORTS_GGR) = 0  
	AND SUM(DTF.POKER_GGR) = 0  
	AND SUM(DTF.SPORTS_THEO) = 0  
	AND SUM(DTF.CASINO_NET_THEO) = 0  
	AND SUM(DTF.CASINO_WAGER) = 0  
	AND SUM(DTF.SPORTS_WAGER) = 0  
	AND SUM(DTF.CASINO_BONUS) = 0  
	AND SUM(DTF.SPORTS_BONUS) = 0);