SELECT COUNT(*) FROM DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
	DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
	DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = 'William Hill' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END  
WHERE (CASINO_GGR+SPORTS_GGR+POKER_GGR+SPORTS_THEO+CASINO_NET_THEO+CASINO_WAGER+SPORTS_WAGER+CASINO_BONUS+SPORTS_BONUS) = 0
AND DTF.CID IN (SELECT DISTINCT CID FROM DAAS_CORE.DIGITAL_TRANSACTIONS_FACT 
WHERE CASINO_GGR <> 0 
OR SPORTS_GGR <> 0 
OR POKER_GGR <> 0 
OR SPORTS_THEO <> 0 
OR CASINO_NET_THEO <> 0 
OR CASINO_WAGER <> 0 
OR SPORTS_WAGER <> 0 
OR CASINO_BONUS <> 0 
OR SPORTS_BONUS <> 0)
AND DTF.DELETE_IND='N'
AND (DGXBL.GUEST_UNIQUE_ID,TO_DATE(DTF.REPORT_DT)) NOT IN (
SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY WHERE DIGITAL_FLG='Y');--37,810,558

	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.DIGITAL_PLAY_DISCREPANCY2 AS
	SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
	FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY 
	WHERE 
	(GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE) IN 
	(SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY DAS
	WHERE DIGITAL_FLG = 'N' AND TRIP_MASTER_ID <> -1 
	AND NOT EXISTS (SELECT 1 FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY DS 
		WHERE DS.GUEST_UNIQUE_ID=DAS.GUEST_UNIQUE_ID 
		AND DS.GUEST_ACTIVITY_DATE=DAS.GUEST_ACTIVITY_DATE 
		AND TRIP_TYPE='PROPERTY' 
		AND TRIP_MASTER_ID=-1))
	AND TRIP_TYPE='ENTERPRISE'
	AND DELETE_IND='N'
	AND DIGITAL_FLG='Y';
	` } );

	snowflake.execute( {sqlText: `
	CREATE OR REPLACE TABLE DAAS_TEMP.DIGITAL_PLAY_DISCREPANCY3 AS
	SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE
	FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY 
	WHERE 
	(GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE) IN 
	(SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
		FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
		WHERE DIGITAL_FLG = 'Y' AND TRIP_MASTER_ID = -1 AND DELETE_IND='N')
	AND TRIP_TYPE='ENTERPRISE'
	AND DELETE_IND='N'
	AND DIGITAL_FLG='N';
	` } );
	
