--For 8963..chck with Pete
--For some of records Mkt & Ent got deleted...As some of metrics is 0 for Prop
--Due to Concat prop..Mkt & Ent duplicated in DAILY_ACTIVITY_SUMMARY for same guid on same date(2358(17/01),2327(18/01))
--For 118 Digital records(18/01), PROPERTY & MARKET not getting populated

SELECT COUNT(*)
FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY 
WHERE 
(GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE) IN 
(SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
	FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
	WHERE DIGITAL_FLG = 'Y' AND TRIP_MASTER_ID = -1 AND DELETE_IND='N')
AND TRIP_TYPE='ENTERPRISE'
AND DELETE_IND='N'
AND DIGITAL_FLG='N';

--2358(17/01)
--2327(18/01)
--2313(19/01)
--2242(22/01)

--661

--Collect all discrepancy GUID in temp tbl
SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE
FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY 
WHERE 
(GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE) IN 
(SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
	FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
	WHERE DIGITAL_FLG = 'Y' AND TRIP_MASTER_ID = -1 AND DELETE_IND='N')
AND TRIP_TYPE='ENTERPRISE'
AND DELETE_IND='N'
AND DIGITAL_FLG='N';


SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY 
WHERE 
(GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE) IN 
(SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY DAS
WHERE DIGITAL_FLG = 'N' AND TRIP_MASTER_ID <> -1 
AND NOT EXISTS (SELECT 1 FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY DS 
	WHERE DS.GUEST_UNIQUE_ID=DAS.GUEST_UNIQUE_ID 
	AND DS.GUEST_ACTIVITY_DATE=DAS.GUEST_ACTIVITY_DATE 
	AND TRIP_TYPE='PROPERTY' 
	AND TRIP_MASTER_ID=-1))
AND TRIP_TYPE='ENTERPRISE'
AND DELETE_IND='N'
AND DIGITAL_FLG='Y';




SELECT DISTINCT GUEST_UNIQUE_ID,GUEST_ACTIVITY_DATE 
FROM DAAS_CORE.DAILY_ACTIVITY_SUMMARY
WHERE TRIP_TYPE='ENTERPRISE' 
AND DIGITAL_FLG='N'
AND (CASINO_GGR <> 0 
OR SPORTS_GGR <> 0
OR POKER_GGR <> 0
OR SPORTS_THEO <> 0
OR CASINO_NET_THEO <> 0
OR CASINO_WAGER <> 0
OR SPORTS_WAGER <> 0
OR CASINO_BONUS <> 0
OR SPORTS_BONUS <>0); 


--& GENERAL VALIDATION QUERY
--UNION ALL AND REPLAY FROM FACT
