SELECT DISTINCT DELETE_IND FROM DAAS_CORE.TRIP_DETAIL
WHERE TRANSACTION_TABLE_SK IN 
(
  SELECT DISTINCT OFFER_LEDGER_FACT_SK 
  FROM 
    DAAS_CORE.OFFER_LEDGER_FACT_HISTORY
  WHERE
       OFFER_STATUS_CD IN ('R','X')
   AND CURRENT_STATUS_IND = 'Y'
   AND DELETE_IND = 'Y'
)
AND TRANSACTION_TYPE = 'OFFER';

SELECT DISTINCT DELETE_IND FROM DAAS_CORE.TRIP_DETAIL
WHERE TRANSACTION_TABLE_SK IN 
(
  SELECT DISTINCT OFFER_LEDGER_FACT_SK 
  FROM 
    DAAS_CORE.OFFER_LEDGER_FACT_HISTORY
  WHERE
       OFFER_STATUS_CD IN ('R','X')
   AND CURRENT_STATUS_IND = 'N'
   AND DELETE_IND = 'Y'
)
AND TRANSACTION_TYPE = 'OFFER';

EXECUTE TASK DAAS_COMMON.TRIP_ROOT_TASK;

show tasks like 'TRIP_ROOT_TASK';

SELECT COUNT(*) FROM DAAS_TEMP.OFFER_FIX;--831

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK SUSPEND;

SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 583 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_FILTERED_TXNS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 558 ORDER BY BATCH_ID DESC LIMIT 5; -- RATINGS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 566 ORDER BY BATCH_ID DESC LIMIT 5; -- HOTEL
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 567 ORDER BY BATCH_ID DESC LIMIT 5; -- POS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 579 ORDER BY BATCH_ID DESC LIMIT 5; -- OFFER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 580 ORDER BY BATCH_ID DESC LIMIT 5; -- COMP
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 581 ORDER BY BATCH_ID DESC LIMIT 5; -- MARKERS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 582 ORDER BY BATCH_ID DESC LIMIT 5; -- FREEPLAY
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 556 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_RECALCULATION
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 559 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE_CHECK
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 560 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 564 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_GUEST_GUESTXREF
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 561 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_TRIP_MASTER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 562 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 578 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_SUMMARY_WRAPPER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 554 ORDER BY BATCH_ID DESC LIMIT 5; -- PDB_OFFER_LEDGER_FACT
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 555 ORDER BY BATCH_ID DESC LIMIT 5; -- PDB_OFFER_LEDGER_FACT_PURGE_HIST

SELECT * FROM DAAS_COMMON.BATCH_METRICS_S02 WHERE BATCH_ID IN (14747109,14737865,14728569);

SELECT * FROM DAAS_COMMON.JOB WHERE JOB_ID = 555 ;--DAAS_PROD_IT_WHSRCTORAW_COMPUTE

SELECT DISTINCT DELETE_IND FROM DAAS_CORE.TRIP_DETAIL
WHERE TRANSACTION_TABLE_SK IN 
(
  SELECT DISTINCT OFFER_LEDGER_FACT_SK 
  FROM 
    DAAS_CORE.OFFER_LEDGER_FACT_HISTORY
  WHERE
       OFFER_STATUS_CD IN ('R','X')
   AND CURRENT_STATUS_IND = 'N'
   AND DELETE_IND = 'Y'
)
AND TRANSACTION_TYPE = 'OFFER';

SELECT DISTINCT DELETE_IND FROM DAAS_CORE.TRIP_DETAIL
WHERE TRANSACTION_TABLE_SK IN 
(
  SELECT DISTINCT OFFER_LEDGER_FACT_SK 
  FROM 
    DAAS_CORE.OFFER_LEDGER_FACT_HISTORY
  WHERE
       OFFER_STATUS_CD IN ('R','X')
   AND CURRENT_STATUS_IND = 'Y'
   AND DELETE_IND = 'Y'
)
AND TRANSACTION_TYPE = 'OFFER';

SELECT COUNT(DISTINCT TRANSACTION_TABLE_SK) FROM DAAS_CORE.TRIP_DETAIL AT (OFFSET => -60*60*1)
WHERE TRANSACTION_TABLE_SK IN 
(
  SELECT DISTINCT OFFER_LEDGER_FACT_SK 
  FROM 
    DAAS_CORE.OFFER_LEDGER_FACT_HISTORY
  WHERE
       OFFER_STATUS_CD IN ('R','X')
   AND CURRENT_STATUS_IND = 'N'
   AND DELETE_IND = 'Y'
)
AND TRANSACTION_TYPE = 'OFFER'
AND DELETE_IND = 'N';

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK RESUME;

SHOW TASKS LIKE '%TRIP_ROOT_TASK%';

SELECT * FROM DAAS_COMMON.JOB WHERE JOB_NAME LIKE '%OFFER_LEDGER%';

select * from table(information_schema.query_history_by_warehouse(WAREHOUSE_NAME=>'DAAS_PROD_IT_WHSRCTORAW_COMPUTE'))
WHERE QUERY_TAG LIKE '%14648897_PDB_OFFER_LEDGER_FACT_PURGE_HISTORY_LOAD_PROC%'
order by start_time desc ;

SELECT * FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_VW
WHERE OFFER_LEDGER_FACT_SK=79577250672;