CREATE TABLE IF NOT EXISTS DAAS_EXACT_TARGET_STG.ET_BOUNCES_EVENT_STG 
(
	I_CLIENTID                 VARCHAR(5000),
	I_SENDID                   VARCHAR(5000) NOT NULL,
	C_SUBSCRIBER_KEY           VARCHAR(5000) NOT NULL,
	C_EMAILADDRESS             VARCHAR(5000),
	I_SUBSCRIBERID             VARCHAR(5000),
	I_LISTID                   VARCHAR(5000),
	D_EVENTDATE                VARCHAR(5000),
	C_EVENTTYPE                VARCHAR(5000),
	C_BOUNCE_CATEGORY          VARCHAR(5000),
	I_SMTP_CODE                VARCHAR(5000),
	C_BOUNCE_REASON            VARCHAR(5000),
	C_BATCHID                  VARCHAR(5000) NOT NULL,
	C_TRIGGEREDSENDEXTERNALKEY VARCHAR(5000),
	SOURCE_SYSTEM_NAME         VARCHAR(100),
	TIME_ZONE 				   VARCHAR(100),
	CREATED_DATE 			   TIMESTAMP_NTZ(9),
	CREATED_BY				   VARCHAR(100),
	UPDATED_DATE 			   TIMESTAMP_NTZ(9),
	UPDATED_BY 				   VARCHAR(100),
	REPLAY_COUNTER 			   NUMBER(38,0),
	SOURCE_FILE_NAME 		   VARCHAR(200)
);