~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Replay Metrics Mismatches for all Domains [Request for 2XL WH to execute Trip root task]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1) Make sure no secondary market added to the PROPERTY_MARKET_LKP table. Delete if exists. (This step is only for UAT, not for PROD)
	
	DELETE FROM DAAS_UAT.PROPERTY_MARKET_LKP WHERE MARKET_CD = 'CH2';


2) Code Check-in and Deploy Hotel Summary proc


3) Code Check-in and Deploy Adhoc procs for each domain to Capture Discrepancy guests into a temp table in DAAS_TEMP for both TRIP_SUMMARY & DAILY_ACTIVITY_SUMMARY tables.
	
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_RATINGS_ADHOC_REQUEST_PROC();
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_HOTEL_ADHOC_REQUEST_PROC();
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_POS_ADHOC_REQUEST_PROC();
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_OFFER_ADHOC_REQUEST_PROC();
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_COMP_ADHOC_REQUEST_PROC();
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_MARKERS_ADHOC_REQUEST_PROC();
CALL DAAS_ADHOC.TRIP_METRICS_MISMATCHES_FREEPLAY_ADHOC_REQUEST_PROC();

	
	
4) Replay the captured distinct Guests at once for each domain including Digital Play using DATA_REPLAY proc after Adhoc proc execution.

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'RATINGS_FACT', 
'WHERE RATINGS_FACT_SK IN 
(SELECT RATINGS_FACT_SK FROM DAAS_CORE_GAMING_VW.RATINGS_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);


CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT', 
'WHERE HOTEL_GUEST_RESERVATIONS_FACT_SK IN 
(SELECT HOTEL_GUEST_RESERVATIONS_FACT_SK FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.HOTEL_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);


CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'CHECK_SALES_FACT', 
'WHERE CHECK_SALES_SK IN (
SELECT CHECK_SALES_SK FROM DAAS_CORE_POS_VW.CHECK_SALES_FACT_VW
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.POS_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);


CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'OFFER_LEDGER_FACT', 
'WHERE OFFER_LEDGER_FACT_SK IN 
(SELECT OFFER_LEDGER_FACT_SK FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_GUEST_UNIQUE_ID_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFER_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);


CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'OFFER_LEDGER_FACT_HISTORY', 
'WHERE OFFER_LEDGER_FACT_SK IN 
(SELECT OFFER_LEDGER_FACT_SK FROM DAAS_CORE_MARKETING_VW.OFFER_LEDGER_FACT_TRIP_GUEST_UNIQUE_ID_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFER_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);


CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'COMP_DETAIL_FACT', 
'WHERE COMP_DETAIL_FACT_SK IN 
(SELECT COMP_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.COMP_DETAIL_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.COMP_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);



CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'CAGE_TRANSACTION_ISSUE_DETAIL_FACT', 
'WHERE CAGE_TRANSACTION_ISSUE_DETAIL_FACT_SK IN 
(SELECT CAGE_TRANSACTION_ISSUE_DETAIL_FACT_SK FROM DAAS_CORE_GAMING_VW.CAGE_TRANSACTION_ISSUE_DETAIL_FACT_VW 
WHERE GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.MARKERS_DISCREPANCY_GUEST_IDS))', 
'8588', 100000000);



CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'DIGITAL_TRANSACTIONS_FACT', 
'WHERE CID IN 
(SELECT 
     DISTINCT CID 
FROM 
    DAAS_CORE.DIGITAL_TRANSACTIONS_FACT DTF
LEFT JOIN 
  (SELECT DISTINCT BRAND_NAME,STATE_CD FROM DAAS_STG_IGAMING.BRAND_VALIDATION) BVAL 
ON 
   DTF.BRAND = REPLACE(BVAL.BRAND_NAME,'''')
LEFT JOIN 
    DAAS_CORE.DIGITAL_GUEST_XREF_BRIDGE_LKP DGXBL 
ON 
    DTF.CID = DGXBL.IGAMING_XREF 
AND
    DGXBL.IGAMING_XREF_BRAND = CASE WHEN DTF.SOURCE_SYSTEM_NM = ''William Hill'' THEN DTF.BRAND ELSE SUBSTR(BVAL.BRAND_NAME,1,2)||BVAL.STATE_CD END
WHERE GUEST_UNIQUE_ID IN (
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATINGS_DISCREPANCY_GUEST_IDS
UNION 
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.HOTEL_DISCREPANCY_GUEST_IDS
UNION 
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.POS_DISCREPANCY_GUEST_IDS
UNION 
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.COMP_DISCREPANCY_GUEST_IDS
UNION 
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFER_DISCREPANCY_GUEST_IDS
UNION 
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.FREEPLAY_DISCREPANCY_GUEST_IDS
UNION 
SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.MARKERS_DISCREPANCY_GUEST_IDS)
)', 
'8588', 100000000);


5) Update the JOB table WH for all trip jobs to 2XL warehouse -- Complete the update statement when env is back

UPDATE DAAS_COMMON.JOB
SET WAREHOUSE_NAME = ''
WHERE JOB_NAME IN ();



6) Trigger TRIP_ROOT_TASK (thru EXECUTE TASK) after calling all domains replay proc.

EXECUTE TASK DAAS_COMMON.TRIP_ROOT_TASK;


7) Validate results after replay -- Take Select part from Adhoc procs to validate 


8) Revert the Trip jobs WH to L -- Complete the update statement when env is back

UPDATE DAAS_COMMON.JOB
SET WAREHOUSE_NAME = ''
WHERE JOB_NAME IN ();