-----step 3)
CREATE TASK DAAS_ADHOC.CREATE_HOTEL_EXTRA_SKS_CLEANUP_TRIPS
WAREHOUSE = DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L
AS
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('CREATE OR REPLACE TABLE DAAS_TEMP.HOTEL_EXTRA_SKS_CLEANUP_TRIPS AS
SELECT DISTINCT TM.TRIP_MASTER_ID,TD.TRANSACTION_TABLE_SK,DENSE_RANK() OVER(ORDER BY TM.TRIP_MASTER_ID) AS RANK
FROM DAAS_CORE.TRIP_MASTER TM
JOIN DAAS_CORE.TRIP_DETAIL TD
ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
WHERE TM.DELETE_IND = \'N\'
AND TD.DELETE_IND = \'N\'
AND TD.TRANSACTION_TYPE = \'HOTEL\'
AND TM.GUEST_UNIQUE_ID <> -1
AND TRANSACTION_TABLE_SK NOT IN (SELECT HOTEL_GUEST_RESERVATION_FACT_SK FROM DAAS_CORE.HOTEL_GUEST_RESERVATION_FACT);');
 
---------step 6)
 
CREATE TASK DAAS_ADHOC.UPDATE_HOTEL_EXTRA_SKS_CLEANUP_TRIPS
WAREHOUSE = DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L
AS
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('UPDATE DAAS_CORE.TRIP_DETAIL
SET DELETE_IND = \'Y\', TRANSACTION_SUB_TYPE = \'VOIDED\'
WHERE TRANSACTION_TABLE_SK IN 
(SELECT DISTINCT TRANSACTION_TABLE_SK FROM DAAS_TEMP.HOTEL_EXTRA_SKS_CLEANUP_TRIPS WHERE RANK <=?)
AND TRANSACTION_TYPE = \'HOTEL\'');
 
 
-------
CREATE TASK DAAS_ADHOC.INSERT_TRIP_RECALC_QUEUE
WAREHOUSE = DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L
AS
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('INSERT INTO DAAS_CORE.TRIP_RECALC_QUEUE
( 
	TRIP_MASTER_ID,
	STATUS,
	BATCH_ID,
	CREATED_DTTM,
	CREATED_BY,
	UPDATED_DTTM,
	UPDATED_BY 
)
SELECT 
	TM.TRIP_MASTER_ID,
	\'PENDING\' AS STATUS,
	20231213,
	CURRENT_TIMESTAMP AS CREATED_DTTM,
	CURRENT_USER AS CREATED_BY,
	CURRENT_TIMESTAMP AS UPDATED_DTTM,
	CURRENT_USER AS UPDATED_BY
FROM
	DAAS_CORE.TRIP_MASTER TM
WHERE 
	TM.TRIP_MASTER_ID IN (SELECT DISTINCT TRIP_MASTER_ID FROM DAAS_TEMP.HOTEL_EXTRA_SKS_CLEANUP_TRIPS where rank <=?)
AND TM.DELETE_IND = \'N\';'
);

ALTER WAREHOUSE DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L SET WAREHOUSE_SIZE = 'LARGE';
SHOW WAREHOUSES LIKE '%DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L%';
CALL DAAS_COMMON.ALTER_TASK_TIMEOUT_PROC('DAAS_COMMON', 'TRIP_RECALCULATION_ONDEMAND_TASK', 7200000);
ALTER TASK DAAS_PROD.DAAS_COMMON.TRIP_ROOT_TASK RESUME;