--------HOTEL----------
--No.of Trip_master_id's inserted into Recalc_queue
SELECT 
		COUNT(TM.TRIP_MASTER_ID)
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.HOTEL_EXTRA_SKS_CLEANUP_GUESTS WHERE GUEST_UNIQUE_ID <> -1)
	AND TM.DELETE_IND = 'N';--19217457

--No.of trip_master_is's getting recalculated based on Guest_unique_id's
SELECT
	 COUNT(A.TRIP_MASTER_ID)
FROM
		DAAS_CORE.TRIP_MASTER A
JOIN DAAS_CORE.TRIP_DETAIL B
ON
		A.TRIP_MASTER_ID = B.TRIP_MASTER_ID
JOIN (SELECT 
		TM.TRIP_MASTER_ID
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.HOTEL_EXTRA_SKS_CLEANUP_GUESTS)
	AND TM.DELETE_IND = 'N') C
ON
		A.TRIP_MASTER_ID = C.TRIP_MASTER_ID
WHERE
		 A.DELETE_IND = 'N'
	AND B.TRANSACTION_SUB_TYPE = 'OPENED';--538385265
	
---------OFFERS----------
--No.of Trip_master_id's inserted into Recalc_queue
SELECT 
		COUNT(TM.TRIP_MASTER_ID)
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFERS_EXTRA_SKS_CLEANUP_GUESTS)
	AND TM.DELETE_IND = 'N';--275285719
 
--No.of trip_master_is's getting recalculated based on Guest_unique_id's
SELECT
	 COUNT(A.TRIP_MASTER_ID)
FROM
		DAAS_CORE.TRIP_MASTER A
JOIN DAAS_CORE.TRIP_DETAIL B
ON
		A.TRIP_MASTER_ID = B.TRIP_MASTER_ID
JOIN (SELECT 
		TM.TRIP_MASTER_ID
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.OFFERS_EXTRA_SKS_CLEANUP_GUESTS)
	AND TM.DELETE_IND = 'N') C
ON
		A.TRIP_MASTER_ID = C.TRIP_MASTER_ID
WHERE
		 A.DELETE_IND = 'N'
	AND B.TRANSACTION_SUB_TYPE = 'OPENED';--6090158703
	
---------RATINGS----------
--No.of Trip_master_id's inserted into Recalc_queue
SELECT 
		COUNT(TM.TRIP_MASTER_ID)
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATING_EXTRA_SKS)
	AND TM.DELETE_IND = 'N';--340307883
	
--No.of trip_master_is's getting recalculated based on Guest_unique_id's
SELECT
	 COUNT(A.TRIP_MASTER_ID)
FROM
		DAAS_CORE.TRIP_MASTER A
JOIN DAAS_CORE.TRIP_DETAIL B
ON
		A.TRIP_MASTER_ID = B.TRIP_MASTER_ID
JOIN (SELECT 
		TM.TRIP_MASTER_ID
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.GUEST_UNIQUE_ID IN (SELECT DISTINCT GUEST_UNIQUE_ID FROM DAAS_TEMP.RATING_EXTRA_SKS)
	AND TM.DELETE_IND = 'N') C
ON
		A.TRIP_MASTER_ID = C.TRIP_MASTER_ID
WHERE
		 A.DELETE_IND = 'N'
	AND B.TRANSACTION_SUB_TYPE = 'OPENED';--7100646853
	