----Check count of trip_master_is's getting recalculated 
SELECT
	 COUNT(A.TRIP_MASTER_ID)
FROM
		DAAS_CORE.TRIP_MASTER A
JOIN DAAS_CORE.TRIP_DETAIL B
ON
		A.TRIP_MASTER_ID = B.TRIP_MASTER_ID
JOIN (SELECT 
		TM.TRIP_MASTER_ID
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.TRIP_MASTER_ID IN (SELECT DISTINCT TRIP_MASTER_ID FROM DAAS_TEMP.RATING_EXTRA_SKS_CLEANUP_TRIPS WHERE RANK)
	AND TM.DELETE_IND = 'N') C
ON
		A.TRIP_MASTER_ID = C.TRIP_MASTER_ID
WHERE
		 A.DELETE_IND = 'N'
	AND B.TRANSACTION_SUB_TYPE = 'OPENED';
	
---create temp table for records to be soft deleted	
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('CREATE OR REPLACE TABLE DAAS_TEMP.RATING_EXTRA_SKS_CLEANUP_TRIPS AS
	SELECT DISTINCT TM.TRIP_MASTER_ID,TD.TRANSACTION_TABLE_SK,DENSE_RANK() OVER(ORDER BY TM.TRIP_MASTER_ID) AS RANK
	FROM DAAS_CORE.TRIP_MASTER TM
	JOIN DAAS_CORE.TRIP_DETAIL TD
	ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
	WHERE TM.DELETE_IND = \'N\'
	AND TD.DELETE_IND = \'N\'
	AND TD.TRANSACTION_TYPE = \'RATINGS\'
	AND TM.GUEST_UNIQUE_ID <> -1
	AND TRANSACTION_TABLE_SK NOT IN (SELECT RATINGS_FACT_SK FROM DAAS_CORE.RATINGS_FACT);');
	
---Soft delete those records from trip_detail tbl
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('UPDATE DAAS_CORE.TRIP_DETAIL
	SET DELETE_IND = \'Y\',
	TRANSACTION_SUB_TYPE = \'VOIDED\'
	WHERE TRANSACTION_TABLE_SK IN (SELECT DISTINCT TRANSACTION_TABLE_SK FROM DAAS_TEMP.RATING_EXTRA_SKS_CLEANUP_TRIPS WHERE RANK )
	AND TRANSACTION_TYPE = \'RATINGS\';');

--Insert trip_master_id into recal queue for soft deleted records	
CALL DAAS_ADHOC.ADHOC_SQL_EXECUTE('INSERT INTO DAAS_CORE.TRIP_RECALC_QUEUE
	( 
		TRIP_MASTER_ID,
		STATUS,
		BATCH_ID,
		CREATED_DTTM,
		CREATED_BY,
		UPDATED_DTTM,
		UPDATED_BY 
	)
	SELECT 
		TM.TRIP_MASTER_ID,
		\'PENDING\' AS STATUS,
		20231208,
		CURRENT_TIMESTAMP AS CREATED_DTTM,
		CURRENT_USER AS CREATED_BY,
		CURRENT_TIMESTAMP AS UPDATED_DTTM,
		CURRENT_USER AS UPDATED_BY
	FROM
		DAAS_CORE.TRIP_MASTER TM
	WHERE 
		TM.TRIP_MASTER_ID IN (SELECT DISTINCT TRIP_MASTER_ID FROM DAAS_TEMP.RATING_EXTRA_SKS_CLEANUP_TRIPS WHERE RANK )
	AND TM.DELETE_IND = \'N\';');
	
	
RANK <=20000000 --completed
RANK BETWEEN 20000001  AND 40000000 --completed
RANK BETWEEN 40000001  AND 60000000 --completed
RANK BETWEEN 60000001  AND 80000000 --completed
RANK BETWEEN 80000001  AND 95000000 --completed
RANK BETWEEN 95000001 AND 107500000 --completed
RANK BETWEEN 107500001 AND 117500000 --completed
RANK BETWEEN 117500001 AND 127500000 --completed
RANK >= 127500001 --completed


MAX(RANK) --> 139,569,723
