CREATE OR REPLACE VIEW DAAS_CORE_MARKETING_VW.ET_BOUNCES_EVENT_VW 
(
	 I_CLIENTID                
	,I_SENDID                  
	,C_SUBSCRIBER_KEY          
	,I_DMID 
	,I_XREF_DMID
	,C_EMAILADDRESS            
	,I_SUBSCRIBERID            
	,I_LISTID                  
	,D_EVENTDATE               
	,C_EVENTTYPE               
	,C_BOUNCE_CATEGORY         
	,I_SMTP_CODE               
	,C_BOUNCE_REASON           
	,C_BATCHID                 
	,C_TRIGGEREDSENDEXTERNALKEY
	,C_QUALITY_CD 			  
	,D_TIMESTAMP               
)
AS
WITH RAW_CTE AS
(
SELECT
	 TD_RAW.I_CLIENTID                
	,TD_RAW.I_SENDID                  
	,TD_RAW.C_SUBSCRIBER_KEY          
	,TD_RAW.I_DMID
	,LKP.PRIMARY_ACCOUNT_NBR AS I_XREF_DMID
	,TD_RAW.C_EMAILADDRESS            
	,TD_RAW.I_SUBSCRIBERID            
	,TD_RAW.I_LISTID                  
	,TD_RAW.D_EVENTDATE               
	,TD_RAW.C_EVENTTYPE               
	,TD_RAW.C_BOUNCE_CATEGORY         
	,TD_RAW.I_SMTP_CODE               
	,TD_RAW.C_BOUNCE_REASON           
	,TD_RAW.C_BATCHID                 
	,TD_RAW.C_TRIGGEREDSENDEXTERNALKEY
	,TD_RAW.C_QUALITY_CD 			  
	,TD_RAW.D_TIMESTAMP
FROM
	DAAS_TERADATA_RAW.ET_BOUNCES_EVENT TD_RAW
JOIN
	DAAS_CORE.GUEST_XREF_BRIDGE_LKP LKP
ON
	TD_RAW.I_DMID = LKP.XREF_ACCOUNT_NBR
WHERE
	LKP.XREF_ACCOUNT_NBR <> -1
UNION ALL
SELECT
	 RAW.I_CLIENTID                
	,RAW.I_SENDID                  
	,RAW.C_SUBSCRIBER_KEY          
	,RAW.I_DMID   
	,LKP.PRIMARY_ACCOUNT_NBR AS I_XREF_DMID	
	,RAW.C_EMAILADDRESS            
	,RAW.I_SUBSCRIBERID            
	,RAW.I_LISTID                  
	,RAW.D_EVENTDATE               
	,RAW.C_EVENTTYPE               
	,RAW.C_BOUNCE_CATEGORY         
	,RAW.I_SMTP_CODE               
	,RAW.C_BOUNCE_REASON           
	,RAW.C_BATCHID                 
	,RAW.C_TRIGGEREDSENDEXTERNALKEY
	,RAW.C_QUALITY_CD 			  
	,RAW.D_TIMESTAMP
FROM
	DAAS_EXACT_TARGET_RAW.ET_BOUNCES_EVENT_RAW RAW
JOIN
	DAAS_CORE.GUEST_XREF_BRIDGE_LKP LKP
ON
	RAW.I_DMID = LKP.XREF_ACCOUNT_NBR
WHERE
	LKP.XREF_ACCOUNT_NBR <> -1
)
SELECT
	 I_CLIENTID                
	,I_SENDID                  
	,C_SUBSCRIBER_KEY          
	,I_DMID
	,I_XREF_DMID	
	,C_EMAILADDRESS            
	,I_SUBSCRIBERID            
	,I_LISTID                  
	,D_EVENTDATE               
	,C_EVENTTYPE               
	,C_BOUNCE_CATEGORY         
	,I_SMTP_CODE               
	,C_BOUNCE_REASON           
	,C_BATCHID                 
	,C_TRIGGEREDSENDEXTERNALKEY
	,C_QUALITY_CD 			  
	,D_TIMESTAMP
FROM
	RAW_CTE
QUALIFY ROW_NUMBER() OVER(PARTITION BY I_SENDID, I_DMID, C_BATCHID
ORDER BY D_EVENTDATE DESC, D_TIMESTAMP DESC) = 1;