CREATE TABLE IF NOT EXISTS DAAS_TERADATA_RAW.ET_BOUNCES_EVENT  
(
      I_CLIENTID INTEGER,
      I_SENDID INTEGER NOT NULL,
      C_SUBSCRIBER_KEY VARCHAR(100) NOT NULL,
      I_DMID NUMBER(38,0),
      C_EMAILADDRESS VARCHAR(200) ,
      I_SUBSCRIBERID INTEGER,
      I_LISTID INTEGER,
      D_EVENTDATE TIMESTAMP_NTZ(9),
      C_EVENTTYPE VARCHAR(200) ,
      C_BOUNCE_CATEGORY VARCHAR(100) ,
      I_SMTP_CODE INTEGER,
      C_BOUNCE_REASON VARCHAR(16777216) ,
      C_BATCHID VARCHAR(100) NOT NULL,
      C_TRIGGEREDSENDEXTERNALKEY VARCHAR(200) ,
      C_QUALITY_CD VARCHAR(1) DEFAULT ' ',
      D_TIMESTAMP TIMESTAMP_NTZ(9)  NOT NULL DEFAULT CURRENT_TIMESTAMP())
;

ALTER TABLE IF EXISTS DAAS_TERADATA_RAW.ET_BOUNCES_EVENT ADD SEARCH OPTIMIZATION ON EQUALITY(I_SENDID,I_DMID,C_BATCHID);