-- Step 1: Suspend trip root task

ALTER TASK DAAS_COMMOM.TRIP_ROOT_TASK SUSPEND;

-- Step 2: Code Check-in and Deploy the below procedure
	
	- trip_hotel_domain_pipeline_proc

common/daas_common/ddl/procedure/core/trip_hotel_domain_pipeline_proc.sql,procedure


-- Step 3: Identify the issue records

SELECT COUNT(*) FROM DAAS_CORE.TRIP_DETAIL TD
JOIN DAAS_CORE.TRIP_MASTER TM
ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
WHERE TD.BUSINESS_START_DT > TD.BUSINESS_END_DT
AND TD.DELETE_IND = 'N' AND TD.TRANSACTION_TYPE = 'HOTEL'
AND TM.DELETE_IND = 'N';--31


-- Step 4: Replay issue records from HOTEL_GUEST_RESERVATIONS_FACT

CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT', 
'WHERE HOTEL_GUEST_RESERVATIONS_FACT_SK IN 
(SELECT HOTEL_GUEST_RESERVATIONS_FACT_SK
FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW HGR
WHERE EXISTS
(
	SELECT DISTINCT TD.TRANSACTION_TABLE_SK FROM DAAS_CORE.TRIP_MASTER TM
	JOIN DAAS_CORE.TRIP_DETAIL TD
	ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
	WHERE TD.BUSINESS_START_DT > TD.BUSINESS_END_DT
	AND TD.TRANSACTION_TABLE_SK = HGR.HOTEL_GUEST_RESERVATIONS_FACT_SK
	AND TD.DELETE_IND = ''N''
	AND TD.TRANSACTION_TYPE = ''HOTEL''
)
)', 'HOTELBUSSTENDDT', 100000000);


-- Step 5: Trigger TRIP_ROOT_TASK manually

EXECUTE TASK DAAS_COMMON.TRIP_ROOT_TASK;


-- Step 6: Validate if any recs having BUSINESS_START_DT > BUSINESS_END_DT


SELECT COUNT(*)
FROM DAAS_CORE.TRIP_MASTER TM
JOIN DAAS_CORE.TRIP_DETAIL TD
ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
WHERE TD.BUSINESS_START_DT > TD.BUSINESS_END_DT
AND TD.DELETE_IND = 'N'
AND TM.DELETE_IND = 'N'
AND TD.TRANSACTION_TYPE = 'HOTEL';

--Step 7: Resume trip root task

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK RESUME;