select *
from table(information_schema.task_history(
scheduled_time_range_start=>dateadd('hour',-1,current_timestamp()),
result_limit => 10,
task_name=>'TRIP_ROOT_TASK'));

SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 583 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_FILTERED_TXNS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 558 ORDER BY BATCH_ID DESC LIMIT 5; -- RATINGS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 566 ORDER BY BATCH_ID DESC LIMIT 5; -- HOTEL
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 567 ORDER BY BATCH_ID DESC LIMIT 5; -- POS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 579 ORDER BY BATCH_ID DESC LIMIT 5; -- OFFER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 580 ORDER BY BATCH_ID DESC LIMIT 5; -- COMP
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 581 ORDER BY BATCH_ID DESC LIMIT 5; -- MARKERS
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 582 ORDER BY BATCH_ID DESC LIMIT 5; -- FREEPLAY
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 556 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_RECALCULATION
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 559 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE_CHECK
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 560 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 561 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_TRIP_MASTER
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 564 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE_CHECK_GUEST_GUESTXREF
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 562 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_CUSTOMER_MERGE
SELECT * FROM DAAS_COMMON.BATCH_S02 WHERE JOB_ID = 578 ORDER BY BATCH_ID DESC LIMIT 5; -- TRIP_SUMMARY_WRAPPER

SELECT * FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY_BY_WAREHOUSE(WAREHOUSE_NAME=>'DAAS_PROD_ADHOC_BULK_LOAD_COMPUTE_L')) 
WHERE USER_NAME = 'SYSTEM' 
ORDER BY START_TIME DESC;

SELECT * FROM DAAS_COMMON.JOB WHERE JOB_ID=578;

ALTER TASK DAAS_COMMON.TRIP_ROOT_TASK RESUME;

SHOW TASKS LIKE '%TRIP_ROOT_TASK%';

SHOW PROCEDURES LIKE '%TRIP_DIGITAL_PLA%' IN DAAS_COMMON;

//CALL DAAS_COMMON.DATA_REPLAY_PROC('DAAS_CORE', 'HOTEL_GUEST_RESERVATIONS_FACT', 
//'WHERE HOTEL_GUEST_RESERVATIONS_FACT_SK IN 
//(SELECT HOTEL_GUEST_RESERVATIONS_FACT_SK
//FROM DAAS_CORE_HOTEL_VW.HOTEL_GUEST_RESERVATIONS_FACT_VW HGR
//WHERE EXISTS
//(
//	SELECT DISTINCT TD.TRANSACTION_TABLE_SK FROM DAAS_CORE.TRIP_MASTER TM
//	JOIN DAAS_CORE.TRIP_DETAIL TD
//	ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
//	WHERE TD.BUSINESS_START_DT > TD.BUSINESS_END_DT
//	AND TD.TRANSACTION_TABLE_SK = HGR.HOTEL_GUEST_RESERVATIONS_FACT_SK
//	AND TD.DELETE_IND = ''N''
//	AND TD.TRANSACTION_TYPE = ''HOTEL''
//)
//)', 'HOTELBUSSTENDDT', 100000000);--14

//CALL DAAS_ADHOC.TRIP_DIGITAL_REPLAY_ADHOC_REQUEST_PROC();

//EXECUTE TASK DAAS_COMMON.TRIP_ROOT_TASK;

SELECT COUNT(*)
FROM DAAS_CORE.TRIP_MASTER TM
JOIN DAAS_CORE.TRIP_DETAIL TD
ON TM.TRIP_MASTER_ID = TD.TRIP_MASTER_ID
WHERE TD.BUSINESS_START_DT > TD.BUSINESS_END_DT
AND TD.DELETE_IND = 'N'
AND TM.DELETE_IND = 'N'
AND TD.TRANSACTION_TYPE = 'HOTEL';